#!/usr/bin/env python3
"""Build docs/js/data.js with Seoul + Japan detailed timelines."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).with_name("data.js")

def place(id, name, name_local, city, country, tags, lat, lng, blurb, taxi_address=None):
    p = {
        "id": id, "name": name, "nameJa": name_local, "city": city, "country": country,
        "tags": tags, "lat": lat, "lng": lng, "blurb": blurb,
    }
    if taxi_address:
        p["taxiAddress"] = taxi_address
    return p

PLACES = {}

def add(p):
    PLACES[p["id"]] = p

# --- Seoul ---
for p in [
    place("brick-hotel", "9 Brick Hotel Hongdae", "나인브릭호텔", "Seoul", "KR", ["hotel"], 37.5563, 126.9236, "Hongdae base for Seoul.", "서울특별시 마포구 와우산로 94, 나인브릭호텔"),
    place("icn", "Incheon Airport (ICN)", "인천국제공항", "Seoul", "KR", ["transport"], 37.4602, 126.4407, "Seoul arrival / departure."),
    place("myeongdong", "Myeongdong", "명동", "Seoul", "KR", ["shopping", "food", "neighborhood"], 37.5636, 126.9869, "K-beauty, street food, neon shopping."),
    place("hongdae", "Hongdae", "홍대", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5563, 126.9236, "Student arts district — cafés, bars, street performers."),
    place("gyeongbokgung", "Gyeongbokgung Palace", "경복궁", "Seoul", "KR", ["must-see", "culture"], 37.5796, 126.9770, "Main royal palace — rent hanbok for free entry vibe."),
    place("bukchon", "Bukchon Hanok Village", "북촌한옥마을", "Seoul", "KR", ["must-see", "neighborhood", "culture"], 37.5826, 126.9831, "Traditional hanok hillside lanes."),
    place("ikseon", "Ikseon-dong", "익선동", "Seoul", "KR", ["neighborhood", "food", "culture"], 37.5740, 126.9897, "Hip hanok alleys with cafés and bars."),
    place("insadong", "Insadong", "인사동", "Seoul", "KR", ["shopping", "culture", "food"], 37.5742, 126.9847, "Tea houses, crafts, souvenir shopping."),
    place("gwangjang", "Gwangjang Market", "광장시장", "Seoul", "KR", ["must-see", "food", "market"], 37.5700, 126.9996, "Bindaetteok, mayak gimbap, night market energy (open late)."),
    place("eunpyeong", "Eunpyeong Hanok Village", "은평한옥마을", "Seoul", "KR", ["neighborhood", "culture"], 37.6408, 126.9345, "Quieter traditional village alternative."),
    place("lotte-world", "Lotte World Adventure", "롯데월드", "Seoul", "KR", ["must-see", "park"], 37.5110, 127.0980, "Indoor/outdoor theme park — full day."),
    place("lotte-tower", "Lotte World Tower Seoul Sky", "롯데월드타워", "Seoul", "KR", ["must-see", "view"], 37.5126, 127.1025, "One of the world’s tallest — Seoul Sky observatory."),
    place("seokchon", "Seokchon Lake", "석촌호수", "Seoul", "KR", ["neighborhood", "nature"], 37.5095, 127.1035, "Lake walk beside Lotte Tower."),
    place("jimjilbang", "Jimjilbang (spa complex)", "찜질방", "Seoul", "KR", ["culture", "onsen"], 37.5400, 127.0700, "Korean bathhouse culture — check nearest well-rated spot (e.g. near Jamsil/Gangnam)."),
    place("jogyesa", "Jogyesa Temple", "조계사", "Seoul", "KR", ["temple", "culture"], 37.5735, 126.9825, "Major Buddhist temple near Insadong."),
    place("changdeokgung", "Changdeokgung + Secret Garden", "창덕궁 후원", "Seoul", "KR", ["must-see", "culture"], 37.5794, 126.9910, "UNESCO palace — book Secret Garden timed tour."),
    place("gangnam", "Gangnam", "강남", "Seoul", "KR", ["neighborhood", "shopping"], 37.4979, 127.0276, "Treatments, shopping, K-pop landmarks."),
    place("bongeunsa", "Bongeunsa Temple", "봉은사", "Seoul", "KR", ["temple", "culture"], 37.5152, 127.0574, "Temple beside COEX — calm contrast to Gangnam."),
    place("coex", "COEX & Starfield Library", "코엑스 별마당도서관", "Seoul", "KR", ["must-see", "shopping", "culture"], 37.5117, 127.0595, "Giant mall + iconic Starfield Library."),
    place("dongdaemun", "Dongdaemun Night Market / DDP", "동대문", "Seoul", "KR", ["shopping", "nightlife", "food"], 37.5665, 127.0092, "Night fashion markets + DDP architecture."),
    place("seongsu", "Seongsu-dong", "성수동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5445, 127.0557, "Brooklyn-feel cafés, pop-ups, and design shops."),
    place("n-tower", "N Seoul Tower", "N서울타워", "Seoul", "KR", ["must-see", "view"], 37.5512, 126.9882, "Namsan sunset views + love locks."),
    place("itaewon", "Itaewon", "이태원", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5345, 126.9944, "International bars, LGBTQ+ friendly nightlife."),
]:
    add(p)

# --- Japan (existing + a few extras) ---
for p in [
    place("keio-plaza", "Keio Plaza Hotel Tokyo", "京王プラザホテル", "Tokyo", "JP", ["hotel"], 35.6906, 139.6921, "Shinjuku base.", "東京都新宿区西新宿2-2-1 京王プラザホテル"),
    place("narita", "Narita Airport (NRT)", "成田国際空港", "Tokyo", "JP", ["transport"], 35.7720, 140.3929, "Tokyo arrival/departure."),
    place("shinjuku", "Shinjuku", "新宿", "Tokyo", "JP", ["neighborhood", "food", "nightlife"], 35.6938, 139.7034, "Neon, shopping, Godzilla."),
    place("shibuya-crossing", "Shibuya Crossing", "渋谷スクランブル交差点", "Tokyo", "JP", ["must-see", "icon"], 35.6595, 139.7005, "Scramble + Hachiko."),
    place("meiji-jingu", "Meiji Jingu", "明治神宮", "Tokyo", "JP", ["must-see", "culture", "shrine"], 35.6764, 139.6993, "Forest shrine."),
    place("takeshita", "Takeshita Street", "竹下通り", "Tokyo", "JP", ["food", "shopping"], 35.6702, 139.7050, "Harajuku crepes & youth fashion."),
    place("cat-street", "Cat Street", "キャットストリート", "Tokyo", "JP", ["shopping", "neighborhood"], 35.6658, 139.7038, "Stylish Harajuku side street."),
    place("omotesando", "Omotesando", "表参道", "Tokyo", "JP", ["shopping", "architecture"], 35.6652, 139.7122, "Tree-lined boutiques."),
    place("disneysea", "Tokyo DisneySea", "東京ディズニーシー", "Tokyo", "JP", ["must-see", "park"], 35.6267, 139.8851, "Unique Disney park."),
    place("asakusa", "Asakusa / Senso-ji", "浅草寺", "Tokyo", "JP", ["must-see", "culture", "food"], 35.7148, 139.7967, "Classic temple Tokyo."),
    place("kappabashi", "Kappabashi Street", "合羽橋道具街", "Tokyo", "JP", ["food", "shopping"], 35.7155, 139.7870, "Kitchen-town souvenirs."),
    place("skytree", "Tokyo Skytree", "東京スカイツリー", "Tokyo", "JP", ["must-see", "view"], 35.7101, 139.8107, "634m tower."),
    place("tsukiji", "Tsukiji Outer Market", "築地場外市場", "Tokyo", "JP", ["must-see", "food"], 35.6654, 139.7707, "Breakfast graze."),
    place("imperial-east", "Imperial Palace East Gardens", "皇居東御苑", "Tokyo", "JP", ["culture", "park"], 35.6865, 139.7575, "Quiet castle gardens."),
    place("ginza", "Ginza", "銀座", "Tokyo", "JP", ["shopping", "food"], 35.6712, 139.7649, "Dept stores & depachika."),
    place("teamlab-planets", "teamLab Planets Tokyo", "チームラボプラネッツ", "Tokyo", "JP", ["must-see", "culture"], 35.6490, 139.7868, "Immersive digital art."),
    place("odaiba", "Odaiba / DiverCity Gundam", "お台場", "Tokyo", "JP", ["park", "shopping"], 35.6251, 139.7755, "Gundam + waterfront."),
    place("ameyoko", "Ameyoko Market", "アメ横", "Tokyo", "JP", ["food", "market"], 35.7095, 139.7745, "Street-food market."),
    place("akihabara", "Akihabara", "秋葉原", "Tokyo", "JP", ["park", "shopping"], 35.7023, 139.7745, "Arcades & anime."),
    place("golden-gai", "Shinjuku Golden Gai", "新宿ゴールデン街", "Tokyo", "JP", ["must-see", "nightlife"], 35.6938, 139.7047, "Tiny bar alleys."),
    place("daikanyama", "Daikanyama T-Site", "代官山T-SITE", "Tokyo", "JP", ["culture", "food"], 35.6492, 139.7032, "Bookstore complex."),
    place("nakameguro", "Nakameguro / Meguro River", "中目黒", "Tokyo", "JP", ["neighborhood", "food"], 35.6442, 139.6988, "Riverside boutiques."),
    place("ny-bar", "New York Bar (Park Hyatt)", "ニューヨークバー", "Tokyo", "JP", ["nightlife", "view"], 35.6855, 139.6905, "Lost in Translation bar."),
    place("kajikaso", "Hotel Kajikaso", "ホテルかじか荘", "Hakone", "JP", ["hotel", "onsen"], 35.2335, 139.0885, "Hakone onsen stay.", "神奈川県足柄下郡箱根町湯本692 ホテルかじか荘"),
    place("owakudani", "Owakudani", "大涌谷", "Hakone", "JP", ["must-see", "nature", "food"], 35.2424, 139.0204, "Volcanic valley + black eggs."),
    place("hakone-shrine", "Hakone Shrine", "箱根神社", "Hakone", "JP", ["must-see", "shrine"], 35.2051, 139.0256, "Lakeside torii — best at sunrise."),
    place("lake-ashi", "Lake Ashi Pirate Ship", "箱根海賊船", "Hakone", "JP", ["nature", "park"], 35.2065, 139.0250, "Sightseeing cruise."),
    place("open-air", "Hakone Open-Air Museum", "箱根彫刻の森美術館", "Hakone", "JP", ["culture"], 35.2445, 139.0515, "Outdoor sculpture museum."),
    place("fuji-lawson", "Lawson Kawaguchiko Station", "ローソン河口湖駅前", "Kawaguchiko", "JP", ["icon", "must-see"], 35.4983, 138.7689, "Famous Fuji convenience-store shot."),
    place("oishi-park", "Oishi Park", "大石公園", "Kawaguchiko", "JP", ["must-see", "view"], 35.5245, 138.7470, "Sunset Fuji lakeside."),
    place("chureito", "Chureito Pagoda", "忠霊塔", "Kawaguchiko", "JP", ["must-see", "icon"], 35.5012, 138.8013, "Sunrise pagoda + Fuji."),
    place("fuji-q", "Fuji-Q Highland", "富士急ハイランド", "Kawaguchiko", "JP", ["must-see", "park"], 35.4871, 138.7806, "World-class coasters."),
    place("musse-kyoto", "Hotel Musse Kyoto", "ホテルミュッセ京都四条河原町名鉄", "Kyoto", "JP", ["hotel"], 35.0037, 135.7685, "Kawaramachi base.", "京都府京都市下京区四条通河原町東入真町70 ホテルミュッセ京都四条河原町名鉄"),
    place("kenninji", "Kennin-ji", "建仁寺", "Kyoto", "JP", ["temple", "culture"], 35.0008, 135.7735, "Oldest Zen temple in Kyoto."),
    place("gion", "Gion", "祇園", "Kyoto", "JP", ["must-see", "neighborhood"], 35.0037, 135.7788, "Geisha district."),
    place("pontocho", "Pontocho Alley", "先斗町", "Kyoto", "JP", ["food", "nightlife"], 35.0045, 135.7712, "Dinner alley by the river."),
    place("fushimi-inari", "Fushimi Inari Taisha", "伏見稲荷大社", "Kyoto", "JP", ["must-see", "shrine"], 34.9671, 135.7727, "Thousands of torii."),
    place("kiyomizu", "Kiyomizu-dera", "清水寺", "Kyoto", "JP", ["must-see", "temple"], 34.9949, 135.7850, "Wooden stage temple."),
    place("sannenzaka", "Sannenzaka & Ninenzaka", "三年坂・二年坂", "Kyoto", "JP", ["must-see", "food"], 34.9958, 135.7815, "Stone postcard streets."),
    place("kinkakuji", "Kinkaku-ji", "金閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0394, 135.7292, "Golden Pavilion."),
    place("nishiki", "Nishiki Market", "錦市場", "Kyoto", "JP", ["must-see", "food"], 35.0050, 135.7649, "Kyoto’s kitchen."),
    place("otagi", "Otagi Nenbutsu-ji", "愛宕念仏寺", "Kyoto", "JP", ["must-see", "temple"], 35.0317, 135.6628, "1,200 rakan statues."),
    place("adashino", "Adashino Nenbutsu-ji", "化野念仏寺", "Kyoto", "JP", ["temple", "culture"], 35.0267, 135.6645, "Bamboo & stone Buddhas."),
    place("saga-toriimoto", "Saga Toriimoto", "嵯峨鳥居本", "Kyoto", "JP", ["neighborhood"], 35.0255, 135.6680, "Preserved approach street."),
    place("bamboo", "Arashiyama Bamboo Grove", "竹林の小径", "Kyoto", "JP", ["must-see", "nature"], 35.0173, 135.6721, "Iconic bamboo path."),
    place("kimono-forest", "Kimono Forest", "キモノフォレスト", "Kyoto", "JP", ["icon"], 35.0153, 135.6775, "Kimono cylinder pillars."),
    place("togetsukyo", "Togetsukyo Bridge", "渡月橋", "Kyoto", "JP", ["icon", "nature"], 35.0135, 135.6778, "Arashiyama bridge."),
    place("monkey-park", "Iwatayama Monkey Park", "嵐山モンキーパーク", "Kyoto", "JP", ["park", "nature"], 35.0117, 135.6761, "Monkeys + city view."),
    place("tenryuji", "Tenryu-ji", "天龍寺", "Kyoto", "JP", ["temple", "culture"], 35.0156, 135.6736, "UNESCO Zen garden."),
    place("kurama-dera", "Kurama-dera", "鞍馬寺", "Kyoto", "JP", ["must-see", "temple", "nature"], 35.1181, 135.7709, "Start of forest trek."),
    place("kifune", "Kifune Shrine", "貴船神社", "Kyoto", "JP", ["must-see", "shrine"], 35.1216, 135.7631, "Lantern stone stairs."),
    place("kawadoko", "Kibune Kawadoko Dining", "貴船川床", "Kyoto", "JP", ["must-see", "food"], 35.1205, 135.7638, "Lunch over the stream."),
    place("kurama-onsen", "Kurama Onsen", "鞍馬温泉", "Kyoto", "JP", ["onsen"], 35.1128, 135.7725, "Mountain onsen."),
    place("ginkakuji", "Ginkaku-ji", "銀閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0264, 135.7986, "Silver Pavilion."),
    place("philosophers-path", "Philosopher’s Path", "哲学の道", "Kyoto", "JP", ["neighborhood", "nature"], 35.0205, 135.7955, "Canal stroll."),
    place("nanzenji", "Nanzen-ji", "南禅寺", "Kyoto", "JP", ["temple", "culture"], 35.0116, 135.7945, "Zen temple + aqueduct."),
    place("uji", "Uji / Byodo-in", "宇治・平等院", "Kyoto", "JP", ["food", "temple"], 34.8894, 135.8077, "Matcha capital + Phoenix Hall."),
    place("daiwa-hiroshima", "Daiwa Roynet Hiroshima", "ダイワロイネットホテル広島", "Hiroshima", "JP", ["hotel"], 34.3927, 132.4553, "Central Hiroshima.", "広島県広島市中区三川町1-1 ダイワロイネットホテル広島"),
    place("shukkeien", "Shukkeien Garden", "縮景園", "Hiroshima", "JP", ["culture", "park"], 34.3995, 132.4674, "Miniature landscape garden."),
    place("peace-park", "Peace Memorial Park", "平和記念公園", "Hiroshima", "JP", ["must-see", "culture"], 34.3955, 132.4536, "Dome + museum."),
    place("okonomiyaki", "Okonomi-mura", "お好み村", "Hiroshima", "JP", ["food", "must-see"], 34.3938, 132.4622, "Hiroshima okonomiyaki hall."),
    place("miyajima", "Itsukushima Shrine", "厳島神社", "Hiroshima", "JP", ["must-see", "shrine"], 34.2960, 132.3198, "Floating torii."),
    place("misen", "Mt. Misen Ropeway", "弥山ロープウェイ", "Hiroshima", "JP", ["nature", "view"], 34.2905, 132.3185, "Island summit."),
    place("cross-osaka", "Cross Hotel Osaka", "クロスホテル大阪", "Osaka", "JP", ["hotel"], 34.6693, 135.5013, "Namba / Dotonbori base.", "大阪府大阪市中央区宗右衛門町2-5-15 クロスホテル大阪"),
    place("kuromon", "Kuromon Market", "黒門市場", "Osaka", "JP", ["must-see", "food"], 34.6664, 135.5064, "Osaka’s kitchen."),
    place("osaka-castle", "Osaka Castle", "大阪城", "Osaka", "JP", ["culture", "must-see"], 34.6873, 135.5262, "Castle + park."),
    place("dotonbori", "Dotonbori", "道頓堀", "Osaka", "JP", ["must-see", "food", "nightlife"], 34.6687, 135.5013, "Neon food crawl."),
    place("usj", "Universal Studios Japan", "ユニバーサル・スタジオ・ジャパン", "Osaka", "JP", ["must-see", "park"], 34.6654, 135.4323, "Nintendo World + coasters."),
    place("nara-park", "Nara Park / Todai-ji", "奈良公園・東大寺", "Osaka", "JP", ["must-see", "culture"], 34.6889, 135.8398, "Deer + Great Buddha."),
    place("shinsekai", "Shinsekai / Tsutenkaku", "新世界・通天閣", "Osaka", "JP", ["food", "neighborhood"], 34.6525, 135.5063, "Retro Osaka."),
    place("tenjinbashi", "Tenjinbashi-suji", "天神橋筋商店街", "Osaka", "JP", ["shopping", "food"], 34.7045, 135.5110, "Longest arcade."),
    place("umeda-sky", "Umeda Sky Building", "梅田スカイビル", "Osaka", "JP", ["must-see", "view"], 34.7055, 135.4897, "Floating Garden view."),
    place("ramen-museum", "Instant Ramen Museum", "カップヌードルミュージアム池田", "Osaka", "JP", ["food", "park"], 34.8195, 135.4258, "Make your Cup Noodle."),
    place("solaria", "Solaria Nishitetsu Ginza", "ソラリア西鉄ホテル銀座", "Tokyo", "JP", ["hotel"], 35.6695, 139.7668, "Ginza return hotel.", "東京都中央区銀座1-9-8 ソラリア西鉄ホテル銀座"),
    place("ryogoku", "Ryogoku Kokugikan", "両国国技館", "Tokyo", "JP", ["must-see", "culture"], 35.6971, 139.7935, "Sumo stadium."),
    place("shimokitazawa", "Shimokitazawa", "下北沢", "Tokyo", "JP", ["neighborhood", "shopping"], 35.6616, 139.6683, "Vintage & indie cafés."),
]:
    add(p)

def day(id, date, weekday, city, country, hotel_id, title, summary, food, place_ids, transport, tips, timeline, transfer=None):
    d = {
        "id": id, "date": date, "weekday": weekday, "city": city, "country": country,
        "hotelId": hotel_id, "title": title, "summary": summary, "food": food,
        "placeIds": place_ids, "transport": transport, "tips": tips, "timeline": timeline,
    }
    if transfer:
        d["transfer"] = transfer
    return d

def infer_category(title, place_id, note=""):
    text = f"{title} {note}".lower()
    tags = []
    if place_id and place_id in PLACES:
        tags = PLACES[place_id].get("tags") or []
    if place_id and place_id in PLACES and "hotel" in tags:
        return "hotel"
    if any(k in text for k in ("flight", "train", "shinkansen", "romancecar", "subway", "bus", "ferry", "transfer", "depart", "airport", "ropeway", "monorail")) or "transport" in tags:
        return "transit"
    if any(k in text for k in ("breakfast", "lunch", "dinner", "food", "market", "crepe", "ramen", "sushi", "café", "cafe", "okonomi", "graze", "snack", "brunch")) or "food" in tags or "market" in tags:
        return "dining"
    if any(k in text for k in ("shop", "souvenir", "arcade street", "ginza", "depachika", "don quijote")) or "shopping" in tags:
        return "shopping"
    if any(k in text for k in ("temple", "shrine", "palace", "garden", "museum", "zen", "sumo", "tea", "hanok", "secret garden")) or "culture" in tags or "temple" in tags or "shrine" in tags:
        return "culture"
    if "park" in tags or any(k in text for k in ("disney", "universal", "fuji-q", "lotte world", "teamlab", "skytree", "tower", "park", "monkey", "cruise", "rope drop")):
        return "attraction"
    if "nightlife" in tags:
        return "dining"
    return "attraction"

def t(time, title, place_id=None, note="", end=None, category=None):
    item = {"time": time, "title": title, "note": note}
    if place_id:
        item["placeId"] = place_id
    if end:
        item["end"] = end
    if category:
        item["category"] = category
    return item

TRANSFERS = {
    "d06": {
        "mode": "flight",
        "label": "Seoul → Tokyo",
        "detail": "ICN → NRT (placeholder flight time)",
        "duration": "~2.5h flight + transfers",
        "fromCity": "Seoul",
        "toCity": "Tokyo",
    },
    "d11": {
        "mode": "train",
        "label": "Tokyo → Hakone",
        "detail": "Odakyu Romancecar from Shinjuku",
        "duration": "~1h 20–1h 45m",
        "fromCity": "Tokyo",
        "toCity": "Hakone",
    },
    "d12": {
        "mode": "bus",
        "label": "Hakone → Kawaguchiko",
        "detail": "Local bus via Gotemba + Fujikyu bus",
        "duration": "~1.5–2h",
        "fromCity": "Hakone",
        "toCity": "Kawaguchiko",
    },
    "d13": {
        "mode": "bus",
        "label": "Optional night bus → Kyoto",
        "detail": "Willer / Fujikyu / Kintetsu from Fujisan or Fuji-Q BT",
        "duration": "~8.5–9.5h overnight",
        "fromCity": "Kawaguchiko",
        "toCity": "Kyoto",
    },
    "d14": {
        "mode": "train",
        "label": "Arrive Kyoto",
        "detail": "Night bus arrival or Mishima → Shinkansen morning route",
        "duration": "Overnight or ~3.5–4h day route",
        "fromCity": "Kawaguchiko",
        "toCity": "Kyoto",
    },
    "d19": {
        "mode": "train",
        "label": "Kyoto → Hiroshima",
        "detail": "Nozomi Shinkansen",
        "duration": "~2h 30m",
        "fromCity": "Kyoto",
        "toCity": "Hiroshima",
    },
    "d21": {
        "mode": "train",
        "label": "Hiroshima → Osaka",
        "detail": "Nozomi to Shin-Osaka + Midosuji to Namba",
        "duration": "~2h 30m",
        "fromCity": "Hiroshima",
        "toCity": "Osaka",
    },
    "d25": {
        "mode": "train",
        "label": "Osaka → Tokyo",
        "detail": "Nozomi Shinkansen + local to Ginza",
        "duration": "~2.5–3h",
        "fromCity": "Osaka",
        "toCity": "Tokyo",
    },
    "d30": {
        "mode": "flight",
        "label": "Tokyo → Home",
        "detail": "Narita evening departure (placeholder)",
        "duration": "Allow 2.5–3h to airport",
        "fromCity": "Tokyo",
        "toCity": "Home",
    },
}

DAYS = [
  # SEOUL
  day("d01", "2026-08-27", "Thursday", "Seoul", "KR", "brick-hotel",
      "Arrive Seoul — settle & Myeongdong",
      "Land, check in near Hongdae, light first evening in Myeongdong (Hongdae if you still have energy).",
      "Myeongdong street food — tteokbokki, egg bread, hotteok.",
      ["icn", "brick-hotel", "myeongdong", "hongdae"],
      ["Airport railroad / taxi ICN → Hongdae (~1h).", "Subway Hongdae → Myeongdong (~25–35m)."],
      ["Keep it light — jet lag day.", "Get a T-money card for Seoul transit."],
      [
        t("14:00", "Land at Incheon (ICN)", "icn", "Clear immigration, grab T-money / SIM."),
        t("15:30", "Transfer to Hongdae hotel", "brick-hotel", "AREX + subway or taxi (~60–75m)."),
        t("17:00", "Check in & freshen up", "brick-hotel", "Shower, short rest."),
        t("18:30", "Myeongdong evening stroll", "myeongdong", "Shopping + street-food dinner.", "21:30"),
        t("21:45", "Optional Hongdae nightcap", "hongdae", "Only if energy remains — otherwise sleep."),
      ]),
  day("d02", "2026-08-28", "Friday", "Seoul", "KR", "brick-hotel",
      "Palaces, hanok lanes & Gwangjang Market",
      "Culture day: Hongdae café → Gyeongbokgung (+ hanbok) → Bukchon → Ikseon-dong → Insadong → Gwangjang dinner.",
      "Gwangjang Market — bindaetteok, mayak gimbap, noodles.",
      ["hongdae", "gyeongbokgung", "bukchon", "ikseon", "insadong", "gwangjang"],
      ["Hongdae → Gyeongbokgung subway (~25m).", "Walk Bukchon → Ikseon → Insadong.", "Bus/subway to Gwangjang."],
      ["Rent hanbok near the palace for photos + free entry perk.", "Alt quieter start: Eunpyeong Hanok Village first."],
      [
        t("09:00", "Café breakfast in Hongdae", "hongdae", "Easy start near the hotel."),
        t("10:15", "Gyeongbokgung Palace", "gyeongbokgung", "Rent hanbok if you want the full look. Watch for changing of the guard timing.", "12:30"),
        t("12:45", "Bukchon Hanok Village walk", "bukchon", "Hill lanes + photo stops — be respectful of residents.", "14:00"),
        t("14:15", "Ikseon-dong wander", "ikseon", "Cafés in renovated hanok alleys.", "16:00"),
        t("16:15", "Insadong afternoon", "insadong", "Tea, crafts, souvenirs.", "18:00"),
        t("18:30", "Dinner at Gwangjang Market", "gwangjang", "Market open late — go hungry (≈19:00–22:30).", "22:00"),
      ]),
  day("d03", "2026-08-29", "Saturday", "Seoul", "KR", "brick-hotel",
      "Lotte World, Seoul Sky & jimjilbang",
      "Full amusement-park day at Lotte World, tower views, lake stroll, Korean spa, then Hongdae night.",
      "Lotte mall food court / park snacks; late Hongdae bites.",
      ["lotte-world", "lotte-tower", "seokchon", "jimjilbang", "hongdae"],
      ["Subway to Jamsil / Lotte World (~40–50m from Hongdae).", "Tower & lake are next door."],
      ["Buy Lotte World tickets ahead.", "Jimjilbang: bring or rent towels; follow floor etiquette."],
      [
        t("08:30", "Convenience-store breakfast", "brick-hotel", "Quick fuel before the park."),
        t("10:00", "Lotte World Adventure", "lotte-world", "Indoor + outdoor zones — full park day.", "17:30"),
        t("18:00", "Lotte World Tower Seoul Sky", "lotte-tower", "Observatory sunset/evening views.", "19:30"),
        t("19:45", "Seokchon Lake stroll", "seokchon", "Easy wind-down by the water.", "20:30"),
        t("21:00", "Jimjilbang session", "jimjilbang", "Heat rooms + rest culture — classic Korea.", "23:00"),
        t("23:30", "Back to Hongdae", "hongdae", "Shower at hotel; optional late bar if still awake."),
      ]),
  day("d04", "2026-08-30", "Sunday", "Seoul", "KR", "brick-hotel",
      "Temples, Secret Garden, Gangnam & Dongdaemun",
      "Jogyesa → Changdeokgung Secret Garden → Gangnam (optional treatment) → Bongeunsa → COEX/Starfield → Dongdaemun night.",
      "Temple-area cafés midday; Dongdaemun street snacks at night.",
      ["jogyesa", "changdeokgung", "gangnam", "bongeunsa", "coex", "dongdaemun"],
      ["Book Secret Garden timed entry.", "Gangnam → COEX short hop; evening to Dongdaemun."],
      ["Secret Garden sells out — reserve online.", "Treatment slot is optional — keep if booked."],
      [
        t("09:00", "Hongdae animal café / easy breakfast", "hongdae", "Fun, chill start."),
        t("10:15", "Jogyesa Temple", "jogyesa", "Calm Buddhist stop near downtown.", "11:15"),
        t("11:30", "Changdeokgung + Secret Garden", "changdeokgung", "Timed Secret Garden tour is the highlight.", "14:00"),
        t("14:30", "Travel to Gangnam", "gangnam", "Optional booked skin / beauty treatment window.", "16:30"),
        t("16:45", "Bongeunsa Temple", "bongeunsa", "Quick temple pause beside the malls.", "17:30"),
        t("17:45", "COEX & Starfield Library", "coex", "Photos + shopping + AC break.", "19:30"),
        t("20:00", "Dongdaemun night market & malls", "dongdaemun", "DDP, APM, night fashion energy.", "23:00"),
      ]),
  day("d05", "2026-08-31", "Monday", "Seoul", "KR", "brick-hotel",
      "Seongsu, N Seoul Tower sunset & Itaewon",
      "Trendy Seongsu morning (optional treatment), Namsan sunset, Itaewon nightlife.",
      "Seongsu café brunch; Itaewon dinner + drinks.",
      ["seongsu", "n-tower", "itaewon"],
      ["Hongdae → Seongsu (~35–45m).", "Seongsu → Namsan (~40m).", "Walk/taxi Namsan → Itaewon."],
      ["Book N Seoul Tower tickets for sunset.", "Itaewon is diverse & LGBTQ+ friendly."],
      [
        t("09:30", "Seongsu-dong brunch + wander", "seongsu", "Cafés, pop-ups, design shops. Optional 2nd treatment here.", "13:30"),
        t("14:00", "Free / rest / packing buffer", "brick-hotel", "Or keep exploring Seongsu."),
        t("16:30", "Head to Namsan", "n-tower", "Arrive before sunset queues."),
        t("17:30", "N Seoul Tower sunset", "n-tower", "Views + love locks.", "19:30"),
        t("20:00", "Itaewon evening", "itaewon", "Dinner, bars, nightlife.", "24:00"),
      ]),
  day("d06", "2026-09-01", "Tuesday", "Tokyo", "JP", "keio-plaza",
      "Seoul → Tokyo travel day",
      "Morning departure from Seoul, evening arrival Tokyo Shinjuku — keep plans light.",
      "Airport food + simple Shinjuku dinner.",
      ["icn", "narita", "keio-plaza", "shinjuku"],
      ["Hotel → ICN with buffer.", "Flight Seoul → Tokyo.", "Narita → Keio Plaza private transfer / train (~1.5h)."],
      ["Confirm flight times and re-check luggage rules.", "Suica/Pasmo on arrival."],
      [
        t("08:00", "Pack & checkout", "brick-hotel", "Leave bags ready."),
        t("09:30", "Transfer to Incheon", "icn", "Aim for airport 2.5–3h before flight."),
        t("13:00", "Flight to Tokyo", "icn", "Adjust to your actual flight time."),
        t("17:30", "Land Narita & transfer", "narita", "Driver or Narita Express / Keisei."),
        t("19:30", "Check in Shinjuku", "keio-plaza", "Freshen up."),
        t("20:30", "Light Shinjuku dinner", "shinjuku", "Near hotel only — early sleep."),
      ]),
  # TOKYO
  day("d07", "2026-09-02", "Wednesday", "Tokyo", "JP", "keio-plaza",
      "Shibuya, Meiji & Harajuku",
      "Full classic Tokyo arc with timed walking blocks.",
      "Takeshita crepes; Omotesando café.",
      ["shibuya-crossing", "meiji-jingu", "takeshita", "cat-street", "omotesando"],
      ["Yamanote to Shibuya (~20m).", "Yoyogi for Meiji.", "Walk Harajuku cluster.", "Return Harajuku→Shinjuku."],
      ["Passport for tax-free.", "Build rest stops."],
      [
        t("09:00", "Breakfast near hotel", "shinjuku"),
        t("10:00", "Shibuya Crossing + Hachiko", "shibuya-crossing", "Hikarie 11F free view if clear.", "11:30"),
        t("11:45", "Meiji Jingu", "meiji-jingu", "Forest shrine — write an ema wish.", "13:00"),
        t("13:15", "Takeshita Street lunch snacks", "takeshita", "Crepes + people-watching.", "14:30"),
        t("14:45", "Cat Street", "cat-street", "Calmer boutiques.", "16:00"),
        t("16:15", "Omotesando stroll", "omotesando", "Architecture + coffee.", "18:00"),
        t("18:30", "Return Shinjuku / dinner", "shinjuku"),
      ]),
  day("d08", "2026-09-03", "Thursday", "Tokyo", "JP", "keio-plaza",
      "Tokyo DisneySea — full park day",
      "Rope-drop to fireworks energy. Park day = timeline is ride-flexible.",
      "In-park dining — book popular restaurants early in the app.",
      ["disneysea"],
      ["JR to Maihama / Resort Gateway + monorail.", "Leave Shinjuku by ~07:30."],
      ["Dated tickets + app ready.", "Premier Access for top rides if needed."],
      [
        t("07:30", "Depart Shinjuku", "keio-plaza", "Buffer for security/entry."),
        t("09:00", "Park open / rope drop", "disneysea", "Hit headliners first.", "12:30"),
        t("12:30", "Lunch in park", "disneysea"),
        t("13:30", "Afternoon attractions", "disneysea", "Shows + secondary rides.", "18:00"),
        t("18:00", "Dinner + evening vibe", "disneysea", "Stay for night atmosphere if energy allows.", "21:00"),
        t("21:30", "Return Shinjuku", "keio-plaza"),
      ]),
  day("d09", "2026-09-04", "Friday", "Tokyo", "JP", "keio-plaza",
      "Asakusa, Kappabashi & Skytree",
      "Old Tokyo morning, kitchen street, tower afternoon.",
      "Nakamise snacks; Solamachi dinner option.",
      ["asakusa", "kappabashi", "skytree"],
      ["Subway to Asakusa.", "Walk Kappabashi.", "Tobu Skytree Line."],
      ["Book Skytree tickets.", "Senso-ji calmer before 16:00."],
      [
        t("09:00", "Travel to Asakusa", "asakusa"),
        t("09:30", "Senso-ji & Nakamise", "asakusa", "Info center 8F view first if you want the overview.", "12:00"),
        t("12:15", "Lunch in Asakusa", "asakusa"),
        t("13:30", "Kappabashi kitchen street", "kappabashi", "Knives / plastic food souvenirs.", "15:00"),
        t("15:30", "Tokyo Skytree + Solamachi", "skytree", "Observatory timed entry.", "18:30"),
        t("19:00", "Dinner & return Shinjuku", "shinjuku"),
      ]),
  day("d10", "2026-09-05", "Saturday", "Tokyo", "JP", "keio-plaza",
      "teamLab Planets & Odaiba",
      "Timed art entry, then Gundam / waterfront afternoon.",
      "Odaiba malls for lunch/dessert.",
      ["teamlab-planets", "odaiba"],
      ["Subway to Toyosu area.", "Yurikamome/Rinkai to Odaiba."],
      ["Book teamLab weeks ahead.", "Roll-up clothes for water rooms."],
      [
        t("09:30", "Arrive teamLab Planets", "teamlab-planets", "Be 10–15m early for timed entry.", "12:00"),
        t("12:30", "Travel to Odaiba", "odaiba"),
        t("13:00", "Lunch + DiverCity Gundam", "odaiba", "Optional Joypolis if you want more rides.", "17:00"),
        t("17:30", "Bay area free time / return", "odaiba"),
        t("19:00", "Dinner Shinjuku", "shinjuku"),
      ]),
  day("d11", "2026-09-06", "Sunday", "Hakone", "JP", "kajikaso",
      "Tokyo → Hakone: Owakudani & onsen night",
      "Romancecar out of Shinjuku, volcanic valley, ryokan onsen dinner.",
      "Black eggs; kaiseki / hotel dinner.",
      ["owakudani", "open-air", "kajikaso"],
      ["Odakyu Romancecar Shinjuku → Hakone-Yumoto (~1h 20–1h 45m, ~¥2,470).", "Ropeway/bus to Owakudani."],
      ["Forward big bags to Kyoto.", "Skip Open-Air Museum if short on time."],
      [
        t("08:30", "Checkout & Romancecar", "keio-plaza", "Send luggage ahead if using takkyubin."),
        t("11:00", "Arrive Hakone-Yumoto", "kajikaso", "Drop bags if possible."),
        t("12:00", "Optional Open-Air Museum", "open-air", "Skip if you prefer more mountain time.", "14:00"),
        t("14:30", "Owakudani", "owakudani", "Black eggs + Fuji views if clear.", "16:30"),
        t("17:30", "Check in + onsen", "kajikaso", "Rinse first; enjoy baths before dinner."),
        t("19:00", "Ryokan dinner", "kajikaso", "Early night — sunrise shrine tomorrow."),
      ]),
  day("d12", "2026-09-07", "Monday", "Kawaguchiko", "JP", None,
      "Hakone sunrise → Kawaguchiko sunset",
      "Hakone Shrine at dawn, optional pirate ship, bus to Fuji lakes, Lawson photo, Oishi Park sunset.",
      "Convenience picnic + lakeside dinner.",
      ["hakone-shrine", "lake-ashi", "fuji-lawson", "oishi-park"],
      ["Hakone → Gotemba bus → Fujikyu to Kawaguchiko (~1.5–2h, ¥1,600–2,100)."],
      ["Sleep early for Chureito sunrise.", "Confirm Kawaguchiko hotel."],
      [
        t("05:15", "Wake for sunrise", "kajikaso"),
        t("05:45", "Hakone Shrine torii", "hakone-shrine", "Best light & fewer people.", "07:15"),
        t("07:30", "Breakfast / checkout", "kajikaso"),
        t("08:30", "Optional Lake Ashi cruise", "lake-ashi", "Skip if transferring early.", "09:30"),
        t("10:00", "Bus transfer toward Kawaguchiko", None, "Gotemba change → Fujikyu bus.", "12:30"),
        t("13:00", "Fuji Lawson photo stop", "fuji-lawson", "Icon shot near the station."),
        t("14:00", "Check in & rest", None, "Kawaguchiko hotel."),
        t("16:30", "Oishi Park sunset", "oishi-park", "Lakeside Fuji views.", "18:30"),
        t("19:00", "Dinner & early sleep", None, "Tomorrow is sunrise + Fuji-Q."),
      ]),
  day("d13", "2026-09-08", "Tuesday", "Kawaguchiko", "JP", None,
      "Chureito sunrise & Fuji-Q Highland",
      "Pagoda dawn photos then full coaster day. Night bus to Kyoto optional tonight.",
      "Park food; light dinner before night bus if taking it.",
      ["chureito", "fuji-q"],
      ["Short hop to Chureito + stairs.", "Fuji-Q for opening.", "Night bus ~21:00 from Fujisan / Fuji-Q BT if chosen."],
      ["Night bus saves a hotel night (¥8,200–10,200) → Kyoto ~06:00.", "Or sleep and take morning Mishima→Shinkansen."],
      [
        t("04:45", "Depart for Chureito Pagoda", "chureito", "~400 stairs — headlamp helpful."),
        t("05:30", "Sunrise at Chureito", "chureito", "Classic Fuji + pagoda shot.", "07:00"),
        t("07:30", "Breakfast back near hotel", None),
        t("09:00", "Fuji-Q Highland", "fuji-q", "Full amusement park day.", "18:30"),
        t("19:00", "Dinner / rest", None),
        t("21:00", "Optional night bus to Kyoto", None, "Willer / Fujikyu / Kintetsu from Fujisan or Fuji-Q BT.", "06:00"),
      ]),
  day("d14", "2026-09-09", "Wednesday", "Kyoto", "JP", "musse-kyoto",
      "Arrive Kyoto — Kennin-ji, Gion, Pontocho",
      "Drop bags, nap if night-bused, calm Zen temple, lantern dinner alleys.",
      "Pontocho riverside dinner.",
      ["musse-kyoto", "kenninji", "gion", "pontocho"],
      ["Arrive Kyoto Station Hachijo if night bus.", "Or Mishima Shinkansen morning (~3.5–4h)."],
      ["Forward bags to hotel ahead of time.", "Respectful photos in Gion."],
      [
        t("06:30", "Arrive Kyoto / hotel drop", "musse-kyoto", "Nap if room ready."),
        t("10:00", "Brunch near Kawaramachi", "nishiki", "Or hotel area café."),
        t("11:30", "Kennin-ji", "kenninji", "Quiet Zen reset.", "13:00"),
        t("15:00", "Rest / shower / free time", "musse-kyoto"),
        t("17:00", "Gion at dusk", "gion", "Hanamikoji + Shirakawa lanes.", "18:30"),
        t("19:00", "Dinner in Pontocho", "pontocho", "Then Kamogawa stroll.", "21:30"),
      ]),
  day("d15", "2026-09-10", "Thursday", "Kyoto", "JP", "musse-kyoto",
      "Fushimi Inari, Higashiyama & Kinkaku-ji",
      "Early torii climb, Kiyomizu lanes, Golden Pavilion, Nishiki graze.",
      "Convenience breakfast; Nishiki tasting later.",
      ["fushimi-inari", "kiyomizu", "sannenzaka", "kinkakuji", "nishiki"],
      ["Keihan/JR to Fushimi early.", "Bus/taxi between Higashiyama & Kinkaku-ji."],
      ["Huge day — start before 08:00.", "Climb higher at Fushimi for fewer people."],
      [
        t("07:00", "Fushimi Inari Taisha", "fushimi-inari", "Climb beyond first gates.", "10:00"),
        t("10:30", "Café break", None, "Recover with coffee/matcha."),
        t("11:30", "Kiyomizu-dera", "kiyomizu", "Wooden stage + views.", "13:00"),
        t("13:15", "Sannenzaka & Ninenzaka", "sannenzaka", "Matcha snacks + alleys.", "15:00"),
        t("15:45", "Kinkaku-ji (Golden Pavilion)", "kinkakuji", "Taxi/bus across town.", "17:15"),
        t("18:00", "Nishiki Market dinner graze", "nishiki", "Back in center.", "20:00"),
      ]),
  day("d16", "2026-09-11", "Friday", "Kyoto", "JP", "musse-kyoto",
      "West Kyoto — statues, bamboo & monkeys",
      "Otagi & Adashino → Saga street → bamboo → Kimono Forest → bridge → monkey park.",
      "Arashiyama lunch near Togetsukyo.",
      ["otagi", "adashino", "saga-toriimoto", "bamboo", "tenryuji", "kimono-forest", "togetsukyo", "monkey-park"],
      ["Bus toward Saga-Arashiyama; walk the chain west→east.", "Return JR/Hankyu."],
      ["Bamboo before 9:00 if possible.", "Monkey park is a real climb."],
      [
        t("08:00", "Otagi Nenbutsu-ji", "otagi", "1,200 rakan statues.", "09:15"),
        t("09:30", "Adashino Nenbutsu-ji", "adashino", "Bamboo & stone Buddhas.", "10:30"),
        t("10:45", "Saga Toriimoto street", "saga-toriimoto", "Preserved approach road."),
        t("11:15", "Bamboo Grove + Tenryu-ji", "bamboo", "Optional temple garden next door.", "12:45"),
        t("13:00", "Kimono Forest + lunch", "kimono-forest", "Eat near the station/bridge.", "14:30"),
        t("14:45", "Togetsukyo Bridge area", "togetsukyo"),
        t("15:15", "Monkey Park Iwatayama", "monkey-park", "~20m uphill; ¥600.", "17:00"),
        t("18:30", "Return center + dinner", "musse-kyoto"),
      ]),
  day("d17", "2026-09-12", "Saturday", "Kyoto", "JP", "musse-kyoto",
      "Kurama → Kibune forest day",
      "Eizan Railway, mountain temple, forest trek, Kifune shrine, kawadoko lunch, onsen.",
      "Kawadoko lunch over the stream — book if possible.",
      ["kurama-dera", "kifune", "kawadoko", "kurama-onsen"],
      ["To Demachiyanagi → Eizan to Kurama (~30m, ~¥430).", "Trek ~45m.", "Return Kibuneguchi Eizan."],
      ["One of the best days — don’t skip if weather is ok.", "Light rain layer."],
      [
        t("08:30", "Train to Kurama", "kurama-dera", "Via Demachiyanagi + Eizan."),
        t("09:30", "Kurama-dera visit", "kurama-dera", "Temple on the mountain.", "10:45"),
        t("11:00", "Forest trek to Kibune", None, "About 45 minutes through cedar forest.", "11:45"),
        t("12:00", "Kifune Shrine", "kifune", "Lantern stone stairs.", "13:00"),
        t("13:15", "Kawadoko lunch", "kawadoko", "Platforms above the cool stream.", "15:00"),
        t("15:30", "Kurama Onsen soak", "kurama-onsen", "Optional but perfect after hiking.", "17:30"),
        t("18:30", "Return Kyoto + easy dinner", "musse-kyoto"),
      ]),
  day("d18", "2026-09-13", "Sunday", "Kyoto", "JP", "musse-kyoto",
      "Ginkaku-ji, Philosopher’s Path & Nanzen-ji",
      "East Kyoto calm day — gardens, canal cafés, aqueduct temple.",
      "Café breakfast on the path; lunch near Nanzen-ji.",
      ["ginkakuji", "philosophers-path", "nanzenji"],
      ["Bus to Ginkaku-ji; walk south; bus/taxi home."],
      ["Forward bags to Hiroshima tonight.", "Celebratory Kyoto dinner."],
      [
        t("08:30", "Ginkaku-ji (Silver Pavilion)", "ginkakuji", "Gardens in morning light.", "10:15"),
        t("10:30", "Philosopher’s Path stroll", "philosophers-path", "Cafés + slow canal walk.", "12:30"),
        t("12:45", "Nanzen-ji + lunch", "nanzenji", "See the brick aqueduct.", "15:00"),
        t("16:00", "Free time / packing", "musse-kyoto"),
        t("19:00", "Farewell Kyoto dinner", "pontocho", "Or anywhere you loved."),
      ]),
  day("d19", "2026-09-14", "Monday", "Hiroshima", "JP", "daiwa-hiroshima",
      "Shinkansen to Hiroshima",
      "Garden calm, Peace Park & Museum, okonomiyaki dinner.",
      "Hiroshima-style okonomiyaki at Okonomi-mura.",
      ["daiwa-hiroshima", "shukkeien", "peace-park", "okonomiyaki"],
      ["Nozomi Kyoto → Hiroshima (~2h 30m) + tram."],
      ["Give museum real time.", "Heavy content — comfort food after."],
      [
        t("09:00", "Shinkansen to Hiroshima", None, "From Kyoto Station."),
        t("12:00", "Check in / drop bags", "daiwa-hiroshima"),
        t("13:00", "Shukkeien Garden", "shukkeien", "Gentle landing walk.", "14:30"),
        t("15:00", "Peace Memorial Park & Museum", "peace-park", "Allow 1.5–2h.", "17:30"),
        t("18:30", "Okonomiyaki dinner", "okonomiyaki", "Okonomi-mura food hall.", "20:30"),
      ]),
  day("d20", "2026-09-15", "Tuesday", "Hiroshima", "JP", "daiwa-hiroshima",
      "Miyajima Island day",
      "Ferry to the island, shrine (tide-aware), snacks, Mt. Misen.",
      "Momiji manju, oysters in season, eel.",
      ["miyajima", "misen"],
      ["Tram+JR to Miyajimaguchi (~55m), ferry ~10m."],
      ["Check tide times.", "Leave early."],
      [
        t("08:00", "Depart hotel for Miyajima", "daiwa-hiroshima"),
        t("09:30", "Ferry + Omotesando snacks", "miyajima"),
        t("10:15", "Itsukushima Shrine", "miyajima", "Match visit to tide if possible.", "12:00"),
        t("12:30", "Lunch on the island", "miyajima"),
        t("13:30", "Mt. Misen ropeway & summit", "misen", "Extra walk beyond ropeway.", "16:30"),
        t("17:00", "Low-tide torii revisit (if timing works)", "miyajima", "Or café rest."),
        t("18:30", "Return Hiroshima", "daiwa-hiroshima"),
      ]),
  day("d21", "2026-09-16", "Wednesday", "Osaka", "JP", "cross-osaka",
      "Osaka arrival — market, castle, Dotonbori",
      "Kuromon graze, Osaka Castle, neon night under the hotel.",
      "Kuromon by day; takoyaki/okonomiyaki/kushikatsu by night.",
      ["cross-osaka", "kuromon", "osaka-castle", "dotonbori"],
      ["Hiroshima → Shin-Osaka Nozomi → Midosuji to Namba."],
      ["Rest before Dotonbori.", "Hotel is perfectly placed."],
      [
        t("09:00", "Shinkansen to Osaka", None),
        t("12:00", "Check in Cross Hotel", "cross-osaka"),
        t("12:30", "Kuromon Market lunch graze", "kuromon", "Arrive hungry.", "14:30"),
        t("15:00", "Osaka Castle", "osaka-castle", "Museum + grounds.", "17:00"),
        t("17:30", "Hotel rest", "cross-osaka"),
        t("19:00", "Dotonbori food crawl", "dotonbori", "Glico sign photos + street food.", "22:00"),
      ]),
  day("d22", "2026-09-17", "Thursday", "Osaka", "JP", "cross-osaka",
      "Universal Studios Japan",
      "Full park day — Nintendo World, coasters, shows.",
      "Park snacks; late Namba ramen optional.",
      ["usj"],
      ["Subway to Universal City (~25–35m). Leave by ~07:45."],
      ["Express Pass strategy.", "Check Nintendo World entry rules."],
      [
        t("07:45", "Depart hotel", "cross-osaka"),
        t("09:00", "USJ rope drop", "usj", "Priority headliners / Nintendo World.", "12:30"),
        t("12:30", "Lunch in park", "usj"),
        t("13:30", "Afternoon rides & shows", "usj", "Continue headliners and shows.", "18:30"),
        t("18:30", "Evening park / parade options", "usj", "Stay for night vibe if energy allows.", "21:00"),
        t("21:30", "Return Namba", "cross-osaka"),
      ]),
  day("d23", "2026-09-18", "Friday", "Osaka", "JP", "cross-osaka",
      "Nara day trip & Shinsekai",
      "Deer park + Todai-ji, then retro Shinsekai night.",
      "Kakinoha-zushi / mochi; kushikatsu in Shinsekai.",
      ["nara-park", "shinsekai"],
      ["Kintetsu Rapid from Osaka-Namba (~45m)."],
      ["Leave 08:00–08:30.", "Guard bags from deer."],
      [
        t("08:15", "Train to Nara", "nara-park"),
        t("09:15", "Nara Park & deer", "nara-park", "Todai-ji, Kasuga area.", "13:00"),
        t("13:15", "Lunch + Nakatanidou mochi if timing works", "nara-park"),
        t("15:00", "Return toward Osaka", None),
        t("17:00", "Rest at hotel", "cross-osaka"),
        t("19:00", "Shinsekai & Tsutenkaku", "shinsekai", "Retro vibes + kushikatsu.", "22:00"),
      ]),
  day("d24", "2026-09-19", "Saturday", "Osaka", "JP", "cross-osaka",
      "Arcade, Umeda Sky & ramen museum",
      "Tenjinbashi shopping, observatory views, Cup Noodle DIY in Ikeda.",
      "Arcade lunch; souvenir Cup Noodle.",
      ["tenjinbashi", "umeda-sky", "ramen-museum"],
      ["Sakaisuji to Ogimachi.", "Hankyu to Ikeda for museum."],
      ["Lighter day.", "Pack for Tokyo tomorrow."],
      [
        t("09:30", "Tenjinbashi-suji arcade", "tenjinbashi", "Japan’s longest covered street.", "12:30"),
        t("13:00", "Umeda Sky Building", "umeda-sky", "Floating Garden Observatory.", "15:00"),
        t("15:45", "Instant Ramen Museum (Ikeda)", "ramen-museum", "Design your Cup Noodle.", "18:00"),
        t("19:30", "Final Osaka dinner near Dotonbori", "dotonbori"),
      ]),
  day("d25", "2026-09-20", "Sunday", "Tokyo", "JP", "solaria",
      "Return to Tokyo — Ginza ease",
      "Shinkansen back; soft landing with Ginza / depachika.",
      "Depachika picnic or Ginza sushi.",
      ["solaria", "ginza"],
      ["Nozomi to Tokyo + local to Higashi-ginza."],
      ["Easy pace.", "Check sumo tickets for midweek."],
      [
        t("09:30", "Shinkansen to Tokyo", None),
        t("13:00", "Check in Solaria", "solaria"),
        t("14:30", "Ginza / Marunouchi wander", "ginza", "Architecture + shopping.", "18:00"),
        t("18:30", "Depachika dinner picnic", "ginza"),
      ]),
  day("d26", "2026-09-21", "Monday", "Tokyo", "JP", "solaria",
      "Tsukiji breakfast, palace & Ginza",
      "Food-first morning then gardens and shopping.",
      "Tsukiji is the main event.",
      ["tsukiji", "imperial-east", "ginza"],
      ["Walk/subway from Ginza hotel."],
      ["Arrive Tsukiji before 09:00."],
      [
        t("08:00", "Tsukiji Outer Market breakfast", "tsukiji", "Graze stall to stall.", "10:30"),
        t("11:00", "Imperial Palace East Gardens", "imperial-east", "Quiet green reset.", "13:00"),
        t("13:30", "Lunch + Ginza afternoon", "ginza", "Uniqlo flagship, GINZA SIX, Loft.", "18:00"),
        t("19:00", "Dinner of choice", "ginza"),
      ]),
  day("d27", "2026-09-22", "Tuesday", "Tokyo", "JP", "solaria",
      "Ueno, Akihabara & Golden Gai",
      "Market snacks, arcades, tiny bars.",
      "Ameyoko grazing; yakitori before Golden Gai.",
      ["ameyoko", "akihabara", "golden-gai"],
      ["Yamanote to Okachimachi/Akihabara; evening toward Shinjuku for Golden Gai."],
      ["Some bars regulars-only — try next door."],
      [
        t("10:00", "Ameyoko Market", "ameyoko", "Street food under the tracks.", "12:30"),
        t("13:00", "Akihabara arcades & shops", "akihabara", "Optional maid café for laughs.", "17:00"),
        t("17:30", "Return / rest", "solaria"),
        t("20:00", "Golden Gai night", "golden-gai", "1–2 tiny bars.", "23:00"),
      ]),
  day("d28", "2026-09-23", "Wednesday", "Tokyo", "JP", "solaria",
      "Sumo day (or encore)",
      "Ryogoku tournament if tickets exist; else Shimokitazawa / favorites.",
      "Chanko nabe if doing sumo.",
      ["ryogoku", "shimokitazawa", "daikanyama", "nakameguro", "ny-bar"],
      ["Subway to Ryogoku (~25–35m)."],
      ["Book sumo early.", "Backup: Daikanyama → Nakameguro → NY Bar."],
      [
        t("11:00", "Ryogoku Kokugikan (if tickets)", "ryogoku", "Afternoon session popular with visitors.", "16:00"),
        t("12:00", "ALT: Shimokitazawa wander", "shimokitazawa", "Only if no sumo.", "16:00"),
        t("17:30", "Optional Daikanyama + Nakameguro", "nakameguro"),
        t("20:00", "Optional New York Bar", "ny-bar", "Smart casual."),
      ]),
  day("d29", "2026-09-24", "Thursday", "Tokyo", "JP", "solaria",
      "Flexible favorites & gifts",
      "Revisit a favorite, finish souvenirs, farewell dinner.",
      "Return to a meal you loved.",
      ["daikanyama", "nakameguro", "ginza"],
      ["Depends on encore choice."],
      ["Pack tonight.", "Confirm Narita timing."],
      [
        t("10:00", "Choose your encore neighborhood", "daikanyama", "Or Ginza shopping finish."),
        t("13:00", "Lunch favorite", None),
        t("15:00", "Souvenir run (Don Quijote / depachika)", "ginza"),
        t("17:00", "Pack at hotel", "solaria"),
        t("19:30", "Farewell dinner", "ginza", "Celebrate the trip."),
      ]),
  day("d30", "2026-09-25", "Friday", "Tokyo", "JP", None,
      "Last breakfast & Narita departure",
      "Optional final Tsukiji, then evening flight home.",
      "One last Tokyo breakfast.",
      ["tsukiji", "narita"],
      ["Allow 2.5–3+ hours door-to-gate.", "Private transfer easiest."],
      ["Eat → pack → airport."],
      [
        t("08:00", "Optional Tsukiji goodbye breakfast", "tsukiji"),
        t("11:00", "Final pack / checkout", "solaria"),
        t("14:00", "Depart for Narita", "narita", "Adjust to your flight — leave earlier if needed."),
        t("17:00", "Airport buffer", "narita", "Security, food, duty-free."),
        t("22:30", "Departure (example evening slot)", "narita", "Replace with your real flight time."),
      ]),
]

TRIP = {
    "title": "Korea + Japan 2026",
    "subtitle": "Haitner trip · smart merge",
    "dates": "August 27 – September 25, 2026",
    "route": ["Seoul", "Tokyo", "Hakone", "Kawaguchiko", "Kyoto", "Hiroshima", "Osaka", "Tokyo"],
    "notes": [
        "Now includes Seoul (Aug 27–Sep 1) plus the merged Japan plan — every day has an hour-by-hour timeline.",
        "Tap any place on the timeline or Places tab to open Google Maps / Yahoo! MAP (Japan) / Kakao·Naver (Korea) / Apple Maps.",
        "Flight times on Sep 1 & Sep 25 are placeholders — update to your real tickets.",
        "Clinic / beauty slots in Seoul are optional windows if you booked them; skip freely.",
    ],
}

for d in DAYS:
    if d["id"] in TRANSFERS:
        d["transfer"] = TRANSFERS[d["id"]]
    for item in d.get("timeline") or []:
        if not item.get("category"):
            item["category"] = infer_category(item.get("title", ""), item.get("placeId"), item.get("note", ""))

def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

js = f"""/* Auto-generated trip data — Seoul + Japan detailed timelines */
window.TRIP = {dumps(TRIP)};
window.PLACES = {dumps(PLACES)};
window.DAYS = {dumps(DAYS)};
"""
OUT.write_text(js, encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
print(f"Days: {len(DAYS)}, Places: {len(PLACES)}")
print("Transfers:", sum(1 for d in DAYS if d.get("transfer")))
print("Sample category:", DAYS[0]["timeline"][0].get("category"))
