#!/usr/bin/env python3
"""Build docs/js/data.js with Seoul + Japan detailed timelines."""
from __future__ import annotations
import json
from pathlib import Path

OUT = Path(__file__).with_name("data.js")

def place(id, name, name_local, city, country, tags, lat, lng, blurb, taxi_address=None):
    p = {
        "id": id, "name": name, "nameJa": name_local, "city": city, "country": country,
        "tags": tags, "lat": lat, "lng": lng, "blurb": blurb,
    }
    if taxi_address:
        p["taxiAddress"] = taxi_address
    return p

PLACES = {}

def add(p):
    PLACES[p["id"]] = p

# --- Seoul ---
for p in [
    place("brick-hotel", "9 Brick Hotel Hongdae", "나인브릭호텔", "Seoul", "KR", ["hotel", "booked"], 37.5563, 126.9236, "Booked — our Seoul base in Hongdae.", "서울특별시 마포구 와우산로 94, 나인브릭호텔"),
    place("icn", "Incheon Airport (ICN)", "인천국제공항", "Seoul", "KR", ["transport"], 37.4602, 126.4407, "Seoul arrival / departure."),
    place("myeongdong", "Myeongdong", "명동", "Seoul", "KR", ["shopping", "food", "neighborhood"], 37.5636, 126.9869, "K-beauty, street food, neon shopping."),
    place("hongdae", "Hongdae", "홍대", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5563, 126.9236, "Student arts district — cafés, bars, street performers."),
    place("gyeongbokgung", "Gyeongbokgung Palace", "경복궁", "Seoul", "KR", ["must-see", "culture"], 37.5796, 126.9770, "Main royal palace — rent hanbok for free entry vibe."),
    place("bukchon", "Bukchon Hanok Village", "북촌한옥마을", "Seoul", "KR", ["must-see", "neighborhood", "culture"], 37.5826, 126.9831, "Traditional hanok hillside lanes."),
    place("ikseon", "Ikseon-dong", "익선동", "Seoul", "KR", ["neighborhood", "food", "culture"], 37.5740, 126.9897, "Hip hanok alleys with cafés and bars."),
    place("insadong", "Insadong", "인사동", "Seoul", "KR", ["shopping", "culture", "food"], 37.5742, 126.9847, "Tea houses, crafts, souvenir shopping."),
    place("gwangjang", "Gwangjang Market", "광장시장", "Seoul", "KR", ["must-see", "food", "market"], 37.5700, 126.9996, "Bindaetteok, mayak gimbap, night market energy (open late)."),
    place("eunpyeong", "Eunpyeong Hanok Village", "은평한옥마을", "Seoul", "KR", ["neighborhood", "culture"], 37.6408, 126.9345, "Quieter traditional village alternative."),
    place("lotte-world", "Lotte World Adventure", "롯데월드", "Seoul", "KR", ["must-see", "park"], 37.5110, 127.0980, "Indoor/outdoor theme park — full day."),
    place("lotte-tower", "Lotte World Tower Seoul Sky", "롯데월드타워", "Seoul", "KR", ["must-see", "view"], 37.5126, 127.1025, "One of the world’s tallest — Seoul Sky observatory."),
    place("seokchon", "Seokchon Lake", "석촌호수", "Seoul", "KR", ["neighborhood", "nature"], 37.5095, 127.1035, "Lake walk beside Lotte Tower."),
    place("jimjilbang", "Jimjilbang (spa complex)", "찜질방", "Seoul", "KR", ["culture", "onsen"], 37.5400, 127.0700, "Korean bathhouse culture — check nearest well-rated spot (e.g. near Jamsil/Gangnam)."),
    place("jogyesa", "Jogyesa Temple", "조계사", "Seoul", "KR", ["temple", "culture"], 37.5735, 126.9825, "Major Buddhist temple near Insadong."),
    place("changdeokgung", "Changdeokgung + Secret Garden", "창덕궁 후원", "Seoul", "KR", ["must-see", "culture"], 37.5794, 126.9910, "UNESCO palace — book Secret Garden timed tour."),
    place("gangnam", "Gangnam", "강남", "Seoul", "KR", ["neighborhood", "shopping"], 37.4979, 127.0276, "Treatments, shopping, K-pop landmarks."),
    place("bongeunsa", "Bongeunsa Temple", "봉은사", "Seoul", "KR", ["temple", "culture"], 37.5152, 127.0574, "Temple beside COEX — calm contrast to Gangnam."),
    place("coex", "COEX & Starfield Library", "코엑스 별마당도서관", "Seoul", "KR", ["must-see", "shopping", "culture"], 37.5117, 127.0595, "Giant mall + iconic Starfield Library."),
    place("dongdaemun", "Dongdaemun Night Market / DDP", "동대문", "Seoul", "KR", ["shopping", "nightlife", "food"], 37.5665, 127.0092, "Night fashion markets + DDP architecture."),
    place("seongsu", "Seongsu-dong", "성수동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5445, 127.0557, "Brooklyn-feel cafés, pop-ups, and design shops."),
    place("n-tower", "N Seoul Tower", "N서울타워", "Seoul", "KR", ["must-see", "view"], 37.5512, 126.9882, "Namsan sunset views + love locks."),
    place("itaewon", "Itaewon", "이태원", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5345, 126.9944, "International bars, LGBTQ+ friendly nightlife."),
]:
    add(p)

# --- Japan (existing + a few extras) ---
for p in [
    place("keio-plaza", "Keio Plaza Hotel Tokyo", "京王プラザホテル", "Tokyo", "JP", ["hotel", "inspiration"], 35.6906, 139.6921, "Dad's stay idea near Shinjuku — not booked for our trip."),
    place("narita", "Narita Airport (NRT)", "成田国際空港", "Tokyo", "JP", ["transport"], 35.7720, 140.3929, "Tokyo arrival/departure."),
    place("shinjuku", "Shinjuku", "新宿", "Tokyo", "JP", ["neighborhood", "food", "nightlife"], 35.6938, 139.7034, "Neon, shopping, Godzilla."),
    place("shibuya-crossing", "Shibuya Crossing", "渋谷スクランブル交差点", "Tokyo", "JP", ["must-see", "icon"], 35.6595, 139.7005, "Scramble + Hachiko."),
    place("meiji-jingu", "Meiji Jingu", "明治神宮", "Tokyo", "JP", ["must-see", "culture", "shrine"], 35.6764, 139.6993, "Forest shrine."),
    place("takeshita", "Takeshita Street", "竹下通り", "Tokyo", "JP", ["food", "shopping"], 35.6702, 139.7050, "Harajuku crepes & youth fashion."),
    place("cat-street", "Cat Street", "キャットストリート", "Tokyo", "JP", ["shopping", "neighborhood"], 35.6658, 139.7038, "Stylish Harajuku side street."),
    place("omotesando", "Omotesando", "表参道", "Tokyo", "JP", ["shopping", "architecture"], 35.6652, 139.7122, "Tree-lined boutiques."),
    place("disneysea", "Tokyo DisneySea", "東京ディズニーシー", "Tokyo", "JP", ["must-see", "park"], 35.6267, 139.8851, "Unique Disney park."),
    place("asakusa", "Asakusa / Senso-ji", "浅草寺", "Tokyo", "JP", ["must-see", "culture", "food"], 35.7148, 139.7967, "Classic temple Tokyo."),
    place("kappabashi", "Kappabashi Street", "合羽橋道具街", "Tokyo", "JP", ["food", "shopping"], 35.7155, 139.7870, "Kitchen-town souvenirs."),
    place("skytree", "Tokyo Skytree", "東京スカイツリー", "Tokyo", "JP", ["must-see", "view"], 35.7101, 139.8107, "634m tower."),
    place("tsukiji", "Tsukiji Outer Market", "築地場外市場", "Tokyo", "JP", ["must-see", "food"], 35.6654, 139.7707, "Breakfast graze."),
    place("imperial-east", "Imperial Palace East Gardens", "皇居東御苑", "Tokyo", "JP", ["culture", "park"], 35.6865, 139.7575, "Quiet castle gardens."),
    place("ginza", "Ginza", "銀座", "Tokyo", "JP", ["shopping", "food"], 35.6712, 139.7649, "Dept stores & depachika."),
    place("teamlab-planets", "teamLab Planets Tokyo", "チームラボプラネッツ", "Tokyo", "JP", ["must-see", "culture"], 35.6490, 139.7868, "Immersive digital art."),
    place("odaiba", "Odaiba / DiverCity Gundam", "お台場", "Tokyo", "JP", ["park", "shopping"], 35.6251, 139.7755, "Gundam + waterfront."),
    place("ameyoko", "Ameyoko Market", "アメ横", "Tokyo", "JP", ["food", "market"], 35.7095, 139.7745, "Street-food market."),
    place("akihabara", "Akihabara", "秋葉原", "Tokyo", "JP", ["park", "shopping"], 35.7023, 139.7745, "Arcades & anime."),
    place("golden-gai", "Shinjuku Golden Gai", "新宿ゴールデン街", "Tokyo", "JP", ["must-see", "nightlife"], 35.6938, 139.7047, "Tiny bar alleys."),
    place("daikanyama", "Daikanyama T-Site", "代官山T-SITE", "Tokyo", "JP", ["culture", "food"], 35.6492, 139.7032, "Bookstore complex."),
    place("nakameguro", "Nakameguro / Meguro River", "中目黒", "Tokyo", "JP", ["neighborhood", "food"], 35.6442, 139.6988, "Riverside boutiques."),
    place("ny-bar", "New York Bar (Park Hyatt)", "ニューヨークバー", "Tokyo", "JP", ["nightlife", "view"], 35.6855, 139.6905, "Lost in Translation bar."),
    place("kajikaso", "Hotel Kajikaso", "ホテルかじか荘", "Hakone", "JP", ["hotel", "onsen", "inspiration"], 35.2335, 139.0885, "Dad's Hakone ryokan idea — not booked for our trip."),
    place("owakudani", "Owakudani", "大涌谷", "Hakone", "JP", ["must-see", "nature", "food"], 35.2424, 139.0204, "Volcanic valley + black eggs."),
    place("hakone-shrine", "Hakone Shrine", "箱根神社", "Hakone", "JP", ["must-see", "shrine"], 35.2051, 139.0256, "Lakeside torii — best at sunrise."),
    place("lake-ashi", "Lake Ashi Pirate Ship", "箱根海賊船", "Hakone", "JP", ["nature", "park"], 35.2065, 139.0250, "Sightseeing cruise."),
    place("open-air", "Hakone Open-Air Museum", "箱根彫刻の森美術館", "Hakone", "JP", ["culture"], 35.2445, 139.0515, "Outdoor sculpture museum."),
    place("fuji-lawson", "Lawson Kawaguchiko Station", "ローソン河口湖駅前", "Kawaguchiko", "JP", ["icon", "must-see"], 35.4983, 138.7689, "Famous Fuji convenience-store shot."),
    place("oishi-park", "Oishi Park", "大石公園", "Kawaguchiko", "JP", ["must-see", "view"], 35.5245, 138.7470, "Sunset Fuji lakeside."),
    place("chureito", "Chureito Pagoda", "忠霊塔", "Kawaguchiko", "JP", ["must-see", "icon"], 35.5012, 138.8013, "Sunrise pagoda + Fuji."),
    place("fuji-q", "Fuji-Q Highland", "富士急ハイランド", "Kawaguchiko", "JP", ["must-see", "park"], 35.4871, 138.7806, "World-class coasters."),
    place("musse-kyoto", "Hotel Musse Kyoto", "ホテルミュッセ京都四条河原町名鉄", "Kyoto", "JP", ["hotel", "inspiration"], 35.0037, 135.7685, "Dad's Kyoto stay idea near Kawaramachi — not booked for our trip."),
    place("kenninji", "Kennin-ji", "建仁寺", "Kyoto", "JP", ["temple", "culture"], 35.0008, 135.7735, "Oldest Zen temple in Kyoto."),
    place("gion", "Gion", "祇園", "Kyoto", "JP", ["must-see", "neighborhood"], 35.0037, 135.7788, "Geisha district."),
    place("pontocho", "Pontocho Alley", "先斗町", "Kyoto", "JP", ["food", "nightlife"], 35.0045, 135.7712, "Dinner alley by the river."),
    place("fushimi-inari", "Fushimi Inari Taisha", "伏見稲荷大社", "Kyoto", "JP", ["must-see", "shrine"], 34.9671, 135.7727, "Thousands of torii."),
    place("kiyomizu", "Kiyomizu-dera", "清水寺", "Kyoto", "JP", ["must-see", "temple"], 34.9949, 135.7850, "Wooden stage temple."),
    place("sannenzaka", "Sannenzaka & Ninenzaka", "三年坂・二年坂", "Kyoto", "JP", ["must-see", "food"], 34.9958, 135.7815, "Stone postcard streets."),
    place("kinkakuji", "Kinkaku-ji", "金閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0394, 135.7292, "Golden Pavilion."),
    place("nishiki", "Nishiki Market", "錦市場", "Kyoto", "JP", ["must-see", "food"], 35.0050, 135.7649, "Kyoto’s kitchen."),
    place("otagi", "Otagi Nenbutsu-ji", "愛宕念仏寺", "Kyoto", "JP", ["must-see", "temple"], 35.0317, 135.6628, "1,200 rakan statues."),
    place("adashino", "Adashino Nenbutsu-ji", "化野念仏寺", "Kyoto", "JP", ["temple", "culture"], 35.0267, 135.6645, "Bamboo & stone Buddhas."),
    place("saga-toriimoto", "Saga Toriimoto", "嵯峨鳥居本", "Kyoto", "JP", ["neighborhood"], 35.0255, 135.6680, "Preserved approach street."),
    place("bamboo", "Arashiyama Bamboo Grove", "竹林の小径", "Kyoto", "JP", ["must-see", "nature"], 35.0173, 135.6721, "Iconic bamboo path."),
    place("kimono-forest", "Kimono Forest", "キモノフォレスト", "Kyoto", "JP", ["icon"], 35.0153, 135.6775, "Kimono cylinder pillars."),
    place("togetsukyo", "Togetsukyo Bridge", "渡月橋", "Kyoto", "JP", ["icon", "nature"], 35.0135, 135.6778, "Arashiyama bridge."),
    place("monkey-park", "Iwatayama Monkey Park", "嵐山モンキーパーク", "Kyoto", "JP", ["park", "nature"], 35.0117, 135.6761, "Monkeys + city view."),
    place("tenryuji", "Tenryu-ji", "天龍寺", "Kyoto", "JP", ["temple", "culture"], 35.0156, 135.6736, "UNESCO Zen garden."),
    place("kurama-dera", "Kurama-dera", "鞍馬寺", "Kyoto", "JP", ["must-see", "temple", "nature"], 35.1181, 135.7709, "Start of forest trek."),
    place("kifune", "Kifune Shrine", "貴船神社", "Kyoto", "JP", ["must-see", "shrine"], 35.1216, 135.7631, "Lantern stone stairs."),
    place("kawadoko", "Kibune Kawadoko Dining", "貴船川床", "Kyoto", "JP", ["must-see", "food"], 35.1205, 135.7638, "Lunch over the stream."),
    place("kurama-onsen", "Kurama Onsen", "鞍馬温泉", "Kyoto", "JP", ["onsen"], 35.1128, 135.7725, "Mountain onsen."),
    place("ginkakuji", "Ginkaku-ji", "銀閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0264, 135.7986, "Silver Pavilion."),
    place("philosophers-path", "Philosopher’s Path", "哲学の道", "Kyoto", "JP", ["neighborhood", "nature"], 35.0205, 135.7955, "Canal stroll."),
    place("nanzenji", "Nanzen-ji", "南禅寺", "Kyoto", "JP", ["temple", "culture"], 35.0116, 135.7945, "Zen temple + aqueduct."),
    place("uji", "Uji / Byodo-in", "宇治・平等院", "Kyoto", "JP", ["food", "temple"], 34.8894, 135.8077, "Matcha capital + Phoenix Hall."),
    place("daiwa-hiroshima", "Daiwa Roynet Hiroshima", "ダイワロイネットホテル広島", "Hiroshima", "JP", ["hotel", "inspiration"], 34.3927, 132.4553, "Dad's Hiroshima hotel idea — we day-trip from Osaka."),
    place("shukkeien", "Shukkeien Garden", "縮景園", "Hiroshima", "JP", ["culture", "park"], 34.3995, 132.4674, "Miniature landscape garden."),
    place("peace-park", "Peace Memorial Park", "平和記念公園", "Hiroshima", "JP", ["must-see", "culture"], 34.3955, 132.4536, "Dome + museum."),
    place("okonomiyaki", "Okonomi-mura", "お好み村", "Hiroshima", "JP", ["food", "must-see"], 34.3938, 132.4622, "Hiroshima okonomiyaki hall."),
    place("miyajima", "Itsukushima Shrine", "厳島神社", "Hiroshima", "JP", ["must-see", "shrine"], 34.2960, 132.3198, "Floating torii."),
    place("misen", "Mt. Misen Ropeway", "弥山ロープウェイ", "Hiroshima", "JP", ["nature", "view"], 34.2905, 132.3185, "Island summit."),
    place("cross-osaka", "Cross Hotel Osaka", "クロスホテル大阪", "Osaka", "JP", ["hotel", "inspiration"], 34.6693, 135.5013, "Dad's Osaka stay idea near Namba — not booked for our trip."),
    place("kuromon", "Kuromon Market", "黒門市場", "Osaka", "JP", ["must-see", "food"], 34.6664, 135.5064, "Osaka’s kitchen."),
    place("osaka-castle", "Osaka Castle", "大阪城", "Osaka", "JP", ["culture", "must-see"], 34.6873, 135.5262, "Castle + park."),
    place("dotonbori", "Dotonbori", "道頓堀", "Osaka", "JP", ["must-see", "food", "nightlife"], 34.6687, 135.5013, "Neon food crawl."),
    place("usj", "Universal Studios Japan", "ユニバーサル・スタジオ・ジャパン", "Osaka", "JP", ["must-see", "park"], 34.6654, 135.4323, "Nintendo World + coasters."),
    place("nara-park", "Nara Park / Todai-ji", "奈良公園・東大寺", "Osaka", "JP", ["must-see", "culture"], 34.6889, 135.8398, "Deer + Great Buddha."),
    place("shinsekai", "Shinsekai / Tsutenkaku", "新世界・通天閣", "Osaka", "JP", ["food", "neighborhood"], 34.6525, 135.5063, "Retro Osaka."),
    place("tenjinbashi", "Tenjinbashi-suji", "天神橋筋商店街", "Osaka", "JP", ["shopping", "food"], 34.7045, 135.5110, "Longest arcade."),
    place("umeda-sky", "Umeda Sky Building", "梅田スカイビル", "Osaka", "JP", ["must-see", "view"], 34.7055, 135.4897, "Floating Garden view."),
    place("ramen-museum", "Instant Ramen Museum", "カップヌードルミュージアム池田", "Osaka", "JP", ["food", "park"], 34.8195, 135.4258, "Make your Cup Noodle."),
    place("solaria", "Solaria Nishitetsu Ginza", "ソラリア西鉄ホテル銀座", "Tokyo", "JP", ["hotel", "inspiration"], 35.6695, 139.7668, "Dad's Tokyo return stay idea — not booked for our trip."),
    place("ryogoku", "Ryogoku Kokugikan", "両国国技館", "Tokyo", "JP", ["must-see", "culture"], 35.6971, 139.7935, "Sumo stadium."),
    place("shimokitazawa", "Shimokitazawa", "下北沢", "Tokyo", "JP", ["neighborhood", "shopping"], 35.6616, 139.6683, "Vintage & indie cafés."),
    place("omoide-yokocho", "Omoide Yokocho (Memory Lane)", "思い出横丁", "Tokyo", "JP", ["food", "nightlife", "must-see"], 35.6935, 139.6995, "Smoky yakitori alleys by Shinjuku station."),
    place("shibuya-sky", "Shibuya Sky", "渋谷スカイ", "Tokyo", "JP", ["must-see", "view"], 35.6585, 139.7024, "Sunset observation deck — book timed tickets."),
    place("ueno-park", "Ueno Park", "上野公園", "Tokyo", "JP", ["park", "culture"], 35.7147, 139.7733, "Museums, temples, and green space."),
    place("ghibli", "Ghibli Museum", "三鷹の森ジブリ美術館", "Tokyo", "JP", ["must-see", "culture", "park"], 35.6962, 139.5703, "Lottery/reservation required — Mitaka."),
    place("inokashira", "Inokashira Park", "井の頭恩賜公園", "Tokyo", "JP", ["park", "nature"], 35.7000, 139.5750, "Lake park near Ghibli / Kichijoji."),
    place("hozenji", "Hozenji Yokocho", "法善寺横丁", "Osaka", "JP", ["neighborhood", "culture", "food"], 34.6678, 135.5025, "Mossy lantern alley near Dotonbori."),
    place("shinsaibashi", "Shinsaibashi", "心斎橋", "Osaka", "JP", ["shopping", "neighborhood"], 34.6750, 135.5013, "Major shopping arcade next to Namba."),
    place("amerikamura", "Amerikamura", "アメリカ村", "Osaka", "JP", ["neighborhood", "shopping", "nightlife"], 34.6728, 135.4985, "Youth fashion & casual dinner area."),
    place("roppongi", "Roppongi", "六本木", "Tokyo", "JP", ["neighborhood", "nightlife"], 35.6628, 139.7314, "Nightlife and city views."),
    place("azabudai", "Azabudai Hills", "麻布台ヒルズ", "Tokyo", "JP", ["shopping", "culture", "architecture"], 35.6605, 139.7400, "Modern complex — teamLab Borderless home."),
    place("tokyo-tower", "Tokyo Tower", "東京タワー", "Tokyo", "JP", ["must-see", "view", "icon"], 35.6586, 139.7454, "Classic Tokyo night landmark."),
    place("kabukicho", "Kabukicho", "歌舞伎町", "Tokyo", "JP", ["nightlife", "neighborhood"], 35.6950, 139.7026, "Neon nightlife district in Shinjuku."),
    place("shinjuku-gyoen", "Shinjuku Gyoen", "新宿御苑", "Tokyo", "JP", ["park", "nature", "must-see"], 35.6852, 139.7101, "Spacious national garden — calm morning walk."),
    place("nakano-broadway", "Nakano Broadway", "中野ブロードウェイ", "Tokyo", "JP", ["shopping", "culture"], 35.7093, 139.6652, "Otaku shopping maze — figures, vintage, Mandarake."),
    place("kamakura", "Kamakura / Kotoku-in", "鎌倉・高徳院", "Tokyo", "JP", ["must-see", "culture", "temple"], 35.3167, 139.5357, "Great Buddha + Enoden coastal line day trip."),
    place("kasuga", "Kasuga Taisha", "春日大社", "Osaka", "JP", ["shrine", "culture"], 34.6814, 135.8482, "Lantern shrine in Nara."),
]:
    add(p)

def day(id, date, weekday, city, country, hotel_id, title, summary, food, place_ids, transport, tips, timeline, transfer=None):
    d = {
        "id": id, "date": date, "weekday": weekday, "city": city, "country": country,
        "hotelId": hotel_id, "title": title, "summary": summary, "food": food,
        "placeIds": place_ids, "transport": transport, "tips": tips, "timeline": timeline,
    }
    if transfer:
        d["transfer"] = transfer
    return d

def infer_category(title, place_id, note=""):
    text = f"{title} {note}".lower()
    tags = []
    if place_id and place_id in PLACES:
        tags = PLACES[place_id].get("tags") or []
    if place_id and place_id in PLACES and "hotel" in tags:
        return "hotel"
    if any(k in text for k in ("flight", "train", "shinkansen", "romancecar", "subway", "bus", "ferry", "transfer", "depart", "airport", "ropeway", "monorail")) or "transport" in tags:
        return "transit"
    if any(k in text for k in ("breakfast", "lunch", "dinner", "food", "market", "crepe", "ramen", "sushi", "café", "cafe", "okonomi", "graze", "snack", "brunch")) or "food" in tags or "market" in tags:
        return "dining"
    if any(k in text for k in ("shop", "souvenir", "arcade street", "ginza", "depachika", "don quijote")) or "shopping" in tags:
        return "shopping"
    if any(k in text for k in ("temple", "shrine", "palace", "garden", "museum", "zen", "sumo", "tea", "hanok", "secret garden")) or "culture" in tags or "temple" in tags or "shrine" in tags:
        return "culture"
    if "park" in tags or any(k in text for k in ("disney", "universal", "fuji-q", "lotte world", "teamlab", "skytree", "tower", "park", "monkey", "cruise", "rope drop")):
        return "attraction"
    if "nightlife" in tags:
        return "dining"
    return "attraction"

def t(time, title, place_id=None, note="", end=None, category=None):
    item = {"time": time, "title": title, "note": note}
    if place_id:
        item["placeId"] = place_id
    if end:
        item["end"] = end
    if category:
        item["category"] = category
    return item


TRANSFERS = {
    "d06": {
        "mode": "flight",
        "label": "Seoul → Tokyo",
        "detail": "ICN/GMP → NRT/HND (confirm your flight)",
        "duration": "~2.5h flight + transfers",
        "fromCity": "Seoul",
        "toCity": "Tokyo",
    },
    "d11": {
        "mode": "train",
        "label": "Tokyo → Hakone",
        "detail": "Odakyu Romancecar Shinjuku → Hakone-Yumoto (~¥2,470)",
        "duration": "~80 minutes",
        "fromCity": "Tokyo",
        "toCity": "Hakone",
    },
    "d12": {
        "mode": "bus",
        "label": "Hakone → Kawaguchiko",
        "detail": "Bus via Gotemba + Fujikyu bus (~¥1,600–2,100)",
        "duration": "~1.5–2h",
        "fromCity": "Hakone",
        "toCity": "Kawaguchiko",
    },
    "d14": {
        "mode": "train",
        "label": "Kawaguchiko → Kyoto (Mishima route)",
        "detail": "Express bus to Mishima (~90m) + Tokaido Shinkansen (~110m). Prefer this over overnight bus.",
        "duration": "~3.5–4h · ~¥12,500–13,500",
        "fromCity": "Kawaguchiko",
        "toCity": "Kyoto",
    },
    "d19": {
        "mode": "train",
        "label": "Kyoto → Osaka",
        "detail": "JR/private line into central Osaka (~30m)",
        "duration": "~30–45 minutes",
        "fromCity": "Kyoto",
        "toCity": "Osaka",
    },
    "d22": {
        "mode": "train",
        "label": "Osaka ↔ Hiroshima day trip",
        "detail": "Early Shinkansen to Hiroshima (~80m), return evening",
        "duration": "~80m each way",
        "fromCity": "Osaka",
        "toCity": "Hiroshima",
    },
    "d24": {
        "mode": "train",
        "label": "Osaka → Tokyo",
        "detail": "Nozomi Shinkansen (~2.5h)",
        "duration": "~2.5 hours",
        "fromCity": "Osaka",
        "toCity": "Tokyo",
    },
    "d28": {
        "mode": "flight",
        "label": "Tokyo → Home",
        "detail": "N'EX / Monorail to NRT or HND",
        "duration": "Allow 2.5–3h to airport",
        "fromCity": "Tokyo",
        "toCity": "Home",
    },
}

DAYS = [
  day("d01", "2026-08-27", "Thursday", "Seoul", "KR", "brick-hotel",
      "Arrival & night walk",
      "Land in Seoul, settle into the Hongdae hotel, then an easy Myeongdong night-food walk. Hongdae only if you still have energy.",
      "Myeongdong street food night market.",
      ["icn", "brick-hotel", "myeongdong", "hongdae"],
      ["ICN → hotel (~1h).", "Subway/taxi to Myeongdong."],
      ["Jet-lag day — keep it light.", "Get T-money / Climate Card."],
      [
        t("14:00", "Land & transfer to hotel", "icn", "Rest and refresh after arrival."),
        t("17:00", "Check in", "brick-hotel"),
        t("18:30", "Myeongdong night walk", "myeongdong", "Street food + shopping streets.", "21:30"),
        t("22:00", "Optional Hongdae nightcap", "hongdae", "Bars & street performances if energy permits."),
      ]),
  day("d02", "2026-08-28", "Friday", "Seoul", "KR", "brick-hotel",
      "Royal heritage & historic alleys",
      "Palace morning (classic Gyeongbokgung, or via quieter Eunpyeong), then Bukchon, Ikseon and Insadong, and a Gwangjang Market dinner.",
      "Gwangjang Market — bindaetteok, mayak kimbap, knife-cut noodles.",
      ["hongdae", "eunpyeong", "gyeongbokgung", "bukchon", "ikseon", "insadong", "gwangjang"],
      ["Hongdae → Gyeongbokgung (~25m).", "Walk Bukchon → Ikseon → Insadong → Gwangjang."],
      ["Rent hanbok for free palace entry vibe.", "Option B: Eunpyeong first if you want quieter hanoks."],
      [
        t("09:00", "Hongdae café breakfast", "hongdae"),
        t("09:45", "Optional: Eunpyeong Hanok Village", "eunpyeong", "Option B — less crowded, Bukhansan views.", "11:00"),
        t("10:30", "Gyeongbokgung Palace", "gyeongbokgung", "Hanbok rental outside. Option A starts here.", "12:30"),
        t("13:00", "Bukchon Hanok Village", "bukchon", "Respect residents while photographing.", "14:15"),
        t("14:30", "Ikseon-dong & Insadong", "ikseon", "Aesthetic cafés, boutiques, crafts.", "17:30"),
        t("18:30", "Gwangjang Market feast", "gwangjang", "Traditional street-food dinner.", "21:30"),
      ]),
  day("d03", "2026-08-29", "Saturday", "Seoul", "KR", "brick-hotel",
      "Thrills, views & nightlife",
      "Full day of thrills at Lotte World, lake and Seoul Sky views, a jjimjilbang reset, then Hongdae nightlife.",
      "Lotte mall lunch; late Hongdae bites.",
      ["lotte-world", "seokchon", "lotte-tower", "jimjilbang", "hongdae"],
      ["Subway to Jamsil (~40–50m from Hongdae)."],
      ["Book Lotte World ahead.", "Tower sunset/evening views are excellent."],
      [
        t("08:30", "Convenience-store breakfast", "brick-hotel"),
        t("10:00", "Lotte World Theme Park", "lotte-world", "Open ~10:00–22:00 — full thrills day.", "17:00"),
        t("17:15", "Seokchon Lake stroll", "seokchon"),
        t("18:00", "Lotte World Tower — Seoul Sky", "lotte-tower", "360° city views.", "19:30"),
        t("20:00", "Jjimjilbang unwind", "jimjilbang", "Korean spa/sauna after park day.", "22:00"),
        t("22:30", "Hongdae night out", "hongdae", "Bars, indie music, clubs."),
      ]),
  day("d04", "2026-08-30", "Sunday", "Seoul", "KR", "brick-hotel",
      "Temples, Myeongdong glow & night shopping",
      "Jogyesa and pre-booked Changdeokgung Secret Garden, then a Myeongdong skin treatment (PPEUM/Lienjang) instead of Gangnam, and Dongdaemun night malls.",
      "Temple-area cafés; Myeongdong snacks; Dongdaemun bites.",
      ["jogyesa", "changdeokgung", "myeongdong", "dongdaemun"],
      ["Book Secret Garden timed tickets online in advance.", "Stay in Myeongdong for the glow treatment — skips ~90 minutes of Gangnam transit."],
      ["Secret Garden sells out — reserve early.", "Book English-friendly Myeongdong clinic (PPEUM / Lienjang / ToxnFill)."],
      [
        t("09:00", "Hongdae café breakfast", "hongdae"),
        t("10:15", "Jogyesa Temple", "jogyesa", "Quick calm stop.", "11:00"),
        t("11:15", "Changdeokgung & Secret Garden", "changdeokgung", "Must pre-book Secret Garden online.", "14:00"),
        t("15:00", "Myeongdong skin treatment", "myeongdong", "Glow / Aqua Peel at PPEUM, Lienjang, or ToxnFill — tourist-friendly English.", "17:00"),
        t("17:15", "Myeongdong browse & snacks", "myeongdong", "K-beauty shopping while you’re already there.", "19:00"),
        t("20:00", "Dongdaemun Design Plaza & night malls", "dongdaemun", "APM, DDP Fashion Mall, Hyundai City Outlets.", "23:30"),
      ]),
  day("d05", "2026-08-31", "Monday", "Seoul", "KR", "brick-hotel",
      "Head Spa, Seongsu & Itaewon night",
      "Morning Head Spa near Hongdae (5-minute walk from 9 Brick), then Seongsu boutiques, N Seoul Tower sunset, and Itaewon nightlife.",
      "Light post-spa lunch in Seongsu; Itaewon international dinner.",
      ["hongdae", "seongsu", "n-tower", "itaewon"],
      ["Head Spa first (Parkjun / Eco Jardin), then subway to Seongsu (~35–45m).", "Seongsu → Namsan (~40m)."],
      ["Book Head Spa 10:00–11:30 near the hotel.", "Book N Tower for sunset.", "Itaewon is LGBTQ+ friendly."],
      [
        t("10:00", "Head Spa in Hongdae", "hongdae", "Parkjun Beauty Lab / Eco Jardin / WT Methode — refreshing reset before a walking day.", "11:30"),
        t("12:30", "Seongsu-dong explore", "seongsu", "Trendy boutiques, cafés, Seongsu Yeonbang.", "16:00"),
        t("16:30", "Head to Namsan", "n-tower"),
        t("17:30", "N Seoul Tower sunset", "n-tower", "Views + love locks.", "19:30"),
        t("20:00", "Itaewon evening", "itaewon", "Dinner, bars, Homo Hill nightlife.", "24:00"),
      ]),
  day("d06", "2026-09-01", "Tuesday", "Tokyo", "JP", None,
      "Seoul → Tokyo & Shinjuku lights",
      "Fly Seoul to Tokyo, set up Suica and eSIM, then a Shinjuku evening in Omoide Yokocho or Golden Gai. Hotel still to book.",
      "Yakitori in Omoide Yokocho or Golden Gai drinks.",
      ["icn", "narita", "shinjuku", "omoide-yokocho", "golden-gai"],
      ["Hotel → ICN/GMP with buffer.", "Flight to Tokyo.", "Airport → Tokyo hotel (still to book — Shinjuku area is convenient)."],
      ["Confirm flight times.", "Set up Suica/Pasmo on arrival."],
      [
        t("08:00", "Checkout & airport transfer", "icn", "ICN or GMP — match your ticket."),
        t("13:00", "Flight to Tokyo", "icn", "Adjust to real schedule."),
        t("17:30", "Land, Suica/eSIM, hotel check-in", None),
        t("19:30", "Shinjuku explore", "shinjuku"),
        t("20:00", "Omoide Yokocho or Golden Gai", "omoide-yokocho", "Memory Lane yakitori or tiny alley bars.", "23:00"),
      ]),
  day("d07", "2026-09-02", "Wednesday", "Tokyo", "JP", None,
      "West Tokyo: culture, pop & Shibuya Sky",
      "West Tokyo: Meiji Jingu, Harajuku and Omotesando, Shibuya Crossing, and a pre-booked Shibuya Sky sunset.",
      "Harajuku snacks; Shibuya dinner & drinks.",
      ["meiji-jingu", "takeshita", "omotesando", "shibuya-crossing", "shibuya-sky"],
      ["Walk/Yamanote between Harajuku and Shibuya."],
      ["Book Shibuya Sky sunset slot ~4 weeks ahead.", "Passport for tax-free shopping."],
      [
        t("09:00", "Meiji Jingu", "meiji-jingu", "Forest shrine morning calm.", "10:30"),
        t("10:45", "Takeshita Street & Omotesando", "takeshita", "Pop fashion → tree-lined boutiques.", "13:00"),
        t("13:30", "Shibuya Crossing & Center-gai", "shibuya-crossing", "Scramble, megastores, people-watching.", "16:30"),
        t("17:00", "Shibuya Sky sunset", "shibuya-sky", "Timed ticket — arrive early.", "19:00"),
        t("19:30", "Dinner & drinks in Shibuya", "shibuya-crossing"),
      ]),
  day("d08", "2026-09-03", "Thursday", "Tokyo", "JP", None,
      "Historic Tokyo & Electric Town",
      "Early Asakusa at Senso-ji, then Skytree or Ueno, and an Akihabara afternoon ending with izakaya.",
      "Nakamise snacks; izakaya dinner.",
      ["asakusa", "skytree", "ueno-park", "akihabara"],
      ["Subway to Asakusa.", "Tobu Skytree Line or walk/transit to Ueno/Akihabara."],
      ["Senso-ji is calmer early.", "Pick Skytree OR Ueno based on energy."],
      [
        t("08:00", "Senso-ji & Nakamise", "asakusa", "Early temple + shopping street.", "11:00"),
        t("11:30", "Tokyo Skytree OR Ueno Park", "skytree", "Choose one afternoon focus.", "14:30"),
        t("15:00", "Akihabara Electric Town", "akihabara", "Gaming, anime, electronics.", "18:30"),
        t("19:00", "Izakaya dinner — Akihabara or Kanda", "akihabara"),
      ]),
  day("d09", "2026-09-04", "Friday", "Tokyo", "JP", None,
      "Digital art & bay views",
      "Tsukiji seafood breakfast, timed teamLab, Odaiba Gundam and bay views, then a Ginza evening.",
      "Tsukiji sushi breakfast; Ginza dinner.",
      ["tsukiji", "teamlab-planets", "azabudai", "odaiba", "ginza"],
      ["Tsukiji early.", "teamLab timed tickets required.", "Odaiba via Yurikamome/Rinkai."],
      ["Pre-book teamLab (Planets Toyosu or Borderless Azabudai Hills)."],
      [
        t("08:00", "Tsukiji Outer Market breakfast", "tsukiji", "Fresh seafood / sushi graze.", "10:30"),
        t("11:30", "teamLab Planets or Borderless", "teamlab-planets", "Borderless is at Azabudai Hills if you choose that.", "14:00"),
        t("14:30", "Odaiba waterfront & Gundam", "odaiba", "Bay views + DiverCity.", "17:30"),
        t("18:30", "Ginza upscale walk & dinner", "ginza"),
      ]),
  day("d10", "2026-09-05", "Saturday", "Tokyo", "JP", None,
      "Magic & coastal culture",
      "Choose one: a full DisneySea day, or Ghibli Museum with Inokashira Park and Shimokitazawa thrifting.",
      "Park food (A) or Kichijoji/Shimokitazawa cafés (B).",
      ["disneysea", "ghibli", "inokashira", "shimokitazawa"],
      ["DisneySea: JR to Maihama.", "Ghibli: Mitaka + walk; then Inokashira & Shimokita."],
      ["DisneySea tickets ~2 months ahead.", "Ghibli is lottery/reservation only."],
      [
        t("08:30", "Option A: Depart for DisneySea", "disneysea", "Full park day — rope drop.", "21:00"),
        t("09:30", "Option B: Ghibli Museum", "ghibli", "Only with reserved tickets.", "12:00"),
        t("12:30", "Option B: Inokashira Park", "inokashira"),
        t("14:30", "Option B: Shimokitazawa shopping", "shimokitazawa", "Vintage & thrift.", "18:30"),
      ]),
  day("d11", "2026-09-06", "Sunday", "Hakone", "JP", None,
      "Romancecar & volcanic valleys",
      "Morning Takkyubin of big bags Tokyo→Kyoto, Romancecar (try Observation Car) into Hakone, Owakudani, then ryokan onsen + kaiseki. Ryokan still to book.",
      "Black eggs; kaiseki dinner at ryokan.",
      ["owakudani"],
      ["Odakyu Romancecar Shinjuku → Hakone-Yumoto (~80m, ~¥2,470).", "Ropeway to Owakudani."],
      ["Send large suitcases Tokyo→Kyoto via hotel Takkyubin; travel Hakone/Fuji with backpacks only.", "Book Romancecar ~1 month ahead — request front Observation Car seats.", "Enjoy onsen etiquette."],
      [
        t("08:00", "Takkyubin drop at Tokyo hotel", None, "Forward big bags straight to the Kyoto hotel — 2-night backpack mode starts now."),
        t("09:00", "Romancecar from Shinjuku", None, "~80 minutes to Hakone-Yumoto. Aim for Observation Car."),
        t("11:00", "Arrive Hakone-Yumoto", None),
        t("12:30", "Owakudani volcanic valley", "owakudani", "Black eggs + Fuji views if clear.", "16:00"),
        t("17:00", "Ryokan check-in & onsen", None),
        t("19:00", "Kaiseki dinner", None, "Early night — dawn shrine tomorrow."),
      ]),
  day("d12", "2026-09-07", "Monday", "Kawaguchiko", "JP", None,
      "Torii dawn, Fuji shores & Chureito sunset",
      "Dawn at Hakone Shrine, Lake Ashi cruise, bus to Kawaguchiko, Fuji Lawson, then Chureito Pagoda at sunset (kept separate from Fuji-Q). Hotel still to book.",
      "Lakeside dinner near Kawaguchiko.",
      ["hakone-shrine", "lake-ashi", "fuji-lawson", "chureito", "oishi-park"],
      ["Hakone → Gotemba → Fujikyu to Kawaguchiko (~1.5–2h, ¥1,600–2,100).", "Late taxi/bus to Chureito for sunset."],
      ["Chureito at sunset today so tomorrow’s Fuji-Q day starts fresh.", "Book Kawaguchiko lodging before this night."],
      [
        t("05:30", "Hakone Shrine floating torii", "hakone-shrine", "Before crowd surges.", "07:15"),
        t("07:45", "Lake Ashi pirate ship", "lake-ashi", "Then return toward Yumoto.", "09:15"),
        t("10:00", "Bus transfer to Kawaguchiko", None, "Gotemba change → Fujikyu bus.", "12:30"),
        t("13:00", "Lawson Fuji View photo stop", "fuji-lawson"),
        t("14:00", "Hotel check-in & rest", None),
        t("15:30", "Optional Oishi Park stroll", "oishi-park", "Lake shore if energy remains.", "16:30"),
        t("17:15", "Chureito Pagoda sunset", "chureito", "Iconic Fuji + pagoda shot — no 05:30 wake-up tomorrow.", "18:45"),
      ]),
  day("d13", "2026-09-08", "Tuesday", "Kawaguchiko", "JP", None,
      "Fuji-Q thrills (fresh start)",
      "Full Fuji-Q Highland day with a normal wake-up (Chureito already done at sunset), hoto noodles, and an early night before Kyoto.",
      "Park food; local hoto noodle dinner.",
      ["fuji-q"],
      ["Fuji-Q for opening — no pre-dawn Chureito detour."],
      ["Prefer Mishima Shinkansen tomorrow — rest well tonight.", "Do-Dodonpa / Takabisha if you dare."],
      [
        t("08:30", "Depart for Fuji-Q Highland", "fuji-q", "Rested legs after yesterday’s sunset pagoda."),
        t("09:00", "Fuji-Q Highland", "fuji-q", "Full theme-park day.", "18:30"),
        t("19:30", "Hoto noodle dinner & early sleep", None, "Skip overnight bus — recover for Kyoto."),
      ]),
  day("d14", "2026-09-09", "Wednesday", "Kyoto", "JP", None,
      "Transfer to Kansai, Nishiki & Gion",
      "Comfortable Mishima Shinkansen to Kyoto (~3.5–4h), hotel drop, Nishiki Market snacks (moved off the heavy Higashiyama day), then Gion and Pontocho. Hotel still to book.",
      "Nishiki snacks; Pontocho riverside dinner.",
      ["nishiki", "kenninji", "gion", "pontocho"],
      ["Bus Kawaguchiko → Mishima (~90m) + Shinkansen to Kyoto (~110m).", "Total ~¥12,500–13,500."],
      ["Far more comfortable than overnight bus after Fuji-Q.", "Nishiki here keeps tomorrow’s Fushimi/Kiyomizu day under ~25k steps.", "Respectful photos in Gion.", "Collect Takkyubin bags at hotel."],
      [
        t("08:30", "Bus to Mishima Station", None, "Express bus ~90 minutes."),
        t("10:30", "Shinkansen Mishima → Kyoto", None, "~110 minutes on Tokaido line."),
        t("13:00", "Hotel drop & collect forwarded bags", None),
        t("14:30", "Nishiki Market graze", "nishiki", "Moved here from the Higashiyama day to save your legs.", "16:00"),
        t("16:30", "Kennin-ji Temple", "kenninji", "Short Zen stop near Gion.", "17:30"),
        t("17:45", "Gion dusk stroll", "gion", "Geisha district lanes.", "19:00"),
        t("19:15", "Pontocho riverside dinner", "pontocho", "Kamogawa atmosphere.", "21:30"),
      ]),
  day("d15", "2026-09-10", "Thursday", "Kyoto", "JP", None,
      "Torii gates & ancient slopes",
      "Sunrise climb at Fushimi Inari, Kiyomizu-dera and the old streets — Nishiki removed to keep the day walkable.",
      "Convenience breakfast; Higashiyama café lunch.",
      ["fushimi-inari", "kiyomizu", "sannenzaka"],
      ["Early Keihan/JR to Fushimi.", "Bus/walk Higashiyama cluster.", "Stop when stairs win — no market add-on today."],
      ["Hike higher at Fushimi to beat crowds.", "Kinkaku-ji is on Sep 13 with east Kyoto."],
      [
        t("06:30", "Fushimi Inari Taisha", "fushimi-inari", "Sunrise torii hike.", "10:00"),
        t("10:30", "Café break", None),
        t("11:30", "Kiyomizu-dera", "kiyomizu", "Wooden stage temple.", "13:00"),
        t("13:15", "Sannenzaka & Ninenzaka", "sannenzaka", "Preserved stone streets — then rest / early dinner nearby.", "16:00"),
        t("18:30", "Easy dinner near hotel", None, "Recovery night after the climbs."),
      ]),
  day("d16", "2026-09-11", "Friday", "Kyoto", "JP", None,
      "Arashiyama bamboo & monkey park",
      "West Kyoto day: stone statues, bamboo grove, Tenryu-ji, the bridge, and Monkey Park views.",
      "Lunch near Togetsukyo Bridge.",
      ["otagi", "adashino", "saga-toriimoto", "bamboo", "tenryuji", "kimono-forest", "togetsukyo", "monkey-park"],
      ["Train/bus toward Saga-Arashiyama; walk the west Kyoto chain."],
      ["Bamboo early if possible.", "Monkey park is a real climb."],
      [
        t("08:00", "Otagi Nenbutsu-ji", "otagi", "1,200 stone rakan statues.", "09:15"),
        t("09:30", "Adashino Nenbutsu-ji", "adashino"),
        t("10:30", "Saga Toriimoto Street", "saga-toriimoto"),
        t("11:15", "Bamboo Grove & Tenryu-ji", "bamboo", "Iconic path + Zen garden.", "13:00"),
        t("13:15", "Kimono Forest & lunch", "kimono-forest", "Near Arashiyama Station / bridge.", "14:45"),
        t("15:00", "Togetsukyo Bridge", "togetsukyo"),
        t("15:30", "Iwatayama Monkey Park", "monkey-park", "Panoramic city views.", "17:30"),
        t("19:00", "Central Kyoto dinner", None),
      ]),
  day("d17", "2026-09-12", "Saturday", "Kyoto", "JP", None,
      "Kurama & Kibune mountain day",
      "Mountain day trip to Kurama and Kibune — temple, forest walk, must-book kawadoko riverside lunch (Hirobun / Fujiya), optional onsen.",
      "Booked kawadoko lunch over the river — romantic highlight.",
      ["kurama-dera", "kifune", "kawadoko", "kurama-onsen"],
      ["Demachiyanagi → Eizan to Kurama (~30m, ~¥430).", "Trek ~45m to Kibune.", "Return Kibuneguchi."],
      ["Reserve kawadoko weeks ahead (Hirobun or Fujiya) — early September is classic season end.", "One of the trip highlights — go if weather is decent."],
      [
        t("08:30", "Train to Kurama", "kurama-dera", "Via Demachiyanagi + Eizan."),
        t("09:30", "Kurama-dera Temple", "kurama-dera", "Mountain temple visit.", "10:45"),
        t("11:00", "Forest trek to Kibune", None, "~45 minutes through cedar forest.", "11:45"),
        t("12:00", "Kifune Shrine", "kifune", "Red lantern stairs.", "13:00"),
        t("13:15", "Kawadoko riverside lunch", "kawadoko", "Decks over the stream — Hirobun / Fujiya reserved.", "15:00"),
        t("15:30", "Kurama Onsen (if open)", "kurama-onsen", "Soak after the hike.", "17:30"),
        t("18:30", "Return to Kyoto", None),
      ]),
  day("d18", "2026-09-13", "Sunday", "Kyoto", "JP", None,
      "Zen gardens & Golden Pavilion",
      "East Kyoto zen path from Ginkaku-ji to Nanzen-ji, then Kinkaku-ji at golden hour and a farewell Kyoto dinner.",
      "Lunch near Nanzen-ji; celebratory Kyoto dinner.",
      ["ginkakuji", "philosophers-path", "nanzenji", "kinkakuji", "pontocho"],
      ["Bus to Ginkaku-ji; walk path; taxi ~25–30m to Kinkaku-ji."],
      ["Kinkaku-ji placed here (not duplicated earlier).", "Forward bags to Osaka tonight."],
      [
        t("08:30", "Ginkaku-ji (Silver Pavilion)", "ginkakuji", "Morning gardens.", "10:15"),
        t("10:30", "Philosopher’s Path", "philosophers-path", "Peaceful canal walk.", "12:15"),
        t("12:30", "Nanzen-ji & lunch", "nanzenji", "Temple + aqueduct.", "14:30"),
        t("15:30", "Kinkaku-ji golden hour", "kinkakuji", "Taxi across town for sunlight on gold.", "17:30"),
        t("19:00", "Farewell Kyoto dinner", "pontocho"),
      ]),
  day("d19", "2026-09-14", "Monday", "Osaka", "JP", None,
      "Transfer to Osaka & street food heaven",
      "Short hop to Osaka, castle park and Shinsekai, then a Dotonbori food crawl. Hotel still to book.",
      "Takoyaki & okonomiyaki in Dotonbori.",
      ["osaka-castle", "shinsekai", "dotonbori", "hozenji"],
      ["Kyoto → Osaka train (~30–45m).", "Book an Osaka hotel near Namba/Dotonbori."],
      ["Base Osaka for USJ, Nara, and Hiroshima day trip."],
      [
        t("09:30", "Train Kyoto → Osaka", None, "~30 minutes."),
        t("11:00", "Hotel check-in", None),
        t("12:30", "Osaka Castle Park", "osaka-castle", "Castle grounds stroll.", "15:00"),
        t("15:30", "Shinsekai & Tsutenkaku", "shinsekai", "Retro Osaka vibes.", "17:30"),
        t("18:30", "Dotonbori food crawl", "dotonbori", "Glico sign photos + street food.", "21:00"),
        t("21:15", "Hozenji Yokocho alley", "hozenji", "Mossy lantern lane near Dotonbori."),
      ]),
  day("d20", "2026-09-15", "Tuesday", "Osaka", "JP", None,
      "Universal Studios Japan",
      "All day at Universal Studios Japan — Nintendo World and Harry Potter. Express Pass must be booked exactly 2 months ahead at midnight JST.",
      "Park snacks; late Namba ramen optional.",
      ["usj"],
      ["Subway to Universal City (~25–35m). Leave by ~07:45."],
      ["Book Express Pass exactly 2 months prior at 00:00 Japan time — locks Nintendo World entry window and skips the rope-drop sprint.", "Check Nintendo World entry rules."],
      [
        t("07:45", "Depart hotel", None),
        t("09:00", "USJ with Express Pass", "usj", "Timed Nintendo World + Harry Potter priority.", "12:30"),
        t("12:30", "Lunch in park", "usj"),
        t("13:30", "Afternoon rides & shows", "usj", "Continue headliners.", "18:30"),
        t("18:30", "Evening park vibe", "usj", "Stay for night energy if you can.", "21:00"),
        t("21:30", "Return Namba", None),
      ]),
  day("d21", "2026-09-16", "Wednesday", "Osaka", "JP", None,
      "Nara deer park day trip",
      "Day trip to Nara for deer park, Todai-ji and Kasuga Taisha; evening back in Shinsaibashi and Amerikamura.",
      "Nara lunch; Amerikamura casual dinner.",
      ["nara-park", "kasuga", "shinsaibashi", "amerikamura"],
      ["Kintetsu/JR to Nara (~45m).", "Return for evening shopping."],
      ["Deer crackers are fun — guard bags.", "Bowing deer are bold."],
      [
        t("08:30", "Train to Nara", "nara-park"),
        t("09:30", "Nara Park & deer", "nara-park", "Todai-ji Great Buddha.", "13:00"),
        t("13:15", "Kasuga Taisha", "kasuga", "Lantern shrine.", "14:30"),
        t("15:00", "Return to Osaka", None),
        t("17:30", "Shinsaibashi shopping", "shinsaibashi"),
        t("19:30", "Dinner in Amerikamura", "amerikamura"),
      ]),
  day("d22", "2026-09-17", "Thursday", "Osaka", "JP", None,
      "Hiroshima & Miyajima day trip",
      "Early Shinkansen day trip to Miyajima and Hiroshima Peace Park, okonomiyaki, then back to Osaka.",
      "Hiroshima-style okonomiyaki before return.",
      ["miyajima", "peace-park", "okonomiyaki"],
      ["Early Nozomi/Sakura to Hiroshima (~80m).", "Ferry to Miyajima.", "Evening Shinkansen back."],
      ["Day trip — no Hiroshima hotel.", "Check tide times for torii.", "Start very early."],
      [
        t("07:00", "Shinkansen to Hiroshima", None, "~80 minutes."),
        t("09:00", "Miyajima Island & Itsukushima", "miyajima", "Floating torii + island stroll.", "13:00"),
        t("14:00", "Peace Memorial Park & Museum", "peace-park", "Allow real time.", "16:30"),
        t("17:00", "Hiroshima okonomiyaki", "okonomiyaki"),
        t("18:30", "Shinkansen return to Osaka", None, "Evening arrival."),
      ]),
  day("d23", "2026-09-18", "Friday", "Osaka", "JP", None,
      "Umeda & modern Osaka",
      "Modern Osaka: Umeda shopping, sunset at Umeda Sky Building, drinks in Namba or Nakazakicho.",
      "Umeda lunch; Namba evening drinks.",
      ["umeda-sky", "dotonbori"],
      ["Subway to Umeda.", "Return south for nightlife."],
      ["Floating Garden Observatory at golden hour."],
      [
        t("10:00", "Umeda shopping", "umeda-sky", "Hep Five, Grand Front Osaka.", "14:00"),
        t("16:00", "Umeda Sky Building sunset", "umeda-sky", "Kuchu Teien Observatory.", "18:30"),
        t("20:00", "Drinks in Namba / Nakazakicho", "dotonbori"),
      ]),
  day("d24", "2026-09-19", "Saturday", "Tokyo", "JP", None,
      "Return to Tokyo & nightlife",
      "Shinkansen back to Tokyo (~2.5h), check into a Ginza/Shiodome-area hotel (best for NRT+HND), then Roppongi or Azabudai, Tokyo Tower night and Kabukicho.",
      "Roppongi/Azabudai dinner.",
      ["ginza", "roppongi", "azabudai", "tokyo-tower", "kabukicho"],
      ["Nozomi Osaka → Tokyo (~2.5h).", "Local transfer to Ginza / Shiodome hotel."],
      ["Prefer Ginza/Shiodome lodging for easy access to both Narita and Haneda.", "Neon night finale energy."],
      [
        t("09:00", "Shinkansen to Tokyo", None, "~2.5 hours."),
        t("12:30", "Hotel check-in — Ginza / Shiodome", "ginza", "Shopping + dual-airport access."),
        t("14:30", "Roppongi or Azabudai Hills", "azabudai", "Modern complex wander.", "17:30"),
        t("18:30", "Tokyo Tower night photos", "tokyo-tower"),
        t("20:00", "Kabukicho arcade & bars", "kabukicho"),
      ]),
  day("d25", "2026-09-20", "Sunday", "Tokyo", "JP", None,
      "Soft Tokyo day",
      "Calm morning in Shinjuku Gyoen, then Shimokitazawa or Nakano Broadway, and a specialty wagyu dinner.",
      "Wagyu BBQ dinner.",
      ["shinjuku-gyoen", "shimokitazawa", "nakano-broadway"],
      ["Gyoen near Shinjuku.", "Choose Shimokita OR Nakano Broadway."],
      ["Gyoen has an entry fee — worth it for calm."],
      [
        t("09:30", "Shinjuku Gyoen National Garden", "shinjuku-gyoen", "Relaxing green morning.", "12:00"),
        t("13:30", "Shimokitazawa OR Nakano Broadway", "shimokitazawa", "Vintage thrift vs otaku maze.", "17:30"),
        t("19:00", "Specialty wagyu BBQ dinner", None),
      ]),
  day("d26", "2026-09-21", "Monday", "Tokyo", "JP", None,
      "Flex day in Tokyo",
      "No Kamakura — after nearly four weeks of walking, keep a free Tokyo day: late wake-up, cafés in Shimokitazawa/Harajuku, or light last shopping.",
      "Café hopping; easy dinner near the hotel.",
      ["shimokitazawa", "takeshita", "ginza"],
      ["Stay local — Ginza / Harajuku / Shimokita on a whim."],
      ["Protect recovery before departure.", "Kamakura dropped on purpose."],
      [
        t("10:30", "Late start — café of choice", None, "Sleep in without guilt."),
        t("13:00", "Flex: Shimokitazawa / Harajuku / Ginza", "shimokitazawa", "Pick one neighborhood and wander.", "17:30"),
        t("19:30", "Easy dinner near hotel", "ginza"),
      ]),
  day("d27", "2026-09-22", "Tuesday", "Tokyo", "JP", None,
      "Last-minute shopping & fine dining",
      "Last focused shopping day in Ginza (you’re already based nearby), Akihabara or Shibuya if needed, then a celebratory farewell dinner.",
      "Farewell fine dining in Tokyo.",
      ["ginza", "akihabara", "shibuya-crossing"],
      ["Pick one shopping focus to avoid rushing."],
      ["Pack non-essentials tonight.", "Ginza base makes airport morning simpler."],
      [
        t("10:00", "Shopping — Ginza focus (or Akihabara / Shibuya)", "ginza", "Choose your lane.", "17:00"),
        t("19:30", "Farewell celebratory dinner", None, "Toast the trip."),
      ]),
  day("d28", "2026-09-23", "Wednesday", "Tokyo", "JP", None,
      "Pack & departure",
      "Pack, travel to Narita or Haneda, and fly home. Keep Sep 24 as a buffer if the flight is later.",
      "Airport meal.",
      ["narita"],
      ["Allow 2.5–3h door-to-gate.", "N'EX to NRT or Monorail/train to HND."],
      ["Confirm actual flight date (Sep 23 or 24).", "Keep passports & Visit Japan Web QR handy."],
      [
        t("09:00", "Final pack & checkout", None),
        t("12:00", "Depart for airport", "narita", "Match NRT vs HND to your ticket."),
        t("15:00", "Airport buffer", "narita", "Security, food, duty-free."),
        t("18:00", "Departure (placeholder)", "narita", "Replace with real flight time — use Sep 24 if needed."),
      ]),
]

TRIP = {
    "title": "Korea + Japan 2026",
    "subtitle": "Idan & Shahar itinerary (dad's Excel was inspiration only)",
    "dates": "August 27 – September 23/24, 2026",
    "route": ["Seoul", "Tokyo", "Hakone", "Kawaguchiko", "Kyoto", "Osaka", "Tokyo"],
    "notes": [
        "Synced to the upgraded itinerary: filled Tokyo/Osaka days, Mishima Shinkansen to Kyoto (not overnight bus), Kinkaku-ji only with east Kyoto, Hiroshima as Osaka day trip.",
        "Sep 5 is DisneySea OR Ghibli/Shimokitazawa — pick one.",
        "Sep 21 Kamakura is optional.",
        "Departure listed Sep 23 with Sep 24 buffer — set your real flight.",
        "Tap places for Google / Kakao / Naver / Yahoo! / Apple Maps.",
    ],
}

for d in DAYS:
    if d["id"] in TRANSFERS:
        d["transfer"] = TRANSFERS[d["id"]]
    for item in d.get("timeline") or []:
        if not item.get("category"):
            item["category"] = infer_category(item.get("title", ""), item.get("placeId"), item.get("note", ""))

def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

js = f"""/* Auto-generated trip data — Seoul + Japan detailed timelines */
window.TRIP = {dumps(TRIP)};
window.PLACES = {dumps(PLACES)};
window.DAYS = {dumps(DAYS)};
"""
OUT.write_text(js, encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
print(f"Days: {len(DAYS)}, Places: {len(PLACES)}")
print("Transfers:", sum(1 for d in DAYS if d.get("transfer")))
