#!/usr/bin/env python3
"""Build docs/js/data.js with Seoul + Japan detailed timelines."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "js" / "data.js"

def place(id, name, name_local, city, country, tags, lat, lng, blurb, taxi_address=None):
    p = {
        "id": id, "name": name, "nameJa": name_local, "city": city, "country": country,
        "tags": tags, "lat": lat, "lng": lng, "blurb": blurb,
    }
    if taxi_address:
        p["taxiAddress"] = taxi_address
    return p

PLACES = {}

def add(p):
    PLACES[p["id"]] = p

# --- Seoul ---
for p in [
    place("amanti-hotel", "Amanti Hotel Seoul Hongdae", "아만티호텔 서울", "Seoul", "KR", ["hotel", "booked"], 37.5577, 126.9248, "Booked — Seoul base in Hongdae (27 Aug–2 Sep).", "서울특별시 마포구 월드컵북로 31"),
    place("namdaemun", "Namdaemun Market", "남대문시장", "Seoul", "KR", ["must-see", "food", "market"], 37.5595, 126.9770, "Classic downtown market — snacks, clothes, souvenirs."),
    place("mangwon", "Mangwon Market", "망원시장", "Seoul", "KR", ["food", "market", "neighborhood"], 37.5560, 126.9102, "Local market next to Yeonnam — street snacks and produce."),
    place("tlv", "Ben Gurion Airport (TLV)", "נתב\"ג", "Tel Aviv", "IL", ["transport"], 32.0114, 34.8867, "Departure — Ethiopian via Addis to Seoul."),
    place("add", "Addis Ababa Bole (ADD)", "አዲስ አበባ", "Addis Ababa", "ET", ["transport"], 8.9779, 38.7993, "Ethiopian Airlines hub — connection TLV → ICN."),
    place("icn", "Incheon Airport (ICN)", "인천국제공항", "Seoul", "KR", ["transport"], 37.4602, 126.4407, "Seoul arrival / departure."),
    place("myeongdong", "Myeongdong", "명동", "Seoul", "KR", ["shopping", "food", "neighborhood"], 37.5636, 126.9869, "K-beauty, street food, neon shopping."),
    place("hongdae", "Hongdae", "홍대", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5563, 126.9236, "Student arts district — cafés, bars, street performers."),
    place("gyeongbokgung", "Gyeongbokgung Palace", "경복궁", "Seoul", "KR", ["must-see", "culture"], 37.5796, 126.9770, "Main royal palace — rent hanbok for free entry vibe."),
    place("bukchon", "Bukchon Hanok Village", "북촌한옥마을", "Seoul", "KR", ["must-see", "neighborhood", "culture"], 37.5826, 126.9831, "Traditional hanok hillside lanes."),
    place("ikseon", "Ikseon-dong", "익선동", "Seoul", "KR", ["neighborhood", "food", "culture"], 37.5740, 126.9897, "Hip hanok alleys with cafés and bars."),
    place("insadong", "Insadong", "인사동", "Seoul", "KR", ["shopping", "culture", "food"], 37.5742, 126.9847, "Tea houses, crafts, souvenir shopping."),
    place("cheonggyecheon", "Cheonggyecheon Stream", "청계천", "Seoul", "KR", ["must-see", "nature", "neighborhood"], 37.5696, 126.9784, "Downtown stream walk between Insadong and markets."),
    place("gwangjang", "Gwangjang Market", "광장시장", "Seoul", "KR", ["must-see", "food", "market"], 37.5700, 126.9996, "Bindaetteok, mayak gimbap, night market energy (open late)."),
    place("eunpyeong", "Eunpyeong Hanok Village", "은평한옥마을", "Seoul", "KR", ["neighborhood", "culture"], 37.6408, 126.9345, "Quieter traditional village alternative."),
    place("lotte-world", "Lotte World Adventure", "롯데월드", "Seoul", "KR", ["must-see", "park"], 37.5110, 127.0980, "Indoor/outdoor theme park — full day."),
    place("lotte-tower", "Lotte World Tower Seoul Sky", "롯데월드타워", "Seoul", "KR", ["must-see", "view"], 37.5126, 127.1025, "One of the world’s tallest — Seoul Sky observatory."),
    place("seokchon", "Seokchon Lake", "석촌호수", "Seoul", "KR", ["neighborhood", "nature"], 37.5095, 127.1035, "Lake walk beside Lotte Tower."),
    place("jimjilbang", "Jimjilbang (spa complex)", "찜질방", "Seoul", "KR", ["culture", "onsen"], 37.5110, 127.0980, "Korean bathhouse near Jamsil — perfect reset after Lotte World."),
    place("jogyesa", "Jogyesa Temple", "조계사", "Seoul", "KR", ["temple", "culture"], 37.5735, 126.9825, "Major Buddhist temple near Insadong."),
    place("changdeokgung", "Changdeokgung + Secret Garden", "창덕궁 후원", "Seoul", "KR", ["must-see", "culture"], 37.5794, 126.9910, "UNESCO palace — book Secret Garden timed tour."),
    place("gangnam", "Gangnam", "강남", "Seoul", "KR", ["neighborhood", "shopping"], 37.4979, 127.0276, "Treatments, shopping, K-pop landmarks."),
    place("unni-guide", "Unni Guide Center", "언니 가이드 센터", "Seoul", "KR", ["must-see", "culture"], 37.5045, 127.0250, "Gangnam Unni Guide — clinic matching, skin analysis & booking help for visitors (book ahead)."),
    place("bongeunsa", "Bongeunsa Temple", "봉은사", "Seoul", "KR", ["temple", "culture"], 37.5152, 127.0574, "Temple beside COEX — calm contrast to Gangnam."),
    place("coex", "COEX & Starfield Library", "코엑스 별마당도서관", "Seoul", "KR", ["must-see", "shopping", "culture"], 37.5117, 127.0595, "Giant mall + iconic Starfield Library."),
    place("dongdaemun", "Dongdaemun Night Market / DDP", "동대문", "Seoul", "KR", ["shopping", "nightlife", "food"], 37.5665, 127.0092, "Night fashion markets + DDP / APM / Hyundai City Outlets."),
    place("seongsu", "Seongsu-dong", "성수동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5445, 127.0557, "Brooklyn-feel cafés, pop-ups, and design shops."),
    place("seoul-forest", "Seoul Forest", "서울숲", "Seoul", "KR", ["must-see", "park", "nature"], 37.5443, 127.0375, "Large urban park next to Seongsu."),
    place("seoulistique", "Seoulistique Skin", "서울리스틱 스킨", "Seoul", "KR", ["must-see", "culture"], 37.5448, 127.0565, "Facial + skin analysis in Seongsu — book via Instagram @seoulistique.skin / WhatsApp."),
    place("yeonnam", "Yeonnam-dong", "연남동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5662, 126.9254, "Chill cafés and boutiques next to Hongdae."),
    place("namsan-cable", "Namsan Cable Car", "남산케이블카", "Seoul", "KR", ["must-see", "transport", "view"], 37.5486, 126.9905, "Cable car up Namsan toward N Seoul Tower."),
    place("n-tower", "N Seoul Tower", "N서울타워", "Seoul", "KR", ["must-see", "view"], 37.5512, 126.9882, "Namsan sunset views + love locks."),
    place("itaewon", "Itaewon", "이태원", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5345, 126.9944, "International bars, LGBTQ+ friendly nightlife."),
]:
    add(p)

# --- Japan (existing + a few extras) ---
for p in [
    place("gracery-shinjuku", "Hotel Gracery Shinjuku", "ホテルグレイスリー新宿", "Tokyo", "JP", ["hotel", "booked"], 35.6956, 139.7023, "Booked — first Tokyo base in Kabukicho (Godzilla head) · nights 2–6/9, checkout 7/9 for Hakone.", "東京都新宿区歌舞伎町1-19-1"),
    place("keio-plaza", "Keio Plaza Hotel Tokyo", "京王プラザホテル", "Tokyo", "JP", ["hotel", "inspiration"], 35.6906, 139.6921, "Near Shinjuku — not on this itinerary."),
    place("narita", "Narita Airport (NRT)", "成田国際空港", "Tokyo", "JP", ["transport"], 35.7720, 140.3929, "Tokyo arrival / later departure to Tirana via Dubai (Emirates)."),
    place("shinjuku", "Shinjuku", "新宿", "Tokyo", "JP", ["neighborhood", "food", "nightlife"], 35.6938, 139.7034, "Neon, shopping, Godzilla."),
    place("shibuya-crossing", "Shibuya Crossing", "渋谷スクランブル交差点", "Tokyo", "JP", ["must-see", "icon"], 35.6595, 139.7005, "Scramble crossing + Hachiko — classic Tokyo icon."),
    place("meiji-jingu", "Meiji Jingu", "明治神宮", "Tokyo", "JP", ["must-see", "culture", "shrine"], 35.6764, 139.6993, "Quiet Shinto shrine in a forest near Harajuku — best early."),
    place("takeshita", "Takeshita Street", "竹下通り", "Tokyo", "JP", ["food", "shopping"], 35.6702, 139.7050, "Harajuku crepes & youth fashion."),
    place("cat-street", "Cat Street", "キャットストリート", "Tokyo", "JP", ["shopping", "neighborhood"], 35.6658, 139.7038, "Stylish Harajuku side street."),
    place("omotesando", "Omotesando", "表参道", "Tokyo", "JP", ["shopping", "architecture"], 35.6652, 139.7122, "Tree-lined boutiques."),
    place("disneysea", "Tokyo DisneySea", "東京ディズニーシー", "Tokyo", "JP", ["park", "inspiration"], 35.6267, 139.8851, "Unique Disney park — not on this itinerary."),
    place("asakusa", "Asakusa / Senso-ji", "浅草寺", "Tokyo", "JP", ["must-see", "culture", "food"], 35.7148, 139.7967, "Classic temple Tokyo."),
    place("kappabashi", "Kappabashi Street", "合羽橋道具街", "Tokyo", "JP", ["food", "shopping"], 35.7155, 139.7870, "Kitchen-town souvenirs."),
    place("skytree", "Tokyo Skytree", "東京スカイツリー", "Tokyo", "JP", ["must-see", "view"], 35.7101, 139.8107, "634m tower + Solamachi mall; deck ticket optional."),
    place("tsukiji", "Tsukiji Outer Market", "築地場外市場", "Tokyo", "JP", ["must-see", "food"], 35.6654, 139.7707, "Outer-market breakfast — sushi, nigiri, and fresh fish with tamago."),
    place("imperial-east", "Imperial Palace East Gardens", "皇居東御苑", "Tokyo", "JP", ["culture", "park"], 35.6865, 139.7575, "Quiet castle gardens."),
    place("ginza", "Ginza", "銀座", "Tokyo", "JP", ["shopping", "food"], 35.6712, 139.7649, "Dept stores & depachika."),
    place("teamlab-planets", "teamLab Planets Tokyo", "チームラボプラネッツ", "Tokyo", "JP", ["must-see", "culture"], 35.6490, 139.7868, "Immersive water-based digital art — book ahead."),
    place("odaiba", "Odaiba / DiverCity Gundam", "お台場", "Tokyo", "JP", ["park", "shopping"], 35.6251, 139.7755, "Gundam + waterfront."),
    place("street-kart", "Street Kart Tokyo", "ストリートカート東京", "Tokyo", "JP", ["must-see", "park", "nightlife"], 35.6585, 139.7015, "Night go-kart through neon streets — physical IDP required · book an evening slot (~19:00)."),
    place("kichijoji", "Kichijoji", "吉祥寺", "Tokyo", "JP", ["neighborhood", "shopping", "food"], 35.7031, 139.5798, "Chill shopping & cafés by Inokashira Park."),
    place("ameyoko", "Ameyoko Market", "アメ横", "Tokyo", "JP", ["food", "market"], 35.7095, 139.7745, "Street-food market."),
    place("akihabara", "Akihabara", "秋葉原", "Tokyo", "JP", ["park", "shopping"], 35.7023, 139.7745, "Arcades, Animate, and anime floors — good izakaya evening."),
    place("golden-gai", "Shinjuku Golden Gai", "新宿ゴールデン街", "Tokyo", "JP", ["must-see", "nightlife"], 35.6938, 139.7047, "Tiny bar alleys."),
    place("daikanyama", "Daikanyama T-Site", "代官山T-SITE", "Tokyo", "JP", ["culture", "food"], 35.6492, 139.7032, "Bookstore complex."),
    place("nakameguro", "Nakameguro / Meguro River", "中目黒", "Tokyo", "JP", ["neighborhood", "food"], 35.6442, 139.6988, "Riverside boutiques."),
    place("ny-bar", "New York Bar (Park Hyatt)", "ニューヨークバー", "Tokyo", "JP", ["nightlife", "view"], 35.6855, 139.6905, "Lost in Translation bar — Park Hyatt reopened Dec 2025 after renovation; reserve ahead."),
    place("kajikaso", "Hotel Kajikaso", "ホテルかじか荘", "Hakone", "JP", ["hotel", "onsen", "inspiration"], 35.2335, 139.0885, "Hakone ryokan — not on this itinerary."),
    place("tsukino-yado-sara", "Tsukino Yado Sara", "月の宿 紗ら", "Hakone", "JP", ["hotel", "onsen", "booked"], 35.2291, 139.0983, "Booked — Hakone-Yumoto ryokan · rooms with open-air baths · kaiseki · ~10 min from Hakone-Yumoto Station.", "神奈川県足柄下郡箱根町湯本588-1"),
    place("owakudani", "Owakudani", "大涌谷", "Hakone", "JP", ["must-see", "nature", "food"], 35.2424, 139.0204, "Volcanic valley + black eggs."),
    place("hakone-shrine", "Hakone Shrine", "箱根神社", "Hakone", "JP", ["must-see", "shrine"], 35.2051, 139.0256, "Lakeside torii — best at sunrise."),
    place("lake-ashi", "Lake Ashi Pirate Ship", "箱根海賊船", "Hakone", "JP", ["nature", "park"], 35.2065, 139.0250, "Sightseeing cruise on Lake Ashi."),
    place("fuji-view-bus", "Kawaguchiko Sightseeing Bus", "河口湖周遊バス", "Kawaguchiko", "JP", ["transport", "must-see"], 35.4985, 138.7685, "Tourist loop buses (red/green/blue) linking Lawson, Chureito, Oishi and Fuji viewpoints."),
    place("open-air", "Hakone Open-Air Museum", "箱根彫刻の森美術館", "Hakone", "JP", ["culture"], 35.2445, 139.0515, "Outdoor sculpture museum."),
    place("fuji-lawson", "Lawson Kawaguchiko Station", "ローソン河口湖駅前", "Kawaguchiko", "JP", ["icon", "must-see"], 35.4983, 138.7689, "Famous Fuji convenience-store shot."),
    place("gotemba-outlets", "Gotemba Premium Outlets", "御殿場プレミアム・アウトレット", "Kawaguchiko", "JP", ["shopping", "must-see"], 35.3086, 138.9365, "Huge outlet mall with Fuji views — brands at discount; open 10:00–20:00 Mar–Nov."),
    place("oishi-park", "Oishi Park", "大石公園", "Kawaguchiko", "JP", ["must-see", "view"], 35.5245, 138.7470, "Sunset Fuji lakeside."),
    place("chureito", "Chureito Pagoda", "忠霊塔", "Kawaguchiko", "JP", ["must-see", "icon"], 35.5012, 138.8013, "Sunrise pagoda + Fuji."),
    place("fuji-q", "Fuji-Q Highland", "富士急ハイランド", "Kawaguchiko", "JP", ["must-see", "park"], 35.4871, 138.7806, "World-class coasters."),
    place("mystays-fuji-onsen", "HOTEL MYSTAYS Fuji Onsen Resort", "ホテルマイステイズ富士温泉リゾート", "Kawaguchiko", "JP", ["hotel", "onsen", "booked"], 35.4921, 138.7801, "Booked — Fujiyoshida / Kawaguchiko base · onsen resort · ~5 min walk from Fujikyu Highland Station · nights 8–9/9, checkout 10/9.", "山梨県富士吉田市新倉2654"),
    place("kabin-koji", "KABIN Koji", "カビン小路", "Kyoto", "JP", ["hotel", "booked"], 35.0003, 135.7647, "Booked — Kyoto base near Kawaramachi / Shijo · ~6 min walk from Kawaramachi Station · nights 11–14/9, checkout 15/9.", "京都府京都市下京区筋屋町152"),
    place("musse-kyoto", "Hotel Musse Kyoto", "ホテルミュッセ京都四条河原町名鉄", "Kyoto", "JP", ["hotel", "inspiration"], 35.0037, 135.7685, "Near Kawaramachi — not on this itinerary."),
    place("kenninji", "Kennin-ji", "建仁寺", "Kyoto", "JP", ["temple", "culture"], 35.0008, 135.7735, "Oldest Zen temple in Kyoto."),
    place("teamlab-biovortex", "teamLab Biovortex Kyoto", "チームラボ バイオヴォルテックス 京都", "Kyoto", "JP", ["must-see", "culture", "booked"], 34.9828, 135.7568, "Booked — 14/9 entry 18:00–18:30 · Japan’s largest teamLab · ~7 min from Kyoto Station Hachijo East.", "京都府京都市南区東九条東岩本町21-5"),
    place("gion", "Gion", "祇園", "Kyoto", "JP", ["must-see", "neighborhood"], 35.0037, 135.7788, "Geisha district lanes — respectful photos at dusk."),
    place("pontocho", "Pontocho Alley", "先斗町", "Kyoto", "JP", ["food", "nightlife"], 35.0045, 135.7712, "Dinner alley by the river."),
    place("fushimi-inari", "Fushimi Inari Taisha", "伏見稲荷大社", "Kyoto", "JP", ["must-see", "shrine"], 34.9671, 135.7727, "Thousands of torii."),
    place("tofukuji", "Tofuku-ji", "東福寺", "Kyoto", "JP", ["temple", "culture"], 34.9606, 135.7800, "Zen temple near Fushimi — Tsutenkyo bridge and gardens."),
    place("byodoin", "Byodo-in", "平等院", "Kyoto", "JP", ["must-see", "temple", "culture"], 34.8894, 135.8077, "Phoenix Hall — the temple on the ¥10 coin."),
    place("uji-omotesando", "Uji Omotesando", "宇治表参道", "Kyoto", "JP", ["must-see", "food", "shopping"], 34.8905, 135.8088, "Historic tea-shop street — matcha sweets and street snacks."),
    place("uji-river", "Uji River", "宇治川", "Kyoto", "JP", ["nature", "neighborhood"], 34.8912, 135.8095, "Scenic bridges and riverside walk in Uji."),
    place("kiyomizu", "Kiyomizu-dera", "清水寺", "Kyoto", "JP", ["must-see", "temple"], 34.9949, 135.7850, "Wooden stage temple."),
    place("sannenzaka", "Sannenzaka & Ninenzaka", "三年坂・二年坂", "Kyoto", "JP", ["must-see", "food"], 34.9958, 135.7815, "Stone postcard streets."),
    place("kinkakuji", "Kinkaku-ji", "金閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0394, 135.7292, "Golden Pavilion."),
    place("nishiki", "Nishiki Market", "錦市場", "Kyoto", "JP", ["must-see", "food"], 35.0050, 135.7649, "Kyoto’s kitchen."),
    place("otagi", "Otagi Nenbutsu-ji", "愛宕念仏寺", "Kyoto", "JP", ["must-see", "temple"], 35.0317, 135.6628, "1,200 rakan statues."),
    place("adashino", "Adashino Nenbutsu-ji", "化野念仏寺", "Kyoto", "JP", ["temple", "culture"], 35.0267, 135.6645, "Bamboo & stone Buddhas."),
    place("saga-toriimoto", "Saga Toriimoto", "嵯峨鳥居本", "Kyoto", "JP", ["neighborhood"], 35.0255, 135.6680, "Preserved approach street."),
    place("bamboo", "Arashiyama Bamboo Grove", "竹林の小径", "Kyoto", "JP", ["must-see", "nature"], 35.0173, 135.6721, "Iconic bamboo path."),
    place("kimono-forest", "Kimono Forest", "キモノフォレスト", "Kyoto", "JP", ["icon"], 35.0153, 135.6775, "Kimono cylinder pillars."),
    place("togetsukyo", "Togetsukyo Bridge", "渡月橋", "Kyoto", "JP", ["icon", "nature"], 35.0135, 135.6778, "Arashiyama bridge."),
    place("monkey-park", "Iwatayama Monkey Park", "嵐山モンキーパーク", "Kyoto", "JP", ["park", "nature"], 35.0117, 135.6761, "Monkeys + city view."),
    place("tenryuji", "Tenryu-ji", "天龍寺", "Kyoto", "JP", ["temple", "culture"], 35.0156, 135.6736, "UNESCO Zen garden."),
    place("kurama-dera", "Kurama-dera", "鞍馬寺", "Kyoto", "JP", ["must-see", "temple", "nature"], 35.1181, 135.7709, "Mountain temple at the end of the Kibune to Kurama forest trek."),
    place("kifune", "Kifune Shrine", "貴船神社", "Kyoto", "JP", ["must-see", "shrine"], 35.1216, 135.7631, "Lantern stone stairs."),
    place("hirobun", "Hirobun Nagashi Somen", "料理旅館 ひろ文（流しそうめん）", "Kyoto", "JP", ["must-see", "food"], 35.1220, 135.7632, "Walk-in nagashi somen on the Kibune river deck next to Kifune Yui shrine — cash ~¥2,000, no reservation.", "京都府京都市左京区鞍馬貴船町87"),
    place("kurama-onsen", "Kurama Onsen", "鞍馬温泉", "Kyoto", "JP", ["onsen"], 35.1128, 135.7725, "Mountain onsen."),
    place("ginkakuji", "Ginkaku-ji", "銀閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0264, 135.7986, "Silver Pavilion."),
    place("philosophers-path", "Philosopher’s Path", "哲学の道", "Kyoto", "JP", ["neighborhood", "nature"], 35.0205, 135.7955, "Canal stroll."),
    place("nanzenji", "Nanzen-ji", "南禅寺", "Kyoto", "JP", ["temple", "culture"], 35.0116, 135.7945, "Zen temple + aqueduct."),
    place("uji", "Uji / Byodo-in", "宇治・平等院", "Kyoto", "JP", ["food", "temple"], 34.8894, 135.8077, "Matcha capital + Phoenix Hall."),
    place("daiwa-hiroshima", "Daiwa Roynet Hiroshima", "ダイワロイネットホテル広島", "Hiroshima", "JP", ["hotel", "inspiration"], 34.3927, 132.4553, "Hiroshima hotel — not on this itinerary."),
    place("shukkeien", "Shukkeien Garden", "縮景園", "Hiroshima", "JP", ["culture", "park"], 34.3995, 132.4674, "Miniature landscape garden."),
    place("peace-park", "Peace Memorial Park", "平和記念公園", "Hiroshima", "JP", ["must-see", "culture"], 34.3955, 132.4536, "Dome + museum."),
    place("okonomiyaki", "Okonomi-mura", "お好み村", "Hiroshima", "JP", ["food", "must-see"], 34.3938, 132.4622, "Hiroshima okonomiyaki hall."),
    place("miyajima", "Itsukushima Shrine", "厳島神社", "Hiroshima", "JP", ["must-see", "shrine"], 34.2960, 132.3198, "Floating torii."),
    place("misen", "Mt. Misen Ropeway", "弥山ロープウェイ", "Hiroshima", "JP", ["nature", "view"], 34.2905, 132.3185, "Island summit."),
    place("nunobiki", "Nunobiki Herb Garden / Ropeway", "布引ハーブ園", "Osaka", "JP", ["must-see", "nature", "view"], 34.7194, 135.1906, "Ropeway above Kobe — herb gardens + city/bay views."),
    place("kitano-ijinkan", "Kitano Ijinkan", "北野異人館", "Osaka", "JP", ["must-see", "culture", "neighborhood"], 34.6985, 135.1900, "Former foreign residences on the Kitano hillside."),
    place("nankinmachi", "Nankinmachi (Kobe Chinatown)", "南京町", "Osaka", "JP", ["food", "neighborhood", "must-see"], 34.6885, 135.1890, "Compact Chinatown lanes — street snacks between Motomachi and Sannomiya."),
    place("meriken-park", "Meriken Park & Harborland", "メリケンパーク・ハーバーランド", "Osaka", "JP", ["must-see", "view", "neighborhood"], 34.6825, 135.1865, "Waterfront park, Kobe Port Tower views, and Harborland shopping."),
    place("apt-hotel-11-shinsaibashi", "Apartment Hotel 11 Shinsaibashi 2", "アパートメントホテル11心斎橋2", "Osaka", "JP", ["hotel", "booked"], 34.6703, 135.5057, "Booked — Osaka apartment-hotel in Higashi-Shinsaibashi · near Dotonbori / Namba · nights 15–20/9, checkout 21/9.", "大阪府大阪市中央区東心斎橋2-2-12"),
    place("cross-osaka", "Cross Hotel Osaka", "クロスホテル大阪", "Osaka", "JP", ["hotel", "inspiration"], 34.6693, 135.5013, "Near Namba — not on this itinerary."),
    place("kuromon", "Kuromon Market", "黒門市場", "Osaka", "JP", ["must-see", "food"], 34.6664, 135.5064, "Osaka’s kitchen."),
    place("osaka-castle", "Osaka Castle", "大阪城", "Osaka", "JP", ["culture", "must-see"], 34.6873, 135.5262, "Castle in a large park — good morning stop before Shinsekai."),
    place("teamlab-botanical", "teamLab Botanical Garden Osaka", "チームラボ ボタニカルガーデン 大阪", "Osaka", "JP", ["culture", "park", "inspiration"], 34.6119, 135.5236, "Night digital art in Nagai — not on this itinerary (Biovortex in Kyoto instead)."),
    place("dotonbori", "Dotonbori", "道頓堀", "Osaka", "JP", ["must-see", "food", "nightlife"], 34.6687, 135.5013, "Neon food crawl."),
    place("usj", "Universal Studios Japan", "ユニバーサル・スタジオ・ジャパン", "Osaka", "JP", ["must-see", "park"], 34.6654, 135.4323, "Full park day 16/9 with Express Pass 7 — SNW morning windows, Harry Potter, Choice A/B, evening Hippogriff."),
    place("nara-park", "Nara Park / Todai-ji", "奈良公園・東大寺", "Osaka", "JP", ["must-see", "culture"], 34.6889, 135.8398, "Deer + Great Buddha."),
    place("shinsekai", "Shinsekai / Tsutenkaku", "新世界・通天閣", "Osaka", "JP", ["food", "neighborhood"], 34.6525, 135.5063, "Retro Osaka."),
    place("tenjinbashi", "Tenjinbashi-suji", "天神橋筋商店街", "Osaka", "JP", ["shopping", "food"], 34.7045, 135.5110, "Longest arcade."),
    place("umeda-sky", "Umeda Sky Building", "梅田スカイビル", "Osaka", "JP", ["must-see", "view"], 34.7055, 135.4897, "Floating Garden view."),
    place("ramen-museum", "Instant Ramen Museum", "カップヌードルミュージアム池田", "Osaka", "JP", ["food", "park"], 34.8195, 135.4258, "Make your Cup Noodle."),
    place("solaria", "Solaria Nishitetsu Ginza", "ソラリア西鉄ホテル銀座", "Tokyo", "JP", ["hotel", "inspiration"], 35.6695, 139.7668, "Ginza hotel — not on this itinerary."),
    place("ryogoku", "Ryogoku Kokugikan", "両国国技館", "Tokyo", "JP", ["must-see", "culture"], 35.6971, 139.7935, "Sumo stadium."),
    place("shimokitazawa", "Shimokitazawa", "下北沢", "Tokyo", "JP", ["neighborhood", "shopping"], 35.6616, 139.6683, "Vintage & indie cafés."),
    place("omoide-yokocho", "Omoide Yokocho (Memory Lane)", "思い出横丁", "Tokyo", "JP", ["food", "nightlife", "must-see"], 35.6935, 139.6995, "Smoky yakitori alleys by Shinjuku station."),
    place("shibuya-sky", "Shibuya Sky", "渋谷スカイ", "Tokyo", "JP", ["must-see", "view"], 35.6585, 139.7024, "Sunset observation deck — book timed tickets."),
    place("ueno-park", "Ueno Park", "上野公園", "Tokyo", "JP", ["park", "culture"], 35.7147, 139.7733, "Museums, temples, and green space."),
    place("ghibli", "Ghibli Museum", "三鷹の森ジブリ美術館", "Tokyo", "JP", ["must-see", "culture", "park"], 35.6962, 139.5703, "Lottery/reservation required — Mitaka."),
    place("inokashira", "Inokashira Park", "井の頭恩賜公園", "Tokyo", "JP", ["park", "nature"], 35.7000, 139.5750, "Lake park near Ghibli / Kichijoji."),
    place("hozenji", "Hozenji Yokocho", "法善寺横丁", "Osaka", "JP", ["neighborhood", "culture", "food"], 34.6678, 135.5025, "Mossy lantern alley near Dotonbori."),
    place("shinsaibashi", "Shinsaibashi", "心斎橋", "Osaka", "JP", ["shopping", "neighborhood"], 34.6750, 135.5013, "Major shopping arcade next to Namba."),
    place("amerikamura", "Amerikamura", "アメリカ村", "Osaka", "JP", ["neighborhood", "shopping", "nightlife"], 34.6728, 135.4985, "Youth fashion and easy dinner near Shinsaibashi."),
    place("roppongi", "Roppongi", "六本木", "Tokyo", "JP", ["neighborhood", "nightlife"], 35.6628, 139.7314, "Nightlife and city views."),
    place("azabudai", "Azabudai Hills", "麻布台ヒルズ", "Tokyo", "JP", ["shopping", "culture", "architecture"], 35.6605, 139.7400, "Modern complex — teamLab Borderless home."),
    place("tokyo-tower", "Tokyo Tower", "東京タワー", "Tokyo", "JP", ["must-see", "view", "icon"], 35.6586, 139.7454, "Classic Tokyo night landmark."),
    place("kabukicho", "Kabukicho", "歌舞伎町", "Tokyo", "JP", ["nightlife", "neighborhood"], 35.6950, 139.7026, "Neon nightlife district in Shinjuku."),
    place("shinjuku-gyoen", "Shinjuku Gyoen", "新宿御苑", "Tokyo", "JP", ["park", "nature", "must-see"], 35.6852, 139.7101, "Spacious national garden — in September last entry is ~16:30 (closes 17:00)."),
    place("tocho", "Tokyo Metropolitan Government Building", "東京都庁", "Tokyo", "JP", ["view", "must-see"], 35.6896, 139.6917, "Free twin-tower observatory in west Shinjuku — great first-night skyline."),
    place("yoyogi", "Yoyogi Park", "代々木公園", "Tokyo", "JP", ["park", "nature"], 35.6711, 139.6949, "Green stretch between Meiji Jingu and Harajuku."),
    place("harmonica", "Harmonica Yokocho", "ハモニカ横丁", "Tokyo", "JP", ["food", "neighborhood"], 35.7033, 139.5792, "Tiny covered alleys of bars and eateries by Kichijoji station."),
    place("nakano-broadway", "Nakano Broadway", "中野ブロードウェイ", "Tokyo", "JP", ["shopping", "culture"], 35.7093, 139.6652, "Otaku shopping maze — figures, vintage, Mandarake."),
    place("kamakura", "Kamakura / Kotoku-in", "鎌倉・高徳院", "Tokyo", "JP", ["must-see", "culture", "temple"], 35.3167, 139.5357, "Great Buddha (Daibutsu)."),
    place("hasedera", "Hasedera Temple", "長谷寺", "Tokyo", "JP", ["temple", "culture"], 35.3128, 139.5333, "Hillside temple with sea views in Kamakura."),
    place("enoshima", "Enoshima", "江の島", "Tokyo", "JP", ["must-see", "nature", "neighborhood"], 35.2997, 139.4808, "Island lanes + seaside sunset via Enoden."),
    place("nikko-toshogu", "Nikko Toshogu Shrine", "日光東照宮", "Tokyo", "JP", ["must-see", "shrine", "culture"], 36.7581, 139.5988, "Ornate UNESCO shrine deep in the forest."),
    place("chuzenji", "Lake Chuzenji", "中禅寺湖", "Tokyo", "JP", ["nature", "must-see"], 36.7390, 139.4470, "Mountain lake above Nikko."),
    place("kegon-falls", "Kegon Falls", "華厳の滝", "Tokyo", "JP", ["nature", "must-see"], 36.7380, 139.4450, "Dramatic waterfall by Lake Chuzenji."),
    place("kasuga", "Kasuga Taisha", "春日大社", "Osaka", "JP", ["shrine", "culture"], 34.6814, 135.8482, "Lantern shrine in Nara."),
]:
    add(p)

def day(id, date, weekday, city, country, hotel_id, title, summary, food, place_ids, transport, tips, timeline, transfer=None):
    d = {
        "id": id, "date": date, "weekday": weekday, "city": city, "country": country,
        "hotelId": hotel_id, "title": title, "summary": summary, "food": food,
        "placeIds": place_ids, "transport": transport, "tips": tips, "timeline": timeline,
    }
    if transfer:
        d["transfer"] = transfer
    return d

def infer_category(title, place_id, note=""):
    text = f"{title} {note}".lower()
    tags = []
    if place_id and place_id in PLACES:
        tags = PLACES[place_id].get("tags") or []
    if place_id and place_id in PLACES and "hotel" in tags:
        return "hotel"
    if any(k in text for k in (
        "flight", "train", "shinkansen", "romancecar", "subway", "bus", "ferry", "transfer",
        "depart", "airport", "ropeway", "monorail", "travel by", "n'ex", "arex", "eizan",
        "hankyu", "kintetsu", "spacia", "enoden", "nozomi", "special rapid", "limousine",
        "yurikamome", "odakyu", "tobu",
    )) or "transport" in tags:
        return "transit"
    if any(k in text for k in ("breakfast", "lunch", "dinner", "food", "market", "crepe", "ramen", "sushi", "café", "cafe", "okonomi", "graze", "snack", "brunch")) or "food" in tags or "market" in tags:
        return "dining"
    if any(k in text for k in ("shop", "souvenir", "arcade street", "ginza", "depachika", "don quijote")) or "shopping" in tags:
        return "shopping"
    if any(k in text for k in ("temple", "shrine", "palace", "garden", "museum", "zen", "sumo", "tea", "hanok", "secret garden")) or "culture" in tags or "temple" in tags or "shrine" in tags:
        return "culture"
    if "park" in tags or any(k in text for k in ("disney", "universal", "fuji-q", "lotte world", "teamlab", "skytree", "tower", "park", "monkey", "cruise", "rope drop")):
        return "attraction"
    if "nightlife" in tags:
        return "dining"
    return "attraction"

def t(time, title, place_id=None, note="", end=None, category=None):
    item = {"time": time, "title": title, "note": note}
    if place_id:
        item["placeId"] = place_id
    if end:
        item["end"] = end
    if category:
        item["category"] = category
    return item


TRANSFERS = {
    "d00": {
        "mode": "flight",
        "label": "Tel Aviv → Seoul (via Addis)",
        "detail": "ET0419 TLV→ADD + ET0672 ADD→ICN (Ethiopian Airlines)",
        "duration": "~24h door-to-door · arrive 27 Aug",
        "fromCity": "Tel Aviv",
        "toCity": "Seoul",
    },
    "d07": {
        "mode": "flight",
        "label": "Seoul → Tokyo",
        "detail": "Air Premia YP7321 · ICN T1 → NRT T2",
        "duration": "~2.5h flight · dep 08:50 · arr 11:20",
        "fromCity": "Seoul",
        "toCity": "Tokyo",
    },
    "d12": {
        "mode": "train",
        "label": "Tokyo → Hakone",
        "detail": "Odakyu Romancecar Shinjuku → Hakone-Yumoto (~¥2,470)",
        "duration": "~80 minutes",
        "fromCity": "Tokyo",
        "toCity": "Hakone",
    },
    "d13": {
        "mode": "bus",
        "label": "Hakone → Gotemba Outlets → Kawaguchiko",
        "detail": "Hakone → Gotemba Premium Outlets (shop) → Fujikyu bus to Kawaguchiko",
        "duration": "shop ~3h + buses",
        "fromCity": "Hakone",
        "toCity": "Kawaguchiko",
    },
    "d15": {
        "mode": "bus",
        "label": "Kawaguchiko → Kyoto (overnight bus)",
        "detail": "Overnight highway bus after Fuji-Q — arrive Kyoto morning 11/9 · no hotel night on 10/9",
        "duration": "~8–10h overnight",
        "fromCity": "Kawaguchiko",
        "toCity": "Kyoto",
    },
    "d20": {
        "mode": "train",
        "label": "Kyoto → Osaka",
        "detail": "Afternoon/evening JR into central Osaka after Kyoto zen morning",
        "duration": "~30–45 minutes",
        "fromCity": "Kyoto",
        "toCity": "Osaka",
    },
    "d25": {
        "mode": "train",
        "label": "Osaka ↔ Kobe day trip",
        "detail": "JR Special Rapid Osaka/Umeda → Sannomiya (~30m), return evening",
        "duration": "~30m each way",
        "fromCity": "Osaka",
        "toCity": "Kobe",
    },
    "d26": {
        "mode": "train",
        "label": "Osaka → Tokyo",
        "detail": "Nozomi Shinkansen (~2.5h)",
        "duration": "~2.5 hours",
        "fromCity": "Osaka",
        "toCity": "Tokyo",
    },
}

DAYS = [
  day("d00", "2026-08-26", "Wednesday", "Seoul", "KR", None,
      "Tel Aviv → Seoul via Addis",
      "Ethiopian Airlines overnight: ET0419 Tel Aviv → Addis Ababa, then ET0672 Addis → Incheon (land Thursday afternoon).",
      "Airport / plane meals; light snack in ADD if time.",
      ["tlv", "add", "icn"],
      ["TLV T3 → ADD → ICN.", "Overnight connection in Addis (~2h45)."],
      [
        "Booked: ET0419 + ET0672.",
        "Arrive Ben Gurion ~3h before departure.",
        "Online check-in / seats on Ethiopian app.",
        "Times are published schedule — confirm on your ticket/boarding pass.",
      ],
      [
        t("12:30", "Arrive Ben Gurion (TLV T3)", "tlv", "Ethiopian Airlines check-in / security."),
        t("15:35", "Travel by Ethiopian Airlines ET0419 · from Tel Aviv to Addis", "tlv", "Flight · ~4h15 · booked.", "19:50"),
        t("19:50", "Land Addis Ababa (ADD)", "add", "Connection — stay airside when possible."),
        t("22:35", "Travel by Ethiopian Airlines ET0672 · from Addis to Seoul", "add", "Overnight flight · ~11h · booked.", "16:00"),
      ]),
  day("d01", "2026-08-27", "Thursday", "Seoul", "KR", "amanti-hotel",
      "Arrival & night bites",
      "Land ICN on ET0672, check in at Amanti Hotel Hongdae, Myeongdong night-food walk, then Hongdae if energy remains.",
      "Myeongdong street food night market.",
      ["icn", "amanti-hotel", "myeongdong", "hongdae"],
      ["ICN → Amanti (~1h AREX/taxi).", "Subway/taxi to Myeongdong."],
      ["Land ~16:00 on ET0672.", "Get T-money / Climate Card."],
      [
        t("16:00", "Land ICN — ET0672", "icn", "Ethiopian from Addis · immigration + bags."),
        t("16:45", "Travel by AREX / taxi · from Incheon to Hongdae", "icn", "AREX Express or taxi · ~50–70 min · no advance booking needed."),
        t("18:00", "Check in — Amanti Hotel Seoul Hongdae", "amanti-hotel", "Hongdae base · 27 Aug–2 Sep."),
        t("19:00", "Myeongdong night food street walk", "myeongdong", "Street food + neon shopping.", "21:30"),
        t("22:00", "Hongdae stroll", "hongdae", "Late snack or drink."),
      ]),
  day("d02", "2026-08-28", "Friday", "Seoul", "KR", "amanti-hotel",
      "Royal heart of Seoul",
      "Gyeongbokgung with the 10:00 changing of the guard + hanbok, Bukchon, Ikseon → Insadong, Gwangjang Market dinner.",
      "Gwangjang Market street-food feast (open ~09:00–22:30).",
      ["gyeongbokgung", "bukchon", "ikseon", "insadong", "gwangjang"],
      ["Hongdae → Gyeongbokgung (~25m).", "Walk Bukchon → Ikseon → Insadong → Gwangjang."],
      ["Arrive early for the 10:00 guard ceremony at Gwanghwamun (~20 min).", "Rent hanbok for free palace entry."],
      [
        t("09:15", "Arrive Gyeongbokgung / hanbok", "gyeongbokgung", "Get set before the ceremony."),
        t("10:00", "Changing of the guard + palace", "gyeongbokgung", "Ceremony at Gwanghwamun (~20 min), then palace grounds.", "12:30"),
        t("13:00", "Bukchon Hanok Village", "bukchon", "Traditional wooden houses on the hill.", "14:15"),
        t("14:30", "Ikseon-dong → Insadong", "ikseon", "Alleys, tea houses, crafts.", "17:00"),
        t("17:30", "Gwangjang Market feast", "gwangjang", "Classic street-food market · open until ~22:30.", "22:00"),
      ]),
  day("d03", "2026-08-29", "Saturday", "Seoul", "KR", "amanti-hotel",
      "Secret Garden, Unni Guide & COEX",
      "Jogyesa and Changdeokgung Secret Garden in the morning, Unni Guide 15:00–16:00 plus treatment, then Bongeunsa and COEX Starfield.",
      "Lunch near the palace / Insadong; dinner near COEX / Gangnam.",
      ["jogyesa", "changdeokgung", "unni-guide", "gangnam", "bongeunsa", "coex"],
      ["Hongdae → Jogyesa / Changdeokgung.", "Subway to Gangnam / Sinnonhyeon for Unni Guide."],
      ["Secret Garden: timed guided tour only — book at ticket.uforus.co.kr (opens 10:00 KST, max 6 days ahead).", "Unni Guide 15:00–16:00."],
      [
        t("09:00", "Jogyesa Temple", "jogyesa", "Buddhist temple near Insadong.", "10:00"),
        t("10:15", "Changdeokgung & Secret Garden", "changdeokgung", "UNESCO palace — pre-book timed tour.", "13:00"),
        t("15:00", "Unni Guide Center — Gangnam", "unni-guide", "Clinic matching / skin analysis / booking help.", "16:00"),
        t("16:15", "Gangnam treatment", "gangnam", "Treatment via Unni Guide / clinic.", "17:30"),
        t("17:45", "Bongeunsa Temple", "bongeunsa", "Temple next to COEX.", "18:30"),
        t("18:45", "COEX & Starfield Library", "coex", "Mall + Starfield Library.", "21:00"),
      ]),
  day("d04", "2026-08-30", "Sunday", "Seoul", "KR", "amanti-hotel",
      "Hongdae facial, Yeonnam & Seongsu",
      "Morning facial near Hongdae, Yeonnam and Mangwon Market, then Seongsu afternoon with Seoul Forest.",
      "Café lunch in Yeonnam / Mangwon; Seongsu snacks.",
      ["hongdae", "yeonnam", "mangwon", "seongsu", "seoul-forest", "seoulistique"],
      ["Hongdae-side morning appointment.", "Walk/subway Yeonnam → Mangwon → Seongsu."],
      ["Book the Hongdae-area facial for the morning."],
      [
        t("10:00", "Facial near Hongdae", "hongdae", "Hongdae-area clinic — book ahead.", "11:45"),
        t("12:15", "Yeonnam-dong stroll", "yeonnam", "Cafés and boutiques by the Gyeongui Line Forest.", "13:30"),
        t("13:45", "Mangwon Market", "mangwon", "Local market snacks next to Yeonnam.", "15:00"),
        t("15:30", "Seongsu-dong", "seongsu", "Cafés, boutiques, and pop-ups.", "17:30"),
        t("17:45", "Seoul Forest", "seoul-forest", "Urban park break.", "19:00"),
        t("19:30", "Dinner near Seongsu / Hongdae", "seongsu", "Dinner nearby."),
      ]),
  day("d05", "2026-08-31", "Monday", "Seoul", "KR", "amanti-hotel",
      "Lotte World + spa night",
      "Full Lotte World day, Seokchon Lake / Lotte Tower Seoul Sky, then jimjilbang and dinner near Jamsil.",
      "Park / Lotte mall snacks; simple dinner near Jamsil after the spa.",
      ["lotte-world", "seokchon", "lotte-tower", "jimjilbang"],
      ["Subway to Jamsil (~40–50m from Hongdae).", "Stay Jamsil-side for spa + dinner."],
      ["Lotte World tickets booked.", "Evening: spa + dinner near Jamsil."],
      [
        t("08:30", "Travel by subway · from Hongdae to Jamsil (Lotte World)", "amanti-hotel", "Seoul Metro · ~40–50 min · no booking."),
        t("10:00", "Lotte World", "lotte-world", "Indoor/outdoor theme park.", "17:00"),
        t("17:15", "Seokchon Lake + Lotte World Tower Seoul Sky", "lotte-tower", "Lake walk + observatory.", "19:00"),
        t("19:30", "Jimjilbang", "jimjilbang", "Korean bathhouse complex.", "21:30"),
        t("21:45", "Dinner near Jamsil", "jimjilbang", "Simple dinner by the park.", "22:45"),
      ]),
  day("d06", "2026-09-01", "Tuesday", "Seoul", "KR", "amanti-hotel",
      "Markets, N Tower sunset & Itaewon",
      "Namdaemun Market morning, Cheonggyecheon walk, Dongdaemun / DDP afternoon, Namsan cable to N Tower sunset, then Itaewon nightlife.",
      "Namdaemun snacks; dinner in Itaewon.",
      ["namdaemun", "cheonggyecheon", "dongdaemun", "namsan-cable", "n-tower", "itaewon"],
      ["Hongdae → Namdaemun.", "Walk Cheonggyecheon toward Dongdaemun.", "Evening to Namsan → Itaewon."],
      ["Book N Tower for sunset; cable tickets at the base.", "Night malls at Dongdaemun: APM, DDP Fashion Mall, Hyundai City Outlets."],
      [
        t("09:30", "Namdaemun Market", "namdaemun", "Classic downtown market — food and shopping.", "11:30"),
        t("11:45", "Cheonggyecheon Stream walk", "cheonggyecheon", "Easy downtown stream toward Dongdaemun.", "13:00"),
        t("13:15", "Dongdaemun / DDP & night malls", "dongdaemun", "DDP + APM / Fashion Mall / outlets.", "16:30"),
        t("17:30", "Namsan cable car", "namsan-cable", "Up Namsan toward N Tower.", "18:00"),
        t("18:05", "N Seoul Tower sunset", "n-tower", "City viewpoint + love locks.", "19:30"),
        t("20:00", "Itaewon / Homo Hill nightlife", "itaewon", "Dinner, bars, LGBTQ+ area.", "23:30"),
      ]),
  day("d07", "2026-09-02", "Wednesday", "Tokyo", "JP", "gracery-shinjuku",
      "Seoul → Tokyo & Shinjuku lights",
      "Early checkout from Amanti, Air Premia YP7321 ICN→NRT, Suica/eSIM, drop bags at Hotel Gracery Shinjuku, go straight to Shinjuku Gyoen (last entry ~16:30), then Shinjuku evening: Godzilla head, free Tocho views, Kabukicho neon, Omoide yakitori and Golden Gai.",
      "Snack/late lunch in or right after Gyoen; yakitori in Omoide Yokocho; drinks in Golden Gai.",
      ["amanti-hotel", "icn", "narita", "gracery-shinjuku", "shinjuku-gyoen", "tocho", "kabukicho", "omoide-yokocho", "golden-gai"],
      ["Amanti → ICN T1 (~1h).", "Air Premia YP7321.", "N'EX / limousine → Hotel Gracery Shinjuku (Kabukicho).", "All evening stops walkable from the hotel."],
      [
        "Air Premia YP7321 · ICN 08:50 → NRT 11:20 (T2). Be at ICN ~06:30–07:00.",
        "Some boards list this route as YP731 — match your ticket.",
        "Set up Suica/Pasmo on arrival.",
        "After bags: go straight to Shinjuku Gyoen (last entry ~16:30, closes 17:00). Lunch after.",
        "Tocho South Observatory is free (closed every other Monday).",
      ],
      [
        t("05:30", "Travel by taxi / AREX · from Hongdae to Incheon T1", "amanti-hotel", "Leave hotel · ~1 hour to ICN · no advance booking."),
        t("06:45", "ICN check-in — Air Premia", "icn", "Terminal 1 · YP7321."),
        t("08:50", "Travel by Air Premia YP7321 · from Seoul to Tokyo", "icn", "Flight · ICN → NRT · ~2h30 · booked.", "11:20"),
        t("11:20", "Land Narita (NRT T2)", "narita", "Immigration + bags."),
        t("12:00", "Travel by N'EX / limousine · from Narita to Shinjuku", "narita", "N'EX ~60–80 min (reserved seats optional) or airport limousine bus · Suica/eSIM on arrival."),
        t("13:00", "Check-in — Hotel Gracery Shinjuku", "gracery-shinjuku", "Leave luggage (shower later) · Godzilla building."),
        t("13:30", "Shinjuku Gyoen — go now", "shinjuku-gyoen", "Straight from the hotel · last entry ~16:30 / closes 17:00 in Sep · snack inside or right after.", "16:30"),
        t("16:45", "Late lunch / snack near the park", "shinjuku", "Ramen / donburi if you only snacked in Gyoen."),
        t("17:30", "Shinjuku metro walk", "shinjuku", "Godzilla head at Toho, Bic Camera / Uniqlo, Kabukicho gate neon."),
        t("18:30", "Tokyo Metropolitan Gov. Building observatory", "tocho", "Free twin-tower skyline — Fuji on clear days.", "19:30"),
        t("19:45", "Kabukicho neon stroll", "kabukicho", "Lights and atmosphere — keep valuables close."),
        t("20:30", "Omoide Yokocho yakitori", "omoide-yokocho", "Memory Lane skewers + beer under the tracks.", "22:00"),
        t("22:15", "Golden Gai nightcap", "golden-gai", "Tiny alley bars — one drink each is enough.", "23:30"),
      ]),
  day("d08", "2026-09-03", "Thursday", "Tokyo", "JP", "gracery-shinjuku",
      "West Tokyo: Meiji, Harajuku, Omotesando & Shibuya Sky",
      "Full west-Tokyo loop: Meiji Jingu and Yoyogi, Takeshita + Cat Street, Omotesando lunch, Shibuya Crossing / Hachiko / Center-gai, timed Shibuya Sky sunset, then dinner in Shibuya.",
      "Crepes or cafe lunch on Omotesando; dinner in Shibuya (Nonbei Yokocho or Center-gai).",
      ["meiji-jingu", "yoyogi", "takeshita", "cat-street", "omotesando", "shibuya-crossing", "shibuya-sky"],
      ["Walk Meiji → Harajuku → Omotesando → Shibuya (or one Yamanote hop)."],
      [
        "Book Shibuya Sky sunset slot ~4 weeks ahead.",
        "Passport for tax-free shopping.",
        "Meiji Jingu opens early — arrive before tour buses if you can.",
      ],
      [
        t("08:30", "Meiji Jingu", "meiji-jingu", "Forest shrine — quiet path from Harajuku station.", "09:45"),
        t("09:50", "Yoyogi Park edge", "yoyogi", "Short green stroll toward Takeshita.", "10:15"),
        t("10:20", "Takeshita Street", "takeshita", "Crepes, youth fashion, souvenir stalls.", "11:20"),
        t("11:25", "Cat Street", "cat-street", "Stylish side street linking Harajuku to Omotesando.", "12:15"),
        t("12:20", "Omotesando lunch & boutiques", "omotesando", "Tree-lined avenue — cafe or light lunch + window shopping.", "14:00"),
        t("14:15", "Walk to Shibuya", "shibuya-crossing", "Continue south along Omotesando / Meiji-dori."),
        t("14:30", "Hachiko & Shibuya Crossing", "shibuya-crossing", "Statue photos, scramble crossing, Starbucks scramble view."),
        t("15:00", "Center-gai & Shibuya shopping", "shibuya-crossing", "109, Tower Records, Loft, Mag’s Park rooftop if energy.", "16:45"),
        t("17:00", "Shibuya Sky sunset", "shibuya-sky", "Timed ticket — arrive 15–20 min early.", "19:00"),
        t("19:30", "Dinner & drinks in Shibuya", "shibuya-crossing", "Nonbei Yokocho izakaya alley or Center-gai dinner."),
      ]),
  day("d09", "2026-09-04", "Friday", "Tokyo", "JP", "gracery-shinjuku",
      "Tsukiji, teamLab Planets, Odaiba & Ginza",
      "Weekday plan for fewer crowds: Tsukiji Outer Market sushi/fish breakfast, timed teamLab Planets in Toyosu, Odaiba Gundam + waterfront, then a long Ginza evening of depachika, flagships and dinner.",
      "Tsukiji sushi and fish; Ginza depachika snacks + sushi, tonkatsu, or yakiniku dinner.",
      ["tsukiji", "teamlab-planets", "odaiba", "ginza"],
      ["Tsukiji early.", "Yurikamome/Rinkai Toyosu → Odaiba.", "Yurikamome or subway back toward Ginza."],
      [
        "Timed tickets for teamLab Planets — book a weekday slot (avoid Sat/Sun sell-outs).",
        "Some rooms have water — wear shorts you can roll up / bring a small towel.",
        "Ginza: Mitsukoshi/Ginza Six depachika, Uniqlo Tokyo flagship, Itoya stationery.",
      ],
      [
        t("07:30", "Travel by subway / Yurikamome · toward Tsukiji", "tsukiji", "Local metro · ~25–35 min from Shinjuku · no booking."),
        t("07:45", "Tsukiji Outer Market breakfast", "tsukiji", "Sushi, nigiri, fresh fish, and tamago.", "10:00"),
        t("10:30", "Travel by subway · from Tsukiji to Toyosu (teamLab)", "teamlab-planets", "Short metro hop · ~10–15 min · timed tickets already needed for teamLab."),
        t("11:00", "teamLab Planets Tokyo", "teamlab-planets", "Water-based digital art in Toyosu — weekday timed tickets.", "14:00"),
        t("14:15", "Travel by Yurikamome / Rinkai · from Toyosu to Odaiba", "odaiba", "Local train · ~10–15 min · no booking."),
        t("14:30", "Odaiba waterfront & Gundam", "odaiba", "DiverCity Gundam, bay promenade, Rainbow Bridge views.", "17:00"),
        t("17:15", "Travel by Yurikamome / subway · from Odaiba to Ginza", "ginza", "Local train · ~20–30 min · no booking."),
        t("17:30", "Ginza arrival — depachika & flagships", "ginza", "Basement food halls + Uniqlo / Itoya / Ginza Six.", "19:30"),
        t("19:45", "Ginza dinner", "ginza", "Sushi, tonkatsu, or yakiniku."),
      ]),
  day("d10", "2026-09-05", "Saturday", "Tokyo", "JP", "gracery-shinjuku",
      "Asakusa, Kappabashi, Skytree & Akihabara",
      "Old-east Tokyo day: early Senso-ji & Nakamise, Kappabashi kitchen street, Sumida riverside to Skytree/Solamachi, then Akihabara arcades and anime floors ending with izakaya.",
      "Nakamise snacks mid-morning; Solamachi or Ameyoko-style grazing; izakaya in Akihabara / Kanda.",
      ["asakusa", "kappabashi", "skytree", "ameyoko", "akihabara"],
      ["Subway to Asakusa.", "Walk Asakusa → Kappabashi → Mizumachi → Skytree.", "JR/subway to Akihabara (or hop via Ueno/Ameyoko)."],
      [
        "Senso-ji before 8:30 if you want fewer crowds (Saturday gets busy fast).",
        "Kappabashi: plastic food samples + kitchen knives (check luggage rules).",
        "Skytree ticket optional — Solamachi mall + exterior views are free.",
        "Optional detour: Ueno Park + Ameyoko before Akihabara if you want street-food market energy.",
      ],
      [
        t("07:30", "Travel by subway · from Shinjuku to Asakusa", "asakusa", "Tokyo Metro / Toei · ~25–35 min · no booking."),
        t("07:45", "Senso-ji & Kaminarimon", "asakusa", "Temple grounds + Thunder Gate photos before tour groups peak.", "09:15"),
        t("09:15", "Nakamise shopping street", "asakusa", "Ningyo-yaki, senbei, small souvenirs.", "10:15"),
        t("10:30", "Kappabashi kitchen town", "kappabashi", "Cookware, knives, plastic food displays — ~10–15 min walk.", "11:45"),
        t("12:00", "Sumida riverside / Tokyo Mizumachi", "skytree", "Easy walk toward Skytree — lunch options along the way.", "13:00"),
        t("13:00", "Tokyo Skytree & Solamachi", "skytree", "Tower exterior + mall floors; book deck only if you want the view ticket.", "15:00"),
        t("15:20", "Optional Ameyoko snack stop", "ameyoko", "If energy/hunger: street-food market under the tracks near Ueno.", "16:00"),
        t("16:00", "Travel by JR / subway · toward Akihabara", "akihabara", "Short hop via Ueno or direct · ~10–15 min · no booking."),
        t("16:15", "Akihabara Electric Town", "akihabara", "GiGO/TAITO arcades, Animate, Radio Kaikan, multi-floor anime shops.", "19:00"),
        t("19:15", "Izakaya dinner — Akihabara or Kanda", "akihabara", "Casual dinner + one more night in east Tokyo."),
      ]),
  day("d11", "2026-09-06", "Sunday", "Tokyo", "JP", "gracery-shinjuku",
      "Kichijoji, Shimokitazawa & night Street Kart",
      "Easy west-Tokyo Sunday: Inokashira and Harmonica lunch in Kichijoji, vintage Shimokitazawa afternoon, early dinner near Shibuya, then night Street Kart through neon (~19:00).",
      "Lunch in Harmonica Yokocho / Kichijoji; early dinner near Shibuya (ramen, tonkatsu, sushi, or yakiniku); light snack after kart if needed.",
      ["inokashira", "kichijoji", "harmonica", "shimokitazawa", "street-kart"],
      [
        "Chuo/Sobu to Kichijoji; Inokashira Line or Odakyu to Shimokita.",
        "Evening: head to Street Kart shop (often Shibuya) — arrive 30 min before the slot.",
      ],
      [
        "Book a night Street Kart slot ~19:00 — evening tours run until ~22:00.",
        "Physical International Driving Permit required — photocopies not accepted.",
        "Confirm the meetup shop the night before; Shibuya works well for neon.",
        "Keep the day light so the kart is the evening highlight.",
      ],
      [
        t("10:00", "Travel by JR Chuo Line · from Shinjuku to Kichijoji", "kichijoji", "Chuo Rapid · ~20–25 min · no booking."),
        t("10:30", "Inokashira Park", "inokashira", "Lake loop, boats if you want, stroll toward Kichijoji.", "12:00"),
        t("12:15", "Kichijoji & Harmonica Yokocho lunch", "harmonica", "Covered alley eats + neighborhood shopping — meat/egg/noodle options easy.", "14:00"),
        t("14:15", "Travel by Keio Inokashira / Odakyu · from Kichijoji to Shimokitazawa", "shimokitazawa", "~15–25 min · no booking."),
        t("14:30", "Shimokitazawa vintage & cafés", "shimokitazawa", "Thrift floors, record shops, indie cafés — unhurried afternoon.", "17:30"),
        t("17:45", "Early dinner near Shibuya", None, "Ramen, tonkatsu, sushi, or yakiniku before kart.", "18:45"),
        t("18:30", "Arrive Street Kart shop", "street-kart", "Be there 30 min early · IDP + passport."),
        t("19:00", "Night Street Kart Tokyo", "street-kart", "Neon streets at night.", "21:00"),
        t("21:15", "Travel by train · back to Shinjuku hotel", "gracery-shinjuku", "Yamanote / Odakyu · ~15–25 min · no booking."),
      ]),
  day("d12", "2026-09-07", "Monday", "Hakone", "JP", "tsukino-yado-sara",
      "Romancecar & Tsukino Yado Sara",
      "Morning Takkyubin of big bags Tokyo→Kawaguchiko hotel, Romancecar (try Observation Car) into Hakone-Yumoto, Owakudani, then check-in at Tsukino Yado Sara for onsen + kaiseki.",
      "Black eggs; kaiseki dinner at Tsukino Yado Sara.",
      ["owakudani", "tsukino-yado-sara"],
      ["Odakyu Romancecar Shinjuku → Hakone-Yumoto (~80m, ~¥2,470).", "Ropeway to Owakudani.", "Sara is ~7–10 min taxi/walk from Hakone-Yumoto Station."],
      [
        "Send large suitcases Tokyo→HOTEL MYSTAYS Fuji Onsen Resort via Takkyubin; travel Hakone/Fuji with backpacks only.",
        "Book Romancecar ~1 month ahead — request front Observation Car seats.",
        "Tsukino Yado Sara booked · check-in from 15:00 · all rooms have open-air baths.",
        "Onsen etiquette at the ryokan.",
      ],
      [
        t("08:00", "Takkyubin drop at Hotel Gracery", "gracery-shinjuku", "Forward large bags to HOTEL MYSTAYS Fuji Onsen Resort."),
        t("09:00", "Travel by Odakyu Romancecar · from Shinjuku to Hakone-Yumoto", None, "Limited express · reserved seats · ~80 min · book ~1 month ahead · request Observation Car.", "10:40"),
        t("11:00", "Arrive Hakone-Yumoto", None, "Leave bags / plan Owakudani before check-in opens at 15:00."),
        t("12:30", "Owakudani volcanic valley", "owakudani", "Black eggs + Fuji views.", "16:00"),
        t("17:00", "Check-in — Tsukino Yado Sara", "tsukino-yado-sara", "Hakone-Yumoto · private open-air bath rooms · onsen."),
        t("19:00", "Kaiseki dinner at Sara", "tsukino-yado-sara", "Multi-course dinner at the ryokan."),
      ]),
  day("d13", "2026-09-08", "Tuesday", "Kawaguchiko", "JP", "mystays-fuji-onsen",
      "Sunrise torii, pirate ship, Gotemba & calm Kawaguchiko",
      "Sunrise at Hakone Shrine floating torii (Fuji if clear), Lake Ashi pirate ship, afternoon Gotemba Premium Outlets shopping, then check-in at HOTEL MYSTAYS Fuji Onsen Resort for a calm evening.",
      "Outlet lunch at Gotemba; calm dinner near the hotel / lake.",
      ["hakone-shrine", "lake-ashi", "gotemba-outlets", "mystays-fuji-onsen"],
      [
        "Early transfer to Motohakone for Hakone Shrine sunrise.",
        "Lake Ashi pirate ship, then afternoon bus to Gotemba Premium Outlets and on to Kawaguchiko.",
      ],
      [
        "Sunrise ~05:30 in early Sep — leave the ryokan with warm layers.",
        "Gotemba open 10:00–20:00 — aim for a midday/afternoon shop window (~3h).",
        "Collect Tokyo→MYSTAYS Takkyubin bags at the hotel if they arrived.",
        "Keep the evening light — big Fuji day tomorrow.",
      ],
      [
        t("05:00", "Travel by taxi / bus · from Sara to Hakone Shrine (Motohakone)", "tsukino-yado-sara", "Early transfer · ~20–30 min · no booking."),
        t("05:30", "Hakone Shrine floating torii at sunrise", "hakone-shrine", "Torii + lake · Fuji if the sky is clear.", "07:15"),
        t("07:45", "Lake Ashi pirate ship", "lake-ashi", "Short sightseeing cruise while the morning is clear.", "09:00"),
        t("09:30", "Travel by bus · from Hakone to Gotemba Premium Outlets", None, "From Togendai / Hakone-Yumoto · ~30–50 min · no booking."),
        t("12:00", "Gotemba Premium Outlets shopping", "gotemba-outlets", "Dedicated outlet time — brands + Fuji views.", "15:00"),
        t("15:15", "Travel by Fujikyu bus / limited-express GL · from Gotemba to Kawaguchiko", "gotemba-outlets", "~60–70 min · GL limited express optional if available.", "17:00"),
        t("17:15", "Check-in — HOTEL MYSTAYS Fuji Onsen Resort", "mystays-fuji-onsen", "Fujiyoshida · onsen · collect forwarded bags."),
        t("19:00", "Calm dinner near the hotel", "mystays-fuji-onsen", "Early-ish night · rest for Chureito sunrise."),
      ]),
  day("d14", "2026-09-09", "Wednesday", "Kawaguchiko", "JP", "mystays-fuji-onsen",
      "Fuji sunrise, Lawson & sightseeing loop",
      "Sunrise at Chureito Pagoda, the Lawson Fuji photo stop, then Kawaguchiko sightseeing buses and north-shore viewpoints. Sleep early at MYSTAYS.",
      "Café / lakeside lunch; early dinner.",
      ["chureito", "fuji-lawson", "fuji-view-bus", "oishi-park", "mystays-fuji-onsen"],
      [
        "Dawn taxi/bus to Chureito (Arakurayama) — close to the hotel.",
        "Kawaguchiko Sightseeing Bus loops (red/green/blue) between viewpoints.",
        "Optional mountain bus toward Fuji if seats/weather allow.",
      ],
      [
        "Chureito stairs in the dark — headlamp helps.",
        "Buy a 1- or 2-day sightseeing bus pass at Kawaguchiko Station.",
        "Sleep early tonight — Fuji-Q opens tomorrow morning (hotel is near Fujikyu Highland Station).",
      ],
      [
        t("05:00", "Chureito Pagoda sunrise", "chureito", "Iconic Fuji + pagoda at first light.", "07:00"),
        t("07:30", "Lawson Kawaguchiko Fuji photo", "fuji-lawson", "The famous convenience-store Fuji shot."),
        t("08:30", "Breakfast near the station", None, "Fuel before the loop."),
        t("09:30", "Kawaguchiko sightseeing bus loop", "fuji-view-bus", "Tourist buses to classic Fuji photo stops.", "12:30"),
        t("13:00", "Oishi Park & north-shore views", "oishi-park", "Flower path + lake & Fuji.", "15:00"),
        t("15:30", "More viewpoint hopping / optional Fuji mountain bus", "fuji-view-bus", "Extra photo stops if energy remains.", "17:30"),
        t("18:30", "Early dinner & early night at MYSTAYS", "mystays-fuji-onsen", "Rest for an early Fuji-Q start tomorrow."),
      ]),
  day("d15", "2026-09-10", "Thursday", "Kawaguchiko", "JP", None,
      "Fuji-Q Highland & overnight bus to Kyoto",
      "Checkout MYSTAYS, Fuji-Q from opening (hotel is next door), send bags ahead to KABIN Koji, then overnight highway bus to Kyoto (no hotel night tonight).",
      "Park food; light snack before the overnight bus.",
      ["fuji-q", "mystays-fuji-onsen"],
      [
        "Arrive Fuji-Q for opening (~09:00) — short hop from MYSTAYS.",
        "Evening overnight bus Kawaguchiko / Fujikyu area → Kyoto.",
      ],
      [
        "Wake ~08:00 for park opening.",
        "Do-Dodonpa / Takabisha are the headline coasters.",
        "Same-day Takkyubin: send bags from MYSTAYS to KABIN Koji.",
        "Overnight bus is reserved seats — sleep on the bus; KABIN Koji from 11/9.",
      ],
      [
        t("08:00", "Checkout MYSTAYS & bag prep", "mystays-fuji-onsen", "Bags ready for Takkyubin to KABIN Koji."),
        t("08:30", "Depart for Fuji-Q Highland", "fuji-q", "Short walk / hop from the hotel."),
        t("09:00", "Fuji-Q Highland", "fuji-q", "Full theme-park day from opening.", "17:30"),
        t("17:45", "Send bags to KABIN Koji", "mystays-fuji-onsen", "Takkyubin / hotel luggage service — arrive Kyoto ahead of you."),
        t("19:00", "Light dinner near the bus stop", None),
        t("21:30", "Travel by overnight highway bus · from Kawaguchiko to Kyoto", None, "Reserved seats · book ahead · ~8–10h · arrive Kyoto morning 11/9 · no hotel tonight."),
      ]),
  day("d16", "2026-09-11", "Friday", "Kyoto", "JP", "kabin-koji",
      "Arrive Kyoto, Gion & riverside alleys",
      "Morning arrival on the overnight bus, check in at KABIN Koji and bag pickup, then rest and an easy Gion dusk stroll with Pontocho riverside dinner.",
      "Pontocho riverside dinner along the Kamogawa.",
      ["kabin-koji", "gion", "pontocho"],
      ["Overnight bus arrives Kyoto morning.", "Walk/taxi to KABIN Koji (Kawaramachi) · easy evening in Higashiyama / Pontocho."],
      [
        "KABIN Koji nights: 11/9 evening → 15/9 evening · 152 Sujiyacho, Shimogyo.",
        "Collect Takkyubin bags at the hotel if they arrive first.",
        "Keep the day light after the overnight bus.",
        "Respectful photos in Gion.",
      ],
      [
        t("06:30", "Arrive Kyoto (overnight bus)", None, "Stretch, coffee, shower priority."),
        t("09:00", "Check in — KABIN Koji", "kabin-koji", "Kawaramachi base · collect forwarded bags when ready."),
        t("12:00", "Easy lunch & rest", None, "Nap if needed after the bus."),
        t("17:30", "Gion dusk stroll", "gion", "Geisha district lanes.", "19:00"),
        t("19:15", "Pontocho riverside dinner", "pontocho", "Kamogawa atmosphere.", "21:30"),
      ]),
  day("d17", "2026-09-12", "Saturday", "Kyoto", "JP", "kabin-koji",
      "Fushimi Inari, Uji matcha & Nishiki",
      "Sunrise Fushimi Inari, then Uji for Byodo-in, matcha Omotesando and the river, then Kiyomizu / Sannenzaka and Nishiki Market.",
      "Matcha snacks in Uji; Nishiki graze later.",
      ["fushimi-inari", "byodoin", "uji-omotesando", "uji-river", "kiyomizu", "sannenzaka", "nishiki"],
      ["Early Keihan/JR to Fushimi.", "Keihan/JR Fushimi → Uji (~20–30m).", "Return to Higashiyama, then Nishiki."],
      ["Higher Fushimi paths are quieter.", "Byodo-in Phoenix Hall is the temple on the ¥10 coin."],
      [
        t("06:00", "Travel by Keihan / JR · from central Kyoto to Fushimi-Inari", "fushimi-inari", "~10–15 min · no booking · early train for sunrise."),
        t("06:30", "Fushimi Inari Taisha", "fushimi-inari", "Sunrise torii hike.", "09:45"),
        t("10:00", "Travel by JR / Keihan · from Fushimi to Uji", "byodoin", "~20–30 min · no booking."),
        t("10:30", "Byodo-in", "byodoin", "Phoenix Hall — iconic Uji temple.", "12:00"),
        t("12:15", "Uji Omotesando matcha street", "uji-omotesando", "Tea shops, matcha soft-serve and sweets.", "14:00"),
        t("14:00", "Uji River walk", "uji-river", "Bridges and riverside stroll.", "15:00"),
        t("15:30", "Travel by JR / Keihan · from Uji to Higashiyama (Kiyomizu)", "kiyomizu", "~30–40 min · no booking."),
        t("16:15", "Kiyomizu-dera", "kiyomizu", "Wooden stage temple.", "17:30"),
        t("17:35", "Sannenzaka & Ninenzaka", "sannenzaka", "Preserved stone streets.", "18:15"),
        t("18:30", "Nishiki Market", "nishiki", "Street-food graze — Kyoto’s kitchen.", "19:30"),
        t("19:45", "Dinner", None, "Near Nishiki / Kawaramachi."),
      ]),
  day("d18", "2026-09-13", "Sunday", "Kyoto", "JP", "kabin-koji",
      "Arashiyama bamboo & monkey park",
      "West Kyoto day: stone statues, bamboo grove, Tenryu-ji, the bridge, and Monkey Park views.",
      "Lunch near Togetsukyo Bridge.",
      ["otagi", "adashino", "saga-toriimoto", "bamboo", "tenryuji", "kimono-forest", "togetsukyo", "monkey-park"],
      ["Train/bus toward Saga-Arashiyama; walk the west Kyoto chain."],
      ["Bamboo grove in the morning.", "Monkey park hike."],
      [
        t("07:30", "Travel by JR / Randen · from central Kyoto to Saga-Arashiyama", "bamboo", "~20–30 min · no booking."),
        t("08:00", "Otagi Nenbutsu-ji", "otagi", "1,200 stone rakan statues.", "09:15"),
        t("09:30", "Adashino Nenbutsu-ji", "adashino", "Quiet stone cemetery with bamboo."),
        t("10:30", "Saga Toriimoto Street", "saga-toriimoto", "Preserved thatched-roof lane."),
        t("11:15", "Bamboo Grove & Tenryu-ji", "bamboo", "Iconic path + Zen garden.", "13:00"),
        t("13:15", "Kimono Forest & lunch", "kimono-forest", "Near Arashiyama Station / bridge.", "14:45"),
        t("15:00", "Togetsukyo Bridge", "togetsukyo", "Classic Arashiyama river bridge."),
        t("15:30", "Iwatayama Monkey Park", "monkey-park", "Panoramic city views.", "17:30"),
        t("18:15", "Travel by train · from Arashiyama to central Kyoto (Kawaramachi)", None, "JR / Randen · ~20–30 min · no booking."),
        t("19:00", "Central Kyoto dinner", None, "Kawaramachi / Pontocho area."),
      ]),
  day("d19", "2026-09-14", "Monday", "Kyoto", "JP", "kabin-koji",
      "Kibune nagashi somen + Kurama, then Biovortex",
      "Kibune-first weekday for walk-in nagashi somen at Hirobun, then forest trek to Kurama-dera, return to Kyoto for booked teamLab Biovortex 18:00–18:30.",
      "Light nagashi somen lunch at Hirobun (~¥2,000); proper dinner after Biovortex.",
      ["kifune", "hirobun", "kurama-dera", "teamlab-biovortex"],
      [
        "Demachiyanagi → Eizan to Kibuneguchi first (~30m), then Kyoto Bus / walk up to Kibune.",
        "After somen: trek Kibune → Kurama (~45m); train down from Kurama.",
        "teamLab Biovortex ~7 min from Kyoto Station Hachijo East — be there before 18:00.",
      ],
      [
        "Nagashi somen is walk-in only · cash ~¥2,000 · aim for Hirobun ~09:45–10:00 for the numbered fan.",
        "Monday helps — weekend waits can exceed 3h. Rain at 10:00 cancels somen → lunch in Kibune or return to Kyoto.",
        "Biovortex booked 18:00–18:30 · allow 2–3h inside · save QR offline.",
      ],
      [
        t("07:45", "Travel by Eizan · from Demachiyanagi to Kibuneguchi", "kifune", "Eizan Electric Railway · ~30 min · no booking · Kibune first for the somen queue."),
        t("08:30", "Travel by Kyoto Bus / walk · from Kibuneguchi to Kibune village", "kifune", "Bus ~10 min or walk uphill ~30–40 min · no booking."),
        t("09:45", "Hirobun — get in line", "hirobun", "Walk-in · pay cash ~¥2,000 · numbered fan when reception opens (~10:00).", "10:15"),
        t("10:15", "Kifune Shrine while waiting", "kifune", "Lantern stairs · Yui shrine is next door · come back when called.", "11:00"),
        t("11:00", "Nagashi somen at Hirobun", "hirobun", "Catch noodles in the bamboo flume on the river deck.", "12:00"),
        t("12:15", "Snack if still hungry", None, "Somen is light — drink/snack by the river before the trek."),
        t("12:45", "Forest trek to Kurama", None, "~45 minutes through cedar — reverse of the usual route.", "13:30"),
        t("13:45", "Kurama-dera Temple", "kurama-dera", "Mountain temple at the end of the trek.", "15:00"),
        t("15:15", "Travel by Eizan · from Kurama to Kyoto", "kabin-koji", "Eizan down from Kurama · ~30 min · no booking · then hotel buffer before Biovortex."),
        t("17:30", "Leave for Biovortex", "teamlab-biovortex", "Hachijo East · ~7 min walk from Kyoto Station."),
        t("18:00", "teamLab Biovortex Kyoto", "teamlab-biovortex", "Booked entry window 18:00–18:30 · allow 2–3h inside.", "21:00"),
        t("21:15", "Dinner near Kyoto Station / Kawaramachi", None, "Full dinner after a light somen lunch."),
      ]),
  day("d20", "2026-09-15", "Tuesday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Kyoto zen morning → Osaka night",
      "Morning Ginkaku-ji / Philosopher’s Path / Nanzen-ji and Kinkaku-ji, then evening train to Osaka for Apartment Hotel 11 Shinsaibashi 2 check-in and Dotonbori.",
      "Lunch near Nanzen-ji; takoyaki & okonomiyaki in Dotonbori.",
      ["kabin-koji", "ginkakuji", "philosophers-path", "nanzenji", "kinkakuji", "apt-hotel-11-shinsaibashi", "dotonbori", "hozenji"],
      [
        "Morning east/west Kyoto zen loop.",
        "Afternoon/evening JR Kyoto → Osaka (~30–45m).",
      ],
      [
        "Checkout KABIN Koji for the evening move to Osaka (Apartment Hotel 11 · nights 15–21/9).",
        "USJ is tomorrow (16/9) — keep the evening moderate.",
      ],
      [
        t("08:00", "Ginkaku-ji (Silver Pavilion)", "ginkakuji", "Morning gardens.", "09:30"),
        t("09:45", "Philosopher’s Path", "philosophers-path", "Peaceful canal walk.", "11:00"),
        t("11:15", "Nanzen-ji & lunch", "nanzenji", "Temple + aqueduct.", "13:00"),
        t("13:45", "Kinkaku-ji", "kinkakuji", "Golden Pavilion before leaving Kyoto.", "15:15"),
        t("16:00", "Travel by JR Special Rapid · from Kyoto to Osaka", None, "JR Special Rapid · ~30–45 min · toward Shinsaibashi / Namba · no reserved seat needed."),
        t("17:30", "Check in — Apartment Hotel 11 Shinsaibashi 2", "apt-hotel-11-shinsaibashi", "Higashi-Shinsaibashi · near Dotonbori through 21/9."),
        t("19:30", "Dotonbori food crawl", "dotonbori", "Glico sign + street food."),
        t("21:00", "Hozenji Yokocho alley", "hozenji", "Mossy lantern lane near Dotonbori."),
      ]),
  day("d21", "2026-09-16", "Wednesday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Universal Studios Japan — Express Pass day",
      "USJ timed to our Express Pass 7 (Minecart & Selection): Super Nintendo World morning windows, Harry Potter express, Choice A/B rides, then Flight of the Hippogriff at 18:30.",
      "Park snacks / Toadette Café if timing works; light dinner in park or Namba after.",
      ["usj"],
      ["Subway to Universal City (~25–35m). Leave by ~07:30 to clear security before the 09:20 SNW window."],
      [
        "Voucher: Universal Express Pass 7～Minecart & Selection～ · 16/9 · still need Studio Pass (park entry).",
        "Timed: SNW 09:20–10:20 · Mario Kart 09:20–09:50 · Yoshi 09:50–10:20 · Mine Cart 10:20–10:50 · Hippogriff 18:30–19:00.",
        "Anytime express: Harry Potter and the Forbidden Journey.",
        "Choice A (pick one): Jurassic Park — The Ride OR JAWS.",
        "Choice B (pick one): Despicable Me: Minion Mayhem OR The Flying Dinosaur.",
        "Save QR screens offline — park Wi‑Fi can drop.",
      ],
      [
        t("07:30", "Travel by subway / JR · from Shinsaibashi to Universal City", "apt-hotel-11-shinsaibashi", "~25–35 min · no booking · leave early for security before the 09:20 SNW window."),
        t("08:45", "Park entry & head to Super Nintendo World", "usj", "Studio Pass + show Express QR at SNW."),
        t("09:20", "Mario Kart: Koopa's Challenge", "usj", "Express window 09:20–09:50.", "09:50"),
        t("09:50", "Yoshi's Adventure", "usj", "Express window 09:50–10:20.", "10:20"),
        t("10:20", "Mine Cart Madness", "usj", "Express window 10:20–10:50.", "10:50"),
        t("11:15", "Harry Potter and the Forbidden Journey", "usj", "Express anytime today — Hogsmeade after SNW.", "12:15"),
        t("12:30", "Lunch in park", "usj", "Recover before Choice A/B."),
        t("13:30", "Choice B — Minion Mayhem or The Flying Dinosaur", "usj", "Pick one ☆ on the voucher.", "14:45"),
        t("15:00", "Choice A — Jurassic Park The Ride or JAWS", "usj", "Pick one ☆ on the voucher.", "16:15"),
        t("16:30", "Free time — photos, shops, shows", "usj", "Buffer before the evening Hippogriff slot.", "18:15"),
        t("18:30", "Flight of the Hippogriff", "usj", "Express window 18:30–19:00.", "19:00"),
        t("19:15", "Evening park / exit", "usj", "One more snack or souvenir if energy remains.", "21:00"),
        t("21:20", "Travel by subway / JR · from Universal City to Shinsaibashi hotel", "apt-hotel-11-shinsaibashi", "~25–35 min · no booking."),
      ]),
  day("d22", "2026-09-17", "Thursday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Nara deer park day trip",
      "Day trip to Nara for deer park, Todai-ji and Kasuga Taisha; evening back in Shinsaibashi and Amerikamura.",
      "Nara lunch; Amerikamura dinner.",
      ["nara-park", "kasuga", "shinsaibashi", "amerikamura"],
      ["Kintetsu/JR to Nara (~45m).", "Return for evening shopping."],
      ["Guard bags around deer.", "Deer crackers available on site."],
      [
        t("08:30", "Travel by Kintetsu (or JR) · from Osaka to Nara", "nara-park", "Kintetsu Ltd. Exp. preferred · ~35–45 min · reserved seat optional."),
        t("09:30", "Nara Park & deer", "nara-park", "Todai-ji Great Buddha.", "13:00"),
        t("13:15", "Kasuga Taisha", "kasuga", "Lantern shrine.", "14:30"),
        t("15:00", "Travel by Kintetsu / JR · from Nara to Osaka (Shinsaibashi)", None, "~35–45 min · reserved seat optional."),
        t("17:30", "Shinsaibashi shopping", "shinsaibashi", "Main arcade near the hotel."),
        t("19:30", "Dinner in Amerikamura", "amerikamura", "Youth fashion streets + easy dinner."),
      ]),
  day("d23", "2026-09-18", "Friday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Osaka markets & Cup Noodle day",
      "Local Osaka day: Instant Ramen Museum in Ikeda, Kuromon Market, Tenjinbashi arcade, evening around Hozenji and Dotonbori.",
      "Kuromon snacks; dinner near Dotonbori.",
      ["ramen-museum", "kuromon", "tenjinbashi", "hozenji"],
      ["Hankyu to Ikeda for the museum (~30–40m).", "Metro / walk for markets and arcade."],
      ["Ramen Museum: book a make-your-own Cup Noodle slot if you want one.", "Easy recovery day between Nara and castle/Umeda."],
      [
        t("09:00", "Travel by Hankyu · from Osaka to Ikeda (Cup Noodle Museum)", "ramen-museum", "Hankyu · ~30–40 min · no booking."),
        t("09:30", "Instant Ramen Museum (Ikeda)", "ramen-museum", "Make-your-own Cup Noodle if booked; museum walk.", "12:00"),
        t("12:30", "Travel by Hankyu · from Ikeda to Osaka / Namba", "kuromon", "~30–40 min · no booking · then walk/metro to Kuromon."),
        t("13:00", "Kuromon Market lunch", "kuromon", "Osaka’s kitchen — fresh stalls and quick bites.", "15:00"),
        t("15:30", "Tenjinbashi-suji arcade", "tenjinbashi", "Long covered shopping street.", "17:30"),
        t("18:30", "Hozenji Yokocho & Dotonbori evening", "hozenji", "Mossy alley + neon stroll / dinner.", "21:00"),
      ]),
  day("d24", "2026-09-19", "Saturday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Castle, Shinsekai, Umeda & sky sunset",
      "Osaka Castle and Shinsekai by day, then Umeda shopping and sunset at Umeda Sky Building.",
      "Shinsekai snacks; dinner near Umeda / Namba.",
      ["osaka-castle", "shinsekai", "umeda-sky", "dotonbori"],
      ["Subway to Osaka Castle · Shinsekai · Umeda."],
      ["Umeda Sky sunset slot if you want the deck timed."],
      [
        t("10:00", "Osaka Castle Park", "osaka-castle", "Castle grounds stroll.", "12:30"),
        t("13:00", "Shinsekai & Tsutenkaku", "shinsekai", "Retro Osaka vibes + lunch.", "15:30"),
        t("16:00", "Umeda shopping", "umeda-sky", "Hep Five, Grand Front Osaka.", "18:00"),
        t("18:15", "Umeda Sky Building sunset", "umeda-sky", "Floating Garden observatory.", "19:45"),
        t("20:30", "Drinks in Namba / Nakazakicho", "dotonbori", "Nightcap near the hotel area."),
      ]),
  day("d25", "2026-09-20", "Sunday", "Osaka", "JP", "apt-hotel-11-shinsaibashi",
      "Kobe day trip — ropeway, Kitano & harbor",
      "Day trip to Kobe: Nunobiki ropeway & herb garden, Kitano Ijinkan hillside, Nankinmachi snacks, Meriken Park / Harborland, then Kobe beef dinner and return to Osaka.",
      "Nankinmachi snacks; Kobe beef dinner before heading back.",
      ["nunobiki", "kitano-ijinkan", "nankinmachi", "meriken-park"],
      [
        "JR Special Rapid Osaka / Umeda → Sannomiya (~30m).",
        "Local walk / City Loop bus between Kitano, Motomachi and the harbor.",
        "Evening JR back to Osaka.",
      ],
      [
        "Check Nunobiki ropeway last cars for the season.",
        "Sleep in Osaka tonight — checkout tomorrow for Tokyo.",
      ],
      [
        t("08:30", "Travel by JR Special Rapid · from Osaka/Umeda to Kobe-Sannomiya", None, "JR Special Rapid · ~30 min · no booking."),
        t("09:30", "Nunobiki Herb Garden / Ropeway", "nunobiki", "Gardens + city & bay views.", "12:00"),
        t("12:30", "Kitano Ijinkan stroll", "kitano-ijinkan", "Former foreign residences on the hill.", "14:00"),
        t("14:15", "Nankinmachi Chinatown snacks", "nankinmachi", "Street food between Motomachi & Sannomiya.", "15:30"),
        t("16:00", "Meriken Park & Harborland", "meriken-park", "Waterfront walk + Port Tower views.", "18:00"),
        t("18:30", "Kobe beef dinner", None, "Book a steakhouse near Sannomiya / Motomachi.", "20:15"),
        t("20:45", "Travel by JR Special Rapid · from Sannomiya to Osaka (Shinsaibashi)", "apt-hotel-11-shinsaibashi", "~30 min · no booking."),
      ]),
  day("d26", "2026-09-21", "Monday", "Tokyo", "JP", None,
      "Leave Osaka → Tokyo, Nakano Broadway & Shinjuku night",
      "Checkout Osaka, Nozomi to Tokyo (~2.5h), Shinjuku hotel check-in, Nakano Broadway otaku maze, then Azabudai/Roppongi, Tokyo Tower night and Kabukicho.",
      "Dinner near Azabudai / Roppongi or Shinjuku.",
      ["shinjuku", "nakano-broadway", "azabudai", "roppongi", "tokyo-tower", "kabukicho"],
      ["Nozomi Osaka → Tokyo (~2.5h).", "Local to Shinjuku hotel; short train to Nakano."],
      ["Nakano Broadway is ~5–10 min from Shinjuku by train.", "Apartment Hotel 11 nights end with morning checkout 21/9."],
      [
        t("09:00", "Checkout — Apartment Hotel 11", "apt-hotel-11-shinsaibashi", "Morning checkout · bags to Shin-Osaka."),
        t("09:45", "Travel by Nozomi Shinkansen · from Shin-Osaka to Tokyo", None, "Nozomi · reserved seats via SmartEX · ~2.5h · book ahead · Oversized Baggage if bags >160 cm.", "12:15"),
        t("12:30", "Hotel check-in — Shinjuku", "shinjuku", "Final Tokyo hotel · still to book."),
        t("13:45", "Travel by JR / metro · from Shinjuku to Nakano", "nakano-broadway", "~5–10 min · no booking."),
        t("14:00", "Nakano Broadway", "nakano-broadway", "Vintage, collectibles & otaku maze.", "17:30"),
        t("18:30", "Azabudai Hills / Roppongi", "azabudai", "Modern complex wander."),
        t("19:30", "Tokyo Tower night photos", "tokyo-tower", "Classic night landmark views."),
        t("20:30", "Kabukicho nightlife", "kabukicho", "Neon streets near the hotel."),
      ]),
  day("d27", "2026-09-22", "Tuesday", "Tokyo", "JP", None,
      "Nikko day trip (lake first)",
      "Early Tobu Spacia X to Nikko, bus UP first to Lake Chuzenji & Kegon Falls, then down to Toshogu in the afternoon (closer to the station if buses run late), evening return to Tokyo.",
      "Lunch by the lake / Chuzenji; dinner back in Tokyo.",
      ["chuzenji", "kegon-falls", "nikko-toshogu"],
      [
        "Tobu Spacia X from Asakusa ~06:30 (book reserved seats).",
        "Nikko Station → bus UP to Chuzenji / Kegon (~45–60m winding road).",
        "Afternoon bus DOWN to Toshogu, then train home.",
      ],
      [
        "Book Spacia X early — aim ~06:30 departure so the mountain bus isn’t a race.",
        "Do the lake/falls FIRST; Toshogu is nearer the station if traffic eats the afternoon.",
        "Comfortable shoes; mountain weather can be cooler than Tokyo.",
      ],
      [
        t("06:30", "Travel by Tobu Spacia X · from Asakusa to Nikko", "nikko-toshogu", "Limited express · reserved seats · book ahead · ~2h.", "08:30"),
        t("09:00", "Travel by bus · from Nikko Station to Lake Chuzenji / Kegon", "chuzenji", "Mountain bus UP · ~45–60 min · no booking · go up first."),
        t("10:00", "Kegon Falls & Lake Chuzenji", "kegon-falls", "Waterfall + lakeside stroll / lunch nearby.", "13:00"),
        t("13:30", "Travel by bus · from Chuzenji to Toshogu", "nikko-toshogu", "Bus DOWN · closer to Nikko Station for the return."),
        t("14:00", "Toshogu Shrine", "nikko-toshogu", "Ornate UNESCO shrine in the forest.", "16:15"),
        t("16:45", "Travel by Tobu limited express · from Nikko to Tokyo", None, "Reserved seats preferred · ~2h · evening arrival.", "18:45"),
        t("19:30", "Dinner in Tokyo", "shinjuku"),
      ]),
  day("d28", "2026-09-23", "Wednesday", "Tokyo", "JP", None,
      "Kamakura & Enoshima day trip",
      "Day trip to Kamakura (Great Buddha + Hasedera), scenic Enoden to Enoshima island lanes and seaside sunset, then back to Tokyo.",
      "Kamakura / Enoshima lunch; dinner back in Tokyo.",
      ["kamakura", "hasedera", "enoshima"],
      ["JR to Kamakura (~50m).", "Enoden coastal train to Enoshima.", "Return evening."],
      ["Enoden is the scenic coastal hop — worth it for photos."],
      [
        t("09:00", "Travel by JR Yokosuka / Shonan-Shinjuku · from Tokyo to Kamakura", "kamakura", "JR · ~50 min · no booking."),
        t("10:00", "Great Buddha & Hasedera", "kamakura", "Daibutsu + hillside temple.", "13:00"),
        t("13:30", "Travel by Enoden · from Kamakura to Enoshima", "enoshima", "Scenic coastal train · ~25 min · no booking."),
        t("14:00", "Enoshima island lanes & seaside walk", "enoshima", "Island lanes + seaside walk.", "17:30"),
        t("17:45", "Sunset by the sea", "enoshima", "If timing works."),
        t("18:30", "Travel by JR · from Enoshima / Kamakura to Tokyo", None, "JR · ~60–75 min · no booking."),
      ]),
  day("d29", "2026-09-24", "Thursday", "Tokyo", "JP", None,
      "Full shopping day & farewell dinner",
      "Ginza shopping morning (Ginza Six, Uniqlo Ginza, Itoya, depachika), afternoon in Shibuya/Omotesando, Akihabara or Shinjuku, then farewell dinner.",
      "Depachika graze; farewell wagyu or sushi dinner.",
      ["ginza", "omotesando", "akihabara", "shinjuku"],
      ["Morning in Ginza; one secondary area in the afternoon."],
      ["Confirm farewell dinner reservation and arrival time."],
      [
        t("10:00", "Ginza shopping — Ginza Six, Uniqlo, Itoya", "ginza", "Luxury + megastore classics.", "14:00"),
        t("14:00", "Depachika graze", "ginza", "Mitsukoshi / Matsuya basement food halls.", "15:30"),
        t("16:00", "Shopping — Shibuya / Omotesando, Akihabara or Shinjuku", "omotesando", "Second shopping district.", "18:30"),
        t("19:30", "Farewell Japan dinner", None, "Wagyu or sushi/omakase."),
      ]),
  day("d30", "2026-09-25", "Friday", "Tokyo", "JP", None,
      "Tokyo → Tirana via Dubai",
      "Checkout, transfer to Narita, and fly Emirates to Tirana via Dubai (DXB).",
      "Airport meal before departure.",
      ["narita"],
      ["Allow 2.5–3h door-to-gate for NRT.", "Emirates connection in Dubai (DXB)."],
      ["Book / confirm Emirates NRT → DXB → TIA.", "Passports ready at security."],
      [
        t("09:00", "Final pack & checkout", None),
        t("12:00", "Travel by N'EX / limousine · from Shinjuku to Narita", "narita", "N'EX reserved optional · ~60–90 min + airport buffer · allow 2.5–3h door-to-gate."),
        t("15:00", "Narita Airport", "narita", "Security, food, duty-free."),
        t("18:00", "Travel by Emirates · from Narita to Dubai to Tirana", "narita", "Book / confirm flight numbers & times."),
      ],
      {"mode": "flight", "label": "Tokyo → Tirana (via Dubai)", "detail": "Emirates · NRT → DXB → TIA · flight TBD", "duration": "to book / confirm"}),
]

TRIP = {
    "title": "Korea + Japan 2026",
    "subtitle": "Idan & Shahar itinerary",
    "dates": "August 26 – September 25, 2026",
    "route": ["Seoul", "Tokyo", "Hakone", "Kawaguchiko", "Kyoto", "Osaka", "Tokyo"],
    "flights": [
        {
            "id": "et0419",
            "journey": "outbound",
            "journeyLabel": "Tel Aviv → Seoul",
            "status": "booked",
            "airline": "Ethiopian Airlines",
            "flight": "ET0419",
            "date": "2026-08-26",
            "from": "TLV",
            "fromName": "Tel Aviv",
            "to": "ADD",
            "toName": "Addis Ababa",
            "depart": "15:35",
            "arrive": "19:50",
            "terminal": "TLV T3",
            "dayId": "d00",
            "note": "Leg 1 · ~4h15",
        },
        {
            "id": "et0672",
            "journey": "outbound",
            "journeyLabel": "Tel Aviv → Seoul",
            "status": "booked",
            "airline": "Ethiopian Airlines",
            "flight": "ET0672",
            "date": "2026-08-26",
            "from": "ADD",
            "fromName": "Addis Ababa",
            "to": "ICN",
            "toName": "Seoul Incheon",
            "depart": "22:35",
            "arrive": "16:00",
            "arriveDate": "2026-08-27",
            "terminal": "ADD T2 → ICN",
            "dayId": "d00",
            "note": "Leg 2 · overnight ~11h · lands next day",
        },
        {
            "id": "yp7321",
            "journey": "seoul-tokyo",
            "journeyLabel": "Seoul → Tokyo",
            "status": "booked",
            "airline": "Air Premia",
            "flight": "YP7321",
            "date": "2026-09-02",
            "from": "ICN",
            "fromName": "Seoul Incheon",
            "to": "NRT",
            "toName": "Tokyo Narita",
            "depart": "08:50",
            "arrive": "11:20",
            "terminal": "ICN T1 → NRT T2",
            "dayId": "d07",
            "note": "~2h30 · some boards list YP731",
        },
        {
            "id": "emirates-nrt-dxb",
            "journey": "tokyo-tirana",
            "journeyLabel": "Tokyo → Tirana",
            "status": "todo",
            "airline": "Emirates",
            "flight": "TBD",
            "date": "2026-09-25",
            "from": "NRT",
            "fromName": "Tokyo Narita",
            "to": "DXB",
            "toName": "Dubai",
            "depart": "—",
            "arrive": "—",
            "terminal": "NRT → DXB",
            "dayId": "d30",
            "note": "Leg 1 · Emirates · confirm flight #",
        },
        {
            "id": "emirates-dxb-tia",
            "journey": "tokyo-tirana",
            "journeyLabel": "Tokyo → Tirana",
            "status": "todo",
            "airline": "Emirates",
            "flight": "TBD",
            "date": "2026-09-25",
            "from": "DXB",
            "fromName": "Dubai",
            "to": "TIA",
            "toName": "Tirana",
            "depart": "—",
            "arrive": "—",
            "terminal": "DXB → TIA",
            "dayId": "d30",
            "note": "Leg 2 · Emirates · arrival may be next calendar day · confirm times",
        },
    ],
    "notes": [
        "Route: Tel Aviv → Seoul → Tokyo → Hakone → Kawaguchiko → Kyoto → Osaka (+ Kobe day) → Tokyo → Tirana (via Dubai).",
        "Outbound booked: ET0419 + ET0672 (26–27 Aug).",
        "Seoul→Tokyo booked: Air Premia YP7321 (2 Sep · ICN 08:50 → NRT 11:20).",
        "Sep 4: Tsukiji sushi/fish + teamLab Planets (weekday) + Odaiba + Ginza.",
        "Sep 5: Asakusa + Skytree + Akihabara.",
        "Sep 6: Kichijoji + Shimokitazawa day, night Street Kart ~19:00 (IDP).",
        "Sep 11: Arrive Kyoto (overnight bus) — rest + Gion/Pontocho.",
        "Sep 12: Fushimi Inari + Uji (Byodo-in / matcha) + Nishiki.",
        "Sep 14: Kibune nagashi somen (Hirobun walk-in) + Kurama trek + teamLab Biovortex booked 18:00–18:30. Sep 15: Kyoto zen → Osaka evening.",
        "Sep 20: Kobe day trip from Osaka.",
        "Sep 21: Leave Osaka for Tokyo.",
        "Sep 22: Nikko — Spacia X ~06:30, lake/Kegon first, Toshogu afternoon. Sep 23: Kamakura & Enoshima.",
        "Sep 24: Full Ginza shopping day + farewell dinner.",
        "Seoul hotel: Amanti Hongdae · 27 Aug–2 Sep.",
        "Tokyo first base: Hotel Gracery Shinjuku · 2–7 Sep (Kabukicho).",
        "Kyoto hotel: KABIN Koji · 11–15 Sep (Kawaramachi).",
        "Osaka hotel: Apartment Hotel 11 Shinsaibashi 2 · 15–21 Sep.",
        "Tokyo return base: Shinjuku (21–25 Sep).",
        "Leave Japan ~25 Sep: Emirates Narita → Dubai (DXB) → Tirana (TIA) — book / confirm flight numbers.",
        "Tap places for Google / Kakao / Naver / Yahoo! / Apple Maps.",
    ],
}


for d in DAYS:
    if d["id"] in TRANSFERS:
        d["transfer"] = TRANSFERS[d["id"]]
    for item in d.get("timeline") or []:
        if not item.get("category"):
            item["category"] = infer_category(item.get("title", ""), item.get("placeId"), item.get("note", ""))

def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

js = f"""/* Auto-generated trip data — Seoul + Japan detailed timelines */
window.TRIP = {dumps(TRIP)};
window.PLACES = {dumps(PLACES)};
window.DAYS = {dumps(DAYS)};
"""
OUT.write_text(js, encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
print(f"Days: {len(DAYS)}, Places: {len(PLACES)}")
print("Transfers:", sum(1 for d in DAYS if d.get("transfer")))
