#!/usr/bin/env python3
"""Build docs/js/data.js with Seoul + Japan detailed timelines."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "js" / "data.js"

def place(id, name, name_local, city, country, tags, lat, lng, blurb, taxi_address=None):
    p = {
        "id": id, "name": name, "nameJa": name_local, "city": city, "country": country,
        "tags": tags, "lat": lat, "lng": lng, "blurb": blurb,
    }
    if taxi_address:
        p["taxiAddress"] = taxi_address
    return p

PLACES = {}

def add(p):
    PLACES[p["id"]] = p

# --- Seoul ---
for p in [
    place("brick-hotel", "9 Brick Hotel Hongdae", "나인브릭호텔", "Seoul", "KR", ["hotel", "booked"], 37.5563, 126.9236, "Booked — our Seoul base in Hongdae.", "서울특별시 마포구 와우산로 94, 나인브릭호텔"),
    place("icn", "Incheon Airport (ICN)", "인천국제공항", "Seoul", "KR", ["transport"], 37.4602, 126.4407, "Seoul arrival / departure."),
    place("myeongdong", "Myeongdong", "명동", "Seoul", "KR", ["shopping", "food", "neighborhood"], 37.5636, 126.9869, "K-beauty, street food, neon shopping."),
    place("hongdae", "Hongdae", "홍대", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5563, 126.9236, "Student arts district — cafés, bars, street performers."),
    place("gyeongbokgung", "Gyeongbokgung Palace", "경복궁", "Seoul", "KR", ["must-see", "culture"], 37.5796, 126.9770, "Main royal palace — rent hanbok for free entry vibe."),
    place("bukchon", "Bukchon Hanok Village", "북촌한옥마을", "Seoul", "KR", ["must-see", "neighborhood", "culture"], 37.5826, 126.9831, "Traditional hanok hillside lanes."),
    place("ikseon", "Ikseon-dong", "익선동", "Seoul", "KR", ["neighborhood", "food", "culture"], 37.5740, 126.9897, "Hip hanok alleys with cafés and bars."),
    place("insadong", "Insadong", "인사동", "Seoul", "KR", ["shopping", "culture", "food"], 37.5742, 126.9847, "Tea houses, crafts, souvenir shopping."),
    place("cheonggyecheon", "Cheonggyecheon Stream", "청계천", "Seoul", "KR", ["must-see", "nature", "neighborhood"], 37.5696, 126.9784, "Downtown stream walk between Insadong and markets."),
    place("gwangjang", "Gwangjang Market", "광장시장", "Seoul", "KR", ["must-see", "food", "market"], 37.5700, 126.9996, "Bindaetteok, mayak gimbap, night market energy (open late)."),
    place("eunpyeong", "Eunpyeong Hanok Village", "은평한옥마을", "Seoul", "KR", ["neighborhood", "culture"], 37.6408, 126.9345, "Quieter traditional village alternative."),
    place("lotte-world", "Lotte World Adventure", "롯데월드", "Seoul", "KR", ["must-see", "park"], 37.5110, 127.0980, "Indoor/outdoor theme park — full day."),
    place("lotte-tower", "Lotte World Tower Seoul Sky", "롯데월드타워", "Seoul", "KR", ["must-see", "view"], 37.5126, 127.1025, "One of the world’s tallest — Seoul Sky observatory."),
    place("seokchon", "Seokchon Lake", "석촌호수", "Seoul", "KR", ["neighborhood", "nature"], 37.5095, 127.1035, "Lake walk beside Lotte Tower."),
    place("jimjilbang", "Jimjilbang (spa complex)", "찜질방", "Seoul", "KR", ["culture", "onsen"], 37.5110, 127.0980, "Korean bathhouse near Jamsil — perfect reset after Lotte World."),
    place("jogyesa", "Jogyesa Temple", "조계사", "Seoul", "KR", ["temple", "culture"], 37.5735, 126.9825, "Major Buddhist temple near Insadong."),
    place("changdeokgung", "Changdeokgung + Secret Garden", "창덕궁 후원", "Seoul", "KR", ["must-see", "culture"], 37.5794, 126.9910, "UNESCO palace — book Secret Garden timed tour."),
    place("gangnam", "Gangnam", "강남", "Seoul", "KR", ["neighborhood", "shopping"], 37.4979, 127.0276, "Treatments, shopping, K-pop landmarks."),
    place("unni-guide", "Unni Guide Center", "언니 가이드 센터", "Seoul", "KR", ["must-see", "culture"], 37.5045, 127.0250, "Gangnam Unni Guide — clinic matching, skin analysis & booking help for visitors (book ahead)."),
    place("bongeunsa", "Bongeunsa Temple", "봉은사", "Seoul", "KR", ["temple", "culture"], 37.5152, 127.0574, "Temple beside COEX — calm contrast to Gangnam."),
    place("coex", "COEX & Starfield Library", "코엑스 별마당도서관", "Seoul", "KR", ["must-see", "shopping", "culture"], 37.5117, 127.0595, "Giant mall + iconic Starfield Library."),
    place("dongdaemun", "Dongdaemun Night Market / DDP", "동대문", "Seoul", "KR", ["shopping", "nightlife", "food"], 37.5665, 127.0092, "Night fashion markets + DDP / APM / Hyundai City Outlets."),
    place("seongsu", "Seongsu-dong", "성수동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5445, 127.0557, "Brooklyn-feel cafés, pop-ups, and design shops."),
    place("seoul-forest", "Seoul Forest", "서울숲", "Seoul", "KR", ["must-see", "park", "nature"], 37.5443, 127.0375, "Large urban park next to Seongsu."),
    place("seoulistique", "Seoulistique Skin", "서울리스틱 스킨", "Seoul", "KR", ["must-see", "culture"], 37.5448, 127.0565, "Facial + skin analysis in Seongsu — book via Instagram @seoulistique.skin / WhatsApp."),
    place("yeonnam", "Yeonnam-dong", "연남동", "Seoul", "KR", ["neighborhood", "food", "shopping"], 37.5662, 126.9254, "Chill cafés and boutiques next to Hongdae."),
    place("namsan-cable", "Namsan Cable Car", "남산케이블카", "Seoul", "KR", ["must-see", "transport", "view"], 37.5486, 126.9905, "Cable car up Namsan toward N Seoul Tower."),
    place("n-tower", "N Seoul Tower", "N서울타워", "Seoul", "KR", ["must-see", "view"], 37.5512, 126.9882, "Namsan sunset views + love locks."),
    place("itaewon", "Itaewon", "이태원", "Seoul", "KR", ["nightlife", "food", "neighborhood"], 37.5345, 126.9944, "International bars, LGBTQ+ friendly nightlife."),
]:
    add(p)

# --- Japan (existing + a few extras) ---
for p in [
    place("keio-plaza", "Keio Plaza Hotel Tokyo", "京王プラザホテル", "Tokyo", "JP", ["hotel", "inspiration"], 35.6906, 139.6921, "Dad's stay idea near Shinjuku — not booked for our trip."),
    place("narita", "Narita Airport (NRT)", "成田国際空港", "Tokyo", "JP", ["transport"], 35.7720, 140.3929, "Tokyo arrival/departure."),
    place("shinjuku", "Shinjuku", "新宿", "Tokyo", "JP", ["neighborhood", "food", "nightlife"], 35.6938, 139.7034, "Neon, shopping, Godzilla."),
    place("shibuya-crossing", "Shibuya Crossing", "渋谷スクランブル交差点", "Tokyo", "JP", ["must-see", "icon"], 35.6595, 139.7005, "Scramble + Hachiko."),
    place("meiji-jingu", "Meiji Jingu", "明治神宮", "Tokyo", "JP", ["must-see", "culture", "shrine"], 35.6764, 139.6993, "Forest shrine."),
    place("takeshita", "Takeshita Street", "竹下通り", "Tokyo", "JP", ["food", "shopping"], 35.6702, 139.7050, "Harajuku crepes & youth fashion."),
    place("cat-street", "Cat Street", "キャットストリート", "Tokyo", "JP", ["shopping", "neighborhood"], 35.6658, 139.7038, "Stylish Harajuku side street."),
    place("omotesando", "Omotesando", "表参道", "Tokyo", "JP", ["shopping", "architecture"], 35.6652, 139.7122, "Tree-lined boutiques."),
    place("disneysea", "Tokyo DisneySea", "東京ディズニーシー", "Tokyo", "JP", ["must-see", "park"], 35.6267, 139.8851, "Unique Disney park."),
    place("asakusa", "Asakusa / Senso-ji", "浅草寺", "Tokyo", "JP", ["must-see", "culture", "food"], 35.7148, 139.7967, "Classic temple Tokyo."),
    place("kappabashi", "Kappabashi Street", "合羽橋道具街", "Tokyo", "JP", ["food", "shopping"], 35.7155, 139.7870, "Kitchen-town souvenirs."),
    place("skytree", "Tokyo Skytree", "東京スカイツリー", "Tokyo", "JP", ["must-see", "view"], 35.7101, 139.8107, "634m tower."),
    place("tsukiji", "Tsukiji Outer Market", "築地場外市場", "Tokyo", "JP", ["must-see", "food"], 35.6654, 139.7707, "Breakfast graze."),
    place("imperial-east", "Imperial Palace East Gardens", "皇居東御苑", "Tokyo", "JP", ["culture", "park"], 35.6865, 139.7575, "Quiet castle gardens."),
    place("ginza", "Ginza", "銀座", "Tokyo", "JP", ["shopping", "food"], 35.6712, 139.7649, "Dept stores & depachika."),
    place("teamlab-planets", "teamLab Planets Tokyo", "チームラボプラネッツ", "Tokyo", "JP", ["must-see", "culture"], 35.6490, 139.7868, "Immersive digital art."),
    place("odaiba", "Odaiba / DiverCity Gundam", "お台場", "Tokyo", "JP", ["park", "shopping"], 35.6251, 139.7755, "Gundam + waterfront."),
    place("ameyoko", "Ameyoko Market", "アメ横", "Tokyo", "JP", ["food", "market"], 35.7095, 139.7745, "Street-food market."),
    place("akihabara", "Akihabara", "秋葉原", "Tokyo", "JP", ["park", "shopping"], 35.7023, 139.7745, "Arcades & anime."),
    place("golden-gai", "Shinjuku Golden Gai", "新宿ゴールデン街", "Tokyo", "JP", ["must-see", "nightlife"], 35.6938, 139.7047, "Tiny bar alleys."),
    place("daikanyama", "Daikanyama T-Site", "代官山T-SITE", "Tokyo", "JP", ["culture", "food"], 35.6492, 139.7032, "Bookstore complex."),
    place("nakameguro", "Nakameguro / Meguro River", "中目黒", "Tokyo", "JP", ["neighborhood", "food"], 35.6442, 139.6988, "Riverside boutiques."),
    place("ny-bar", "New York Bar (Park Hyatt)", "ニューヨークバー", "Tokyo", "JP", ["nightlife", "view"], 35.6855, 139.6905, "Lost in Translation bar."),
    place("kajikaso", "Hotel Kajikaso", "ホテルかじか荘", "Hakone", "JP", ["hotel", "onsen", "inspiration"], 35.2335, 139.0885, "Dad's Hakone ryokan idea — not booked for our trip."),
    place("owakudani", "Owakudani", "大涌谷", "Hakone", "JP", ["must-see", "nature", "food"], 35.2424, 139.0204, "Volcanic valley + black eggs."),
    place("hakone-shrine", "Hakone Shrine", "箱根神社", "Hakone", "JP", ["must-see", "shrine"], 35.2051, 139.0256, "Lakeside torii — best at sunrise."),
    place("lake-ashi", "Lake Ashi Pirate Ship", "箱根海賊船", "Hakone", "JP", ["nature", "park"], 35.2065, 139.0250, "Sightseeing cruise."),
    place("open-air", "Hakone Open-Air Museum", "箱根彫刻の森美術館", "Hakone", "JP", ["culture"], 35.2445, 139.0515, "Outdoor sculpture museum."),
    place("fuji-lawson", "Lawson Kawaguchiko Station", "ローソン河口湖駅前", "Kawaguchiko", "JP", ["icon", "must-see"], 35.4983, 138.7689, "Famous Fuji convenience-store shot."),
    place("oishi-park", "Oishi Park", "大石公園", "Kawaguchiko", "JP", ["must-see", "view"], 35.5245, 138.7470, "Sunset Fuji lakeside."),
    place("chureito", "Chureito Pagoda", "忠霊塔", "Kawaguchiko", "JP", ["must-see", "icon"], 35.5012, 138.8013, "Sunrise pagoda + Fuji."),
    place("fuji-q", "Fuji-Q Highland", "富士急ハイランド", "Kawaguchiko", "JP", ["must-see", "park"], 35.4871, 138.7806, "World-class coasters."),
    place("musse-kyoto", "Hotel Musse Kyoto", "ホテルミュッセ京都四条河原町名鉄", "Kyoto", "JP", ["hotel", "inspiration"], 35.0037, 135.7685, "Dad's Kyoto stay idea near Kawaramachi — not booked for our trip."),
    place("kenninji", "Kennin-ji", "建仁寺", "Kyoto", "JP", ["temple", "culture"], 35.0008, 135.7735, "Oldest Zen temple in Kyoto."),
    place("teamlab-biovortex", "teamLab Biovortex Kyoto", "チームラボ バイオヴォルテックス 京都", "Kyoto", "JP", ["must-see", "culture"], 34.9828, 135.7568, "Japan’s largest teamLab — ~7 min walk from Kyoto Station Hachijo East."),
    place("gion", "Gion", "祇園", "Kyoto", "JP", ["must-see", "neighborhood"], 35.0037, 135.7788, "Geisha district."),
    place("pontocho", "Pontocho Alley", "先斗町", "Kyoto", "JP", ["food", "nightlife"], 35.0045, 135.7712, "Dinner alley by the river."),
    place("fushimi-inari", "Fushimi Inari Taisha", "伏見稲荷大社", "Kyoto", "JP", ["must-see", "shrine"], 34.9671, 135.7727, "Thousands of torii."),
    place("kiyomizu", "Kiyomizu-dera", "清水寺", "Kyoto", "JP", ["must-see", "temple"], 34.9949, 135.7850, "Wooden stage temple."),
    place("sannenzaka", "Sannenzaka & Ninenzaka", "三年坂・二年坂", "Kyoto", "JP", ["must-see", "food"], 34.9958, 135.7815, "Stone postcard streets."),
    place("kinkakuji", "Kinkaku-ji", "金閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0394, 135.7292, "Golden Pavilion."),
    place("nishiki", "Nishiki Market", "錦市場", "Kyoto", "JP", ["must-see", "food"], 35.0050, 135.7649, "Kyoto’s kitchen."),
    place("otagi", "Otagi Nenbutsu-ji", "愛宕念仏寺", "Kyoto", "JP", ["must-see", "temple"], 35.0317, 135.6628, "1,200 rakan statues."),
    place("adashino", "Adashino Nenbutsu-ji", "化野念仏寺", "Kyoto", "JP", ["temple", "culture"], 35.0267, 135.6645, "Bamboo & stone Buddhas."),
    place("saga-toriimoto", "Saga Toriimoto", "嵯峨鳥居本", "Kyoto", "JP", ["neighborhood"], 35.0255, 135.6680, "Preserved approach street."),
    place("bamboo", "Arashiyama Bamboo Grove", "竹林の小径", "Kyoto", "JP", ["must-see", "nature"], 35.0173, 135.6721, "Iconic bamboo path."),
    place("kimono-forest", "Kimono Forest", "キモノフォレスト", "Kyoto", "JP", ["icon"], 35.0153, 135.6775, "Kimono cylinder pillars."),
    place("togetsukyo", "Togetsukyo Bridge", "渡月橋", "Kyoto", "JP", ["icon", "nature"], 35.0135, 135.6778, "Arashiyama bridge."),
    place("monkey-park", "Iwatayama Monkey Park", "嵐山モンキーパーク", "Kyoto", "JP", ["park", "nature"], 35.0117, 135.6761, "Monkeys + city view."),
    place("tenryuji", "Tenryu-ji", "天龍寺", "Kyoto", "JP", ["temple", "culture"], 35.0156, 135.6736, "UNESCO Zen garden."),
    place("kurama-dera", "Kurama-dera", "鞍馬寺", "Kyoto", "JP", ["must-see", "temple", "nature"], 35.1181, 135.7709, "Start of forest trek."),
    place("kifune", "Kifune Shrine", "貴船神社", "Kyoto", "JP", ["must-see", "shrine"], 35.1216, 135.7631, "Lantern stone stairs."),
    place("kawadoko", "Kibune Kawadoko Dining", "貴船川床", "Kyoto", "JP", ["must-see", "food"], 35.1205, 135.7638, "Lunch over the stream."),
    place("kurama-onsen", "Kurama Onsen", "鞍馬温泉", "Kyoto", "JP", ["onsen"], 35.1128, 135.7725, "Mountain onsen."),
    place("ginkakuji", "Ginkaku-ji", "銀閣寺", "Kyoto", "JP", ["must-see", "temple"], 35.0264, 135.7986, "Silver Pavilion."),
    place("philosophers-path", "Philosopher’s Path", "哲学の道", "Kyoto", "JP", ["neighborhood", "nature"], 35.0205, 135.7955, "Canal stroll."),
    place("nanzenji", "Nanzen-ji", "南禅寺", "Kyoto", "JP", ["temple", "culture"], 35.0116, 135.7945, "Zen temple + aqueduct."),
    place("uji", "Uji / Byodo-in", "宇治・平等院", "Kyoto", "JP", ["food", "temple"], 34.8894, 135.8077, "Matcha capital + Phoenix Hall."),
    place("daiwa-hiroshima", "Daiwa Roynet Hiroshima", "ダイワロイネットホテル広島", "Hiroshima", "JP", ["hotel", "inspiration"], 34.3927, 132.4553, "Dad's Hiroshima hotel idea — we day-trip from Osaka."),
    place("shukkeien", "Shukkeien Garden", "縮景園", "Hiroshima", "JP", ["culture", "park"], 34.3995, 132.4674, "Miniature landscape garden."),
    place("peace-park", "Peace Memorial Park", "平和記念公園", "Hiroshima", "JP", ["must-see", "culture"], 34.3955, 132.4536, "Dome + museum."),
    place("okonomiyaki", "Okonomi-mura", "お好み村", "Hiroshima", "JP", ["food", "must-see"], 34.3938, 132.4622, "Hiroshima okonomiyaki hall."),
    place("miyajima", "Itsukushima Shrine", "厳島神社", "Hiroshima", "JP", ["must-see", "shrine"], 34.2960, 132.3198, "Floating torii."),
    place("misen", "Mt. Misen Ropeway", "弥山ロープウェイ", "Hiroshima", "JP", ["nature", "view"], 34.2905, 132.3185, "Island summit."),
    place("cross-osaka", "Cross Hotel Osaka", "クロスホテル大阪", "Osaka", "JP", ["hotel", "inspiration"], 34.6693, 135.5013, "Dad's Osaka stay idea near Namba — not booked for our trip."),
    place("kuromon", "Kuromon Market", "黒門市場", "Osaka", "JP", ["must-see", "food"], 34.6664, 135.5064, "Osaka’s kitchen."),
    place("osaka-castle", "Osaka Castle", "大阪城", "Osaka", "JP", ["culture", "must-see"], 34.6873, 135.5262, "Castle + park."),
    place("dotonbori", "Dotonbori", "道頓堀", "Osaka", "JP", ["must-see", "food", "nightlife"], 34.6687, 135.5013, "Neon food crawl."),
    place("usj", "Universal Studios Japan", "ユニバーサル・スタジオ・ジャパン", "Osaka", "JP", ["must-see", "park"], 34.6654, 135.4323, "Nintendo World + coasters."),
    place("nara-park", "Nara Park / Todai-ji", "奈良公園・東大寺", "Osaka", "JP", ["must-see", "culture"], 34.6889, 135.8398, "Deer + Great Buddha."),
    place("shinsekai", "Shinsekai / Tsutenkaku", "新世界・通天閣", "Osaka", "JP", ["food", "neighborhood"], 34.6525, 135.5063, "Retro Osaka."),
    place("tenjinbashi", "Tenjinbashi-suji", "天神橋筋商店街", "Osaka", "JP", ["shopping", "food"], 34.7045, 135.5110, "Longest arcade."),
    place("umeda-sky", "Umeda Sky Building", "梅田スカイビル", "Osaka", "JP", ["must-see", "view"], 34.7055, 135.4897, "Floating Garden view."),
    place("ramen-museum", "Instant Ramen Museum", "カップヌードルミュージアム池田", "Osaka", "JP", ["food", "park"], 34.8195, 135.4258, "Make your Cup Noodle."),
    place("solaria", "Solaria Nishitetsu Ginza", "ソラリア西鉄ホテル銀座", "Tokyo", "JP", ["hotel", "inspiration"], 35.6695, 139.7668, "Dad's Tokyo return stay idea — not booked for our trip."),
    place("ryogoku", "Ryogoku Kokugikan", "両国国技館", "Tokyo", "JP", ["must-see", "culture"], 35.6971, 139.7935, "Sumo stadium."),
    place("shimokitazawa", "Shimokitazawa", "下北沢", "Tokyo", "JP", ["neighborhood", "shopping"], 35.6616, 139.6683, "Vintage & indie cafés."),
    place("omoide-yokocho", "Omoide Yokocho (Memory Lane)", "思い出横丁", "Tokyo", "JP", ["food", "nightlife", "must-see"], 35.6935, 139.6995, "Smoky yakitori alleys by Shinjuku station."),
    place("shibuya-sky", "Shibuya Sky", "渋谷スカイ", "Tokyo", "JP", ["must-see", "view"], 35.6585, 139.7024, "Sunset observation deck — book timed tickets."),
    place("ueno-park", "Ueno Park", "上野公園", "Tokyo", "JP", ["park", "culture"], 35.7147, 139.7733, "Museums, temples, and green space."),
    place("ghibli", "Ghibli Museum", "三鷹の森ジブリ美術館", "Tokyo", "JP", ["must-see", "culture", "park"], 35.6962, 139.5703, "Lottery/reservation required — Mitaka."),
    place("inokashira", "Inokashira Park", "井の頭恩賜公園", "Tokyo", "JP", ["park", "nature"], 35.7000, 139.5750, "Lake park near Ghibli / Kichijoji."),
    place("hozenji", "Hozenji Yokocho", "法善寺横丁", "Osaka", "JP", ["neighborhood", "culture", "food"], 34.6678, 135.5025, "Mossy lantern alley near Dotonbori."),
    place("shinsaibashi", "Shinsaibashi", "心斎橋", "Osaka", "JP", ["shopping", "neighborhood"], 34.6750, 135.5013, "Major shopping arcade next to Namba."),
    place("amerikamura", "Amerikamura", "アメリカ村", "Osaka", "JP", ["neighborhood", "shopping", "nightlife"], 34.6728, 135.4985, "Youth fashion & casual dinner area."),
    place("roppongi", "Roppongi", "六本木", "Tokyo", "JP", ["neighborhood", "nightlife"], 35.6628, 139.7314, "Nightlife and city views."),
    place("azabudai", "Azabudai Hills", "麻布台ヒルズ", "Tokyo", "JP", ["shopping", "culture", "architecture"], 35.6605, 139.7400, "Modern complex — teamLab Borderless home."),
    place("tokyo-tower", "Tokyo Tower", "東京タワー", "Tokyo", "JP", ["must-see", "view", "icon"], 35.6586, 139.7454, "Classic Tokyo night landmark."),
    place("kabukicho", "Kabukicho", "歌舞伎町", "Tokyo", "JP", ["nightlife", "neighborhood"], 35.6950, 139.7026, "Neon nightlife district in Shinjuku."),
    place("shinjuku-gyoen", "Shinjuku Gyoen", "新宿御苑", "Tokyo", "JP", ["park", "nature", "must-see"], 35.6852, 139.7101, "Spacious national garden — calm morning walk."),
    place("nakano-broadway", "Nakano Broadway", "中野ブロードウェイ", "Tokyo", "JP", ["shopping", "culture"], 35.7093, 139.6652, "Otaku shopping maze — figures, vintage, Mandarake."),
    place("kamakura", "Kamakura / Kotoku-in", "鎌倉・高徳院", "Tokyo", "JP", ["must-see", "culture", "temple"], 35.3167, 139.5357, "Great Buddha + Enoden coastal line day trip."),
    place("kasuga", "Kasuga Taisha", "春日大社", "Osaka", "JP", ["shrine", "culture"], 34.6814, 135.8482, "Lantern shrine in Nara."),
]:
    add(p)

def day(id, date, weekday, city, country, hotel_id, title, summary, food, place_ids, transport, tips, timeline, transfer=None):
    d = {
        "id": id, "date": date, "weekday": weekday, "city": city, "country": country,
        "hotelId": hotel_id, "title": title, "summary": summary, "food": food,
        "placeIds": place_ids, "transport": transport, "tips": tips, "timeline": timeline,
    }
    if transfer:
        d["transfer"] = transfer
    return d

def infer_category(title, place_id, note=""):
    text = f"{title} {note}".lower()
    tags = []
    if place_id and place_id in PLACES:
        tags = PLACES[place_id].get("tags") or []
    if place_id and place_id in PLACES and "hotel" in tags:
        return "hotel"
    if any(k in text for k in ("flight", "train", "shinkansen", "romancecar", "subway", "bus", "ferry", "transfer", "depart", "airport", "ropeway", "monorail")) or "transport" in tags:
        return "transit"
    if any(k in text for k in ("breakfast", "lunch", "dinner", "food", "market", "crepe", "ramen", "sushi", "café", "cafe", "okonomi", "graze", "snack", "brunch")) or "food" in tags or "market" in tags:
        return "dining"
    if any(k in text for k in ("shop", "souvenir", "arcade street", "ginza", "depachika", "don quijote")) or "shopping" in tags:
        return "shopping"
    if any(k in text for k in ("temple", "shrine", "palace", "garden", "museum", "zen", "sumo", "tea", "hanok", "secret garden")) or "culture" in tags or "temple" in tags or "shrine" in tags:
        return "culture"
    if "park" in tags or any(k in text for k in ("disney", "universal", "fuji-q", "lotte world", "teamlab", "skytree", "tower", "park", "monkey", "cruise", "rope drop")):
        return "attraction"
    if "nightlife" in tags:
        return "dining"
    return "attraction"

def t(time, title, place_id=None, note="", end=None, category=None):
    item = {"time": time, "title": title, "note": note}
    if place_id:
        item["placeId"] = place_id
    if end:
        item["end"] = end
    if category:
        item["category"] = category
    return item


TRANSFERS = {
    "d06": {
        "mode": "flight",
        "label": "Seoul → Tokyo",
        "detail": "ICN/GMP → NRT/HND (confirm your flight)",
        "duration": "~2.5h flight + transfers",
        "fromCity": "Seoul",
        "toCity": "Tokyo",
    },
    "d11": {
        "mode": "train",
        "label": "Tokyo → Hakone",
        "detail": "Odakyu Romancecar Shinjuku → Hakone-Yumoto (~¥2,470)",
        "duration": "~80 minutes",
        "fromCity": "Tokyo",
        "toCity": "Hakone",
    },
    "d12": {
        "mode": "bus",
        "label": "Hakone → Kawaguchiko",
        "detail": "Bus via Gotemba + Fujikyu bus (~¥1,600–2,100)",
        "duration": "~1.5–2h",
        "fromCity": "Hakone",
        "toCity": "Kawaguchiko",
    },
    "d14": {
        "mode": "train",
        "label": "Kawaguchiko → Kyoto (Mishima route)",
        "detail": "Express bus to Mishima (~90m) + Tokaido Shinkansen (~110m). Prefer this over overnight bus.",
        "duration": "~3.5–4h · ~¥12,500–13,500",
        "fromCity": "Kawaguchiko",
        "toCity": "Kyoto",
    },
    "d19": {
        "mode": "train",
        "label": "Kyoto → Osaka",
        "detail": "JR/private line into central Osaka (~30m)",
        "duration": "~30–45 minutes",
        "fromCity": "Kyoto",
        "toCity": "Osaka",
    },
    "d22": {
        "mode": "train",
        "label": "Osaka ↔ Hiroshima day trip",
        "detail": "Early Shinkansen to Hiroshima (~80m), return evening",
        "duration": "~80m each way",
        "fromCity": "Osaka",
        "toCity": "Hiroshima",
    },
    "d24": {
        "mode": "train",
        "label": "Osaka → Tokyo",
        "detail": "Nozomi Shinkansen (~2.5h)",
        "duration": "~2.5 hours",
        "fromCity": "Osaka",
        "toCity": "Tokyo",
    },
    "d28": {
        "mode": "flight",
        "label": "Tokyo → Home",
        "detail": "N'EX / Monorail to NRT or HND",
        "duration": "Allow 2.5–3h to airport",
        "fromCity": "Tokyo",
        "toCity": "Home",
    },
}

DAYS = [
  day("d01", "2026-08-27", "Thursday", "Seoul", "KR", "brick-hotel",
      "Arrival & night bites",
      "Land in Seoul, check in at 9 Brick Hotel Hongdae, easy Myeongdong night-food walk, then a chill optional snack/drink around Hongdae if you still have energy.",
      "Myeongdong street food night market.",
      ["icn", "brick-hotel", "myeongdong", "hongdae"],
      ["ICN → hotel (~1h).", "Subway/taxi to Myeongdong."],
      ["Get T-money / Climate Card.", "Keep arrival evening light — big days start Friday."],
      [
        t("14:00", "Land & transfer to hotel", "icn"),
        t("17:00", "Check in — 9 Brick Hotel Hongdae", "brick-hotel"),
        t("18:30", "Myeongdong night food street walk", "myeongdong", "Easy street food + neon shopping streets.", "21:30"),
        t("22:00", "Optional Hongdae chill walk", "hongdae", "Late snack/drink or street vibe if energy remains."),
      ]),
  day("d02", "2026-08-28", "Friday", "Seoul", "KR", "brick-hotel",
      "Royal heart of Seoul",
      "Culture day with Option A/B: Gyeongbokgung (+ hanbok) or Eunpyeong first, then Bukchon → Ikseon → Insadong, and Gwangjang Market dinner.",
      "Gwangjang Market street-food feast.",
      ["eunpyeong", "gyeongbokgung", "bukchon", "ikseon", "insadong", "gwangjang"],
      ["Hongdae → Gyeongbokgung (~25m).", "Walk Bukchon → Ikseon → Insadong → Gwangjang."],
      ["Rent hanbok for free palace entry vibe.", "Option A starts at the palace; Option B does quieter Eunpyeong Hanok Village first."],
      [
        t("09:00", "Option A/B: Gyeongbokgung morning", "gyeongbokgung", "Option A: palace (+ hanbok). Option B: Eunpyeong Hanok Village first, then the palace.", "12:30"),
        t("13:00", "Bukchon Hanok Village", "bukchon", "Respect residents while photographing.", "14:15"),
        t("14:30", "Ikseon-dong → Insadong", "ikseon", "Hip alleys, crafts, tea houses.", "17:00"),
        t("17:30", "Gwangjang Market feast", "gwangjang", "Street-food dinner (~until late).", "22:30"),
      ]),
  day("d03", "2026-08-29", "Saturday", "Seoul", "KR", "brick-hotel",
      "Temples, Gangnam Unni Guide & Dongdaemun",
      "Jogyesa + Changdeokgung Secret Garden in the morning, then a Gangnam block with Unni Guide + treatment, Bongeunsa, COEX Starfield, and Dongdaemun night malls.",
      "Lunch near the palace / Insadong; light dinner near Dongdaemun.",
      ["hongdae", "jogyesa", "changdeokgung", "unni-guide", "gangnam", "bongeunsa", "coex", "dongdaemun"],
      ["Hongdae → Jogyesa / Changdeokgung.", "Subway to Gangnam / Sinnonhyeon for Unni Guide.", "COEX → Dongdaemun evening."],
      ["Book Secret Garden timed slot — closed Mondays.", "Book Unni Guide Center appointment ahead.", "Night malls: APM, DDP Fashion Mall, Hyundai City Outlets."],
      [
        t("08:30", "Optional animal café breakfast in Hongdae", "hongdae", "Easy animal-café vibe before temples."),
        t("09:30", "Jogyesa Temple", "jogyesa", "Calm temple stop near Insadong.", "10:30"),
        t("10:45", "Changdeokgung & Secret Garden", "changdeokgung", "Pre-book Secret Garden timed slot.", "13:00"),
        t("14:00", "Unni Guide Center — Gangnam", "unni-guide", "Clinic matching / skin analysis / booking help. Book ahead.", "15:30"),
        t("15:45", "Gangnam treatment slot", "gangnam", "Treatment booked via Unni Guide / clinic.", "17:00"),
        t("17:15", "Bongeunsa Temple", "bongeunsa", "Quiet contrast next to COEX.", "18:00"),
        t("18:15", "COEX & Starfield Library", "coex", "Mall + iconic library glow.", "19:45"),
        t("20:15", "Dongdaemun night market & malls", "dongdaemun", "DDP + APM / DDP Fashion Mall / Hyundai City Outlets.", "23:30"),
      ]),
  day("d04", "2026-08-30", "Sunday", "Seoul", "KR", "brick-hotel",
      "Seongsu, N Tower sunset & Itaewon",
      "Breakfast and second treatment in Seongsu, hang around the cool neighborhood + Seoul Forest, Namsan cable to N Seoul Tower sunset, then Itaewon nightlife.",
      "Breakfast/cafés in Seongsu; dinner in Itaewon.",
      ["seongsu", "seoulistique", "seoul-forest", "namsan-cable", "n-tower", "itaewon"],
      ["Head to Seongsu late morning.", "Seoul Forest → Namsan → Itaewon."],
      ["Book Seoulistique via Instagram @seoulistique.skin / WhatsApp.", "Book N Tower for sunset; cable-car tickets at the base."],
      [
        t("10:00", "Seongsu breakfast & neighborhood stroll", "seongsu", "Cool cafés, boutiques, pop-ups.", "11:30"),
        t("12:00", "Seoulistique facial (2nd treatment)", "seoulistique", "Skin analysis + facial in Seongsu.", "13:45"),
        t("14:00", "More Seongsu + Seoul Forest", "seoul-forest", "Keep exploring the area, then park break.", "16:30"),
        t("17:30", "Namsan cable car", "namsan-cable", "Up toward N Seoul Tower.", "18:00"),
        t("18:05", "N Seoul Tower sunset", "n-tower", "City views + love locks.", "19:30"),
        t("20:00", "Itaewon / Homo Hill nightlife", "itaewon", "Dinner, bars, LGBTQ+ friendly night.", "24:00"),
      ]),
  day("d05", "2026-08-31", "Monday", "Seoul", "KR", "brick-hotel",
      "Lotte World Monday + spa night",
      "Move Lotte World to quieter Monday: full park day, Lotte Tower / Seokchon views, then only jimjilbang spa + dinner — you'll be wiped, so keep the night short.",
      "Park / Lotte mall snacks; simple dinner near Jamsil after the spa.",
      ["lotte-world", "seokchon", "lotte-tower", "jimjilbang"],
      ["Subway to Jamsil (~40–50m from Hongdae).", "Stay Jamsil-side for spa + dinner."],
      ["Book Lotte World ahead — Monday is usually less crowded than weekend.", "Evening is spa + dinner only — no extra nightlife."],
      [
        t("08:30", "Convenience-store breakfast & subway to Jamsil", "brick-hotel"),
        t("10:00", "Lotte World", "lotte-world", "Full park day while it's quieter.", "17:00"),
        t("17:15", "Seokchon Lake + Lotte World Tower Seoul Sky", "lotte-tower", "Lake stroll and skyline views.", "19:00"),
        t("19:30", "Jimjilbang spa reset", "jimjilbang", "Soak off the park day — keep it chill.", "21:30"),
        t("21:45", "Simple dinner near Jamsil", "jimjilbang", "Eat and crash — no Hongdae night planned.", "22:45"),
      ]),
  day("d06", "2026-09-01", "Tuesday", "Tokyo", "JP", None,
      "Seoul → Tokyo & Shinjuku lights",
      "Fly Seoul to Tokyo, set up Suica and eSIM, then a Shinjuku evening in Omoide Yokocho or Golden Gai.",
      "Yakitori in Omoide Yokocho or Golden Gai drinks.",
      ["icn", "narita", "shinjuku", "omoide-yokocho", "golden-gai"],
      ["Hotel → ICN/GMP.", "Flight to Tokyo.", "Airport → Tokyo hotel (Shinjuku area)."],
      ["Confirm flight times.", "Set up Suica/Pasmo on arrival."],
      [
        t("08:00", "Checkout & airport transfer", "icn", "ICN or GMP — match your ticket."),
        t("13:00", "Flight to Tokyo", "icn", "Adjust to real schedule."),
        t("17:30", "Land, Suica/eSIM, hotel check-in", None),
        t("19:30", "Shinjuku explore", "shinjuku"),
        t("20:00", "Omoide Yokocho or Golden Gai", "omoide-yokocho", "Memory Lane yakitori or tiny alley bars.", "23:00"),
      ]),
  day("d07", "2026-09-02", "Wednesday", "Tokyo", "JP", None,
      "West Tokyo: culture, pop & Shibuya Sky",
      "West Tokyo: Meiji Jingu, Harajuku and Omotesando, Shibuya Crossing, and a pre-booked Shibuya Sky sunset.",
      "Harajuku snacks; Shibuya dinner & drinks.",
      ["meiji-jingu", "takeshita", "omotesando", "shibuya-crossing", "shibuya-sky"],
      ["Walk/Yamanote between Harajuku and Shibuya."],
      ["Book Shibuya Sky sunset slot ~4 weeks ahead.", "Passport for tax-free shopping."],
      [
        t("09:00", "Meiji Jingu", "meiji-jingu", "Forest shrine morning calm.", "10:30"),
        t("10:45", "Takeshita Street & Omotesando", "takeshita", "Pop fashion → tree-lined boutiques.", "13:00"),
        t("13:30", "Shibuya Crossing & Center-gai", "shibuya-crossing", "Scramble, megastores, people-watching.", "16:30"),
        t("17:00", "Shibuya Sky sunset", "shibuya-sky", "Timed ticket — arrive early.", "19:00"),
        t("19:30", "Dinner & drinks in Shibuya", "shibuya-crossing"),
      ]),
  day("d08", "2026-09-03", "Thursday", "Tokyo", "JP", None,
      "Asakusa to Skytree & Electric Town",
      "Early Senso-ji & Nakamise, walk via Tokyo Mizumachi to Tokyo Skytree / Solamachi, then Akihabara ending with izakaya.",
      "Nakamise snacks; izakaya dinner.",
      ["asakusa", "skytree", "akihabara"],
      ["Subway to Asakusa.", "Walk Asakusa → Mizumachi → Skytree; then transit to Akihabara."],
      ["Senso-ji early morning.", "Walk Asakusa → Mizumachi → Skytree / Solamachi."],
      [
        t("08:00", "Senso-ji & Nakamise", "asakusa", "Early temple + shopping street.", "11:00"),
        t("11:15", "Walk to Tokyo Skytree via Mizumachi", "skytree", "Easy riverside / Solamachi approach.", "14:00"),
        t("15:00", "Akihabara Electric Town", "akihabara", "Gaming, anime, electronics.", "18:30"),
        t("19:00", "Izakaya dinner — Akihabara or Kanda", "akihabara"),
      ]),
  day("d09", "2026-09-04", "Friday", "Tokyo", "JP", None,
      "Bay views & Ginza evening",
      "Tsukiji seafood breakfast, Odaiba Gundam and bay views, then a Ginza evening.",
      "Tsukiji sushi breakfast; Ginza dinner.",
      ["tsukiji", "odaiba", "ginza"],
      ["Tsukiji early.", "Odaiba via Yurikamome/Rinkai."],
      ["Yurikamome/Rinkai for Odaiba."],
      [
        t("08:00", "Tsukiji Outer Market breakfast", "tsukiji", "Fresh seafood / sushi graze.", "10:30"),
        t("11:30", "Odaiba waterfront & Gundam", "odaiba", "Bay views + DiverCity.", "16:00"),
        t("17:30", "Ginza upscale walk & dinner", "ginza"),
      ]),
  day("d10", "2026-09-05", "Saturday", "Tokyo", "JP", None,
      "Ghibli, Inokashira & Shimokitazawa",
      "Ghibli Museum, Inokashira Park, and Shimokitazawa.",
      "Kichijoji / Shimokitazawa cafés.",
      ["ghibli", "inokashira", "shimokitazawa"],
      ["Ghibli: Mitaka + walk; then Inokashira & Shimokita."],
      ["Ghibli tickets open on the 10th of each month at 10:00 JST for the following month."],
      [
        t("09:30", "Ghibli Museum", "ghibli", "Timed entry — reservation required.", "12:00"),
        t("12:30", "Inokashira Park", "inokashira", "Lake park near Mitaka / Kichijoji."),
        t("14:30", "Shimokitazawa vintage & cafés", "shimokitazawa", "Thrift, coffee, indie shops.", "18:30"),
        t("19:30", "Dinner near Shimokita / Shinjuku", None),
      ]),
  day("d11", "2026-09-06", "Sunday", "Hakone", "JP", None,
      "Romancecar & volcanic valleys",
      "Morning Takkyubin of big bags Tokyo→Kyoto, Romancecar (try Observation Car) into Hakone, Owakudani, then ryokan onsen + kaiseki.",
      "Black eggs; kaiseki dinner at ryokan.",
      ["owakudani"],
      ["Odakyu Romancecar Shinjuku → Hakone-Yumoto (~80m, ~¥2,470).", "Ropeway to Owakudani."],
      ["Send large suitcases Tokyo→Kyoto via hotel Takkyubin; travel Hakone/Fuji with backpacks only.", "Book Romancecar ~1 month ahead — request front Observation Car seats.", "Enjoy onsen etiquette."],
      [
        t("08:00", "Takkyubin drop at Tokyo hotel", None, "Forward large bags to the Kyoto hotel."),
        t("09:00", "Romancecar from Shinjuku", None, "~80 minutes to Hakone-Yumoto. Observation Car."),
        t("11:00", "Arrive Hakone-Yumoto", None),
        t("12:30", "Owakudani volcanic valley", "owakudani", "Black eggs + Fuji views.", "16:00"),
        t("17:00", "Ryokan check-in & onsen", None),
        t("19:00", "Kaiseki dinner", None),
      ]),
  day("d12", "2026-09-07", "Monday", "Kawaguchiko", "JP", None,
      "Torii dawn, Fuji shores & Chureito sunset",
      "Dawn at Hakone Shrine, Lake Ashi cruise, bus to Kawaguchiko, Fuji Lawson, Oishi Park, then Chureito Pagoda at sunset.",
      "Lakeside dinner near Kawaguchiko.",
      ["hakone-shrine", "lake-ashi", "fuji-lawson", "chureito", "oishi-park"],
      ["Hakone → Gotemba → Fujikyu to Kawaguchiko (~1.5–2h, ¥1,600–2,100).", "Taxi/bus to Chureito for sunset."],
      ["Book Kawaguchiko lodging before this night."],
      [
        t("05:30", "Hakone Shrine floating torii", "hakone-shrine", "Early morning visit.", "07:15"),
        t("07:45", "Lake Ashi pirate ship", "lake-ashi", "Then return toward Yumoto.", "09:15"),
        t("10:00", "Bus transfer to Kawaguchiko", None, "Gotemba change → Fujikyu bus.", "12:30"),
        t("13:00", "Lawson Fuji View photo stop", "fuji-lawson"),
        t("14:00", "Hotel check-in", None),
        t("15:30", "Oishi Park", "oishi-park", "Lake Kawaguchiko shore.", "16:30"),
        t("17:15", "Chureito Pagoda sunset", "chureito", "Fuji and pagoda viewpoint.", "18:45"),
      ]),
  day("d13", "2026-09-08", "Tuesday", "Kawaguchiko", "JP", None,
      "Fuji-Q Highland",
      "Full day at Fuji-Q Highland, then hoto noodles and an early night.",
      "Park food; local hoto noodle dinner.",
      ["fuji-q"],
      ["Arrive for park opening."],
      ["Do-Dodonpa / Takabisha.", "Mishima Shinkansen to Kyoto tomorrow."],
      [
        t("08:30", "Depart for Fuji-Q Highland", "fuji-q"),
        t("09:00", "Fuji-Q Highland", "fuji-q", "Full theme-park day.", "18:30"),
        t("19:30", "Hoto noodle dinner", None),
      ]),
  day("d14", "2026-09-09", "Wednesday", "Kyoto", "JP", None,
      "Arrive Kyoto, teamLab Biovortex & Gion",
      "Mishima Shinkansen to Kyoto, hotel drop + bag pickup, timed teamLab Biovortex (largest Japan museum, by Kyoto Station), then Gion and Pontocho.",
      "Nishiki snacks; Pontocho riverside dinner.",
      ["teamlab-biovortex", "nishiki", "gion", "pontocho"],
      ["Bus Kawaguchiko → Mishima (~90m) + Shinkansen to Kyoto (~110m).", "~7 min walk from Kyoto Station Hachijo East to Biovortex."],
      ["Book teamLab Biovortex timed tickets.", "Collect Takkyubin bags at hotel.", "Respectful photos in Gion."],
      [
        t("08:30", "Bus to Mishima Station", None, "Express bus ~90 minutes."),
        t("10:30", "Shinkansen Mishima → Kyoto", None, "~110 minutes on Tokaido line."),
        t("13:00", "Hotel drop & collect forwarded bags", None),
        t("14:00", "teamLab Biovortex Kyoto", "teamlab-biovortex", "Japan’s largest teamLab, near Kyoto Station.", "17:00"),
        t("17:30", "Nishiki Market", "nishiki", "Short graze.", "18:15"),
        t("18:30", "Gion dusk stroll", "gion", "Geisha district lanes.", "19:30"),
        t("19:45", "Pontocho riverside dinner", "pontocho", "Kamogawa atmosphere.", "21:30"),
      ]),
  day("d15", "2026-09-10", "Thursday", "Kyoto", "JP", None,
      "Torii gates & ancient slopes",
      "Sunrise at Fushimi Inari, Kiyomizu-dera, and Sannenzaka & Ninenzaka.",
      "Convenience breakfast; Higashiyama café lunch.",
      ["fushimi-inari", "kiyomizu", "sannenzaka"],
      ["Early Keihan/JR to Fushimi.", "Bus/walk Higashiyama cluster."],
      ["Hike higher at Fushimi.", "Kinkaku-ji is on Sep 13 with east Kyoto."],
      [
        t("06:30", "Fushimi Inari Taisha", "fushimi-inari", "Sunrise torii hike.", "10:00"),
        t("10:30", "Café break", None),
        t("11:30", "Kiyomizu-dera", "kiyomizu", "Wooden stage temple.", "13:00"),
        t("13:15", "Sannenzaka & Ninenzaka", "sannenzaka", "Preserved stone streets.", "16:00"),
        t("18:30", "Dinner near hotel", None),
      ]),
  day("d16", "2026-09-11", "Friday", "Kyoto", "JP", None,
      "Arashiyama bamboo & monkey park",
      "West Kyoto day: stone statues, bamboo grove, Tenryu-ji, the bridge, and Monkey Park views.",
      "Lunch near Togetsukyo Bridge.",
      ["otagi", "adashino", "saga-toriimoto", "bamboo", "tenryuji", "kimono-forest", "togetsukyo", "monkey-park"],
      ["Train/bus toward Saga-Arashiyama; walk the west Kyoto chain."],
      ["Bamboo grove in the morning.", "Monkey park hike."],
      [
        t("08:00", "Otagi Nenbutsu-ji", "otagi", "1,200 stone rakan statues.", "09:15"),
        t("09:30", "Adashino Nenbutsu-ji", "adashino"),
        t("10:30", "Saga Toriimoto Street", "saga-toriimoto"),
        t("11:15", "Bamboo Grove & Tenryu-ji", "bamboo", "Iconic path + Zen garden.", "13:00"),
        t("13:15", "Kimono Forest & lunch", "kimono-forest", "Near Arashiyama Station / bridge.", "14:45"),
        t("15:00", "Togetsukyo Bridge", "togetsukyo"),
        t("15:30", "Iwatayama Monkey Park", "monkey-park", "Panoramic city views.", "17:30"),
        t("19:00", "Central Kyoto dinner", None),
      ]),
  day("d17", "2026-09-12", "Saturday", "Kyoto", "JP", None,
      "Kurama & Kibune mountain day",
      "Kurama and Kibune: temple, forest walk, kawadoko riverside lunch (Hirobun / Fujiya), and Kurama Onsen.",
      "Kawadoko lunch over the river.",
      ["kurama-dera", "kifune", "kawadoko", "kurama-onsen"],
      ["Demachiyanagi → Eizan to Kurama (~30m, ~¥430).", "Trek ~45m to Kibune.", "Return Kibuneguchi."],
      ["Reserve kawadoko weeks ahead (Hirobun or Fujiya)."],
      [
        t("08:30", "Train to Kurama", "kurama-dera", "Via Demachiyanagi + Eizan."),
        t("09:30", "Kurama-dera Temple", "kurama-dera", "Mountain temple visit.", "10:45"),
        t("11:00", "Forest trek to Kibune", None, "~45 minutes through cedar forest.", "11:45"),
        t("12:00", "Kifune Shrine", "kifune", "Red lantern stairs.", "13:00"),
        t("13:15", "Kawadoko riverside lunch", "kawadoko", "Decks over the stream — Hirobun / Fujiya reserved.", "15:00"),
        t("15:30", "Kurama Onsen", "kurama-onsen", "Mountain onsen.", "17:30"),
        t("18:30", "Return to Kyoto", None),
      ]),
  day("d18", "2026-09-13", "Sunday", "Kyoto", "JP", None,
      "Zen gardens & Golden Pavilion",
      "East Kyoto zen path from Ginkaku-ji to Nanzen-ji, then Kinkaku-ji at golden hour and a farewell Kyoto dinner.",
      "Lunch near Nanzen-ji; celebratory Kyoto dinner.",
      ["ginkakuji", "philosophers-path", "nanzenji", "kinkakuji", "pontocho"],
      ["Bus to Ginkaku-ji; walk path; taxi ~25–30m to Kinkaku-ji."],
      ["Forward bags to Osaka tonight."],
      [
        t("08:30", "Ginkaku-ji (Silver Pavilion)", "ginkakuji", "Morning gardens.", "10:15"),
        t("10:30", "Philosopher’s Path", "philosophers-path", "Peaceful canal walk.", "12:15"),
        t("12:30", "Nanzen-ji & lunch", "nanzenji", "Temple + aqueduct.", "14:30"),
        t("15:30", "Kinkaku-ji golden hour", "kinkakuji", "Taxi across town for sunlight on gold.", "17:30"),
        t("19:00", "Farewell Kyoto dinner", "pontocho"),
      ]),
  day("d19", "2026-09-14", "Monday", "Osaka", "JP", None,
      "Transfer to Osaka & street food heaven",
      "Short hop to Osaka, castle park and Shinsekai, then a Dotonbori food crawl.",
      "Takoyaki & okonomiyaki in Dotonbori.",
      ["osaka-castle", "shinsekai", "dotonbori", "hozenji"],
      ["Kyoto → Osaka train (~30–45m).", "Book an Osaka hotel near Namba/Dotonbori."],
      ["Base Osaka for USJ, Nara, and Hiroshima day trip."],
      [
        t("09:30", "Train Kyoto → Osaka", None, "~30 minutes."),
        t("11:00", "Hotel check-in", None),
        t("12:30", "Osaka Castle Park", "osaka-castle", "Castle grounds stroll.", "15:00"),
        t("15:30", "Shinsekai & Tsutenkaku", "shinsekai", "Retro Osaka vibes.", "17:30"),
        t("18:30", "Dotonbori food crawl", "dotonbori", "Glico sign photos + street food.", "21:00"),
        t("21:15", "Hozenji Yokocho alley", "hozenji", "Mossy lantern lane near Dotonbori."),
      ]),
  day("d20", "2026-09-15", "Tuesday", "Osaka", "JP", None,
      "Universal Studios Japan",
      "All day at Universal Studios Japan — Nintendo World and Harry Potter. Express Pass must be booked exactly 2 months ahead at midnight JST.",
      "Park snacks; Namba ramen.",
      ["usj"],
      ["Subway to Universal City (~25–35m). Leave by ~07:45."],
      ["Book Express Pass exactly 2 months prior at 00:00 Japan time — locks Nintendo World entry window and skips the rope-drop sprint.", "Check Nintendo World entry rules."],
      [
        t("07:45", "Depart hotel", None),
        t("09:00", "USJ with Express Pass", "usj", "Timed Nintendo World + Harry Potter priority.", "12:30"),
        t("12:30", "Lunch in park", "usj"),
        t("13:30", "Afternoon rides & shows", "usj", "Continue headliners.", "18:30"),
        t("18:30", "Evening at USJ", "usj", "", "21:00"),
        t("21:30", "Return Namba", None),
      ]),
  day("d21", "2026-09-16", "Wednesday", "Osaka", "JP", None,
      "Nara deer park day trip",
      "Day trip to Nara for deer park, Todai-ji and Kasuga Taisha; evening back in Shinsaibashi and Amerikamura.",
      "Nara lunch; Amerikamura casual dinner.",
      ["nara-park", "kasuga", "shinsaibashi", "amerikamura"],
      ["Kintetsu/JR to Nara (~45m).", "Return for evening shopping."],
      ["Deer crackers are fun — guard bags.", "Bowing deer are bold."],
      [
        t("08:30", "Train to Nara", "nara-park"),
        t("09:30", "Nara Park & deer", "nara-park", "Todai-ji Great Buddha.", "13:00"),
        t("13:15", "Kasuga Taisha", "kasuga", "Lantern shrine.", "14:30"),
        t("15:00", "Return to Osaka", None),
        t("17:30", "Shinsaibashi shopping", "shinsaibashi"),
        t("19:30", "Dinner in Amerikamura", "amerikamura"),
      ]),
  day("d22", "2026-09-17", "Thursday", "Osaka", "JP", None,
      "Hiroshima & Miyajima day trip",
      "Early Shinkansen day trip to Miyajima and Hiroshima Peace Park, okonomiyaki, then back to Osaka.",
      "Hiroshima-style okonomiyaki before return.",
      ["miyajima", "peace-park", "okonomiyaki"],
      ["Early Nozomi/Sakura to Hiroshima (~80m).", "Ferry to Miyajima.", "Evening Shinkansen back."],
      ["Check tide times for torii.", "Early Shinkansen outbound."],
      [
        t("07:00", "Shinkansen to Hiroshima", None, "~80 minutes."),
        t("09:00", "Miyajima Island & Itsukushima", "miyajima", "Floating torii + island stroll.", "13:00"),
        t("14:00", "Peace Memorial Park & Museum", "peace-park", "Allow real time.", "16:30"),
        t("17:00", "Hiroshima okonomiyaki", "okonomiyaki"),
        t("18:30", "Shinkansen return to Osaka", None, "Evening arrival."),
      ]),
  day("d23", "2026-09-18", "Friday", "Osaka", "JP", None,
      "Umeda & modern Osaka",
      "Modern Osaka: Umeda shopping, sunset at Umeda Sky Building, drinks in Namba or Nakazakicho.",
      "Umeda lunch; Namba evening drinks.",
      ["umeda-sky", "dotonbori"],
      ["Subway to Umeda.", "Return south for nightlife."],
      ["Floating Garden Observatory at golden hour."],
      [
        t("10:00", "Umeda shopping", "umeda-sky", "Hep Five, Grand Front Osaka.", "14:00"),
        t("16:00", "Umeda Sky Building sunset", "umeda-sky", "Kuchu Teien Observatory.", "18:30"),
        t("20:00", "Drinks in Namba / Nakazakicho", "dotonbori"),
      ]),
  day("d24", "2026-09-19", "Saturday", "Tokyo", "JP", None,
      "Return to Tokyo & nightlife",
      "Shinkansen back to Tokyo (~2.5h), check into a Ginza/Shiodome-area hotel (best for NRT+HND), then Roppongi or Azabudai, Tokyo Tower night and Kabukicho.",
      "Roppongi/Azabudai dinner.",
      ["ginza", "roppongi", "azabudai", "tokyo-tower", "kabukicho"],
      ["Nozomi Osaka → Tokyo (~2.5h).", "Local transfer to Ginza / Shiodome hotel."],
      ["Ginza/Shiodome lodging for Narita and Haneda access."],
      [
        t("09:00", "Shinkansen to Tokyo", None, "~2.5 hours."),
        t("12:30", "Hotel check-in — Ginza / Shiodome", "ginza", "Shopping + dual-airport access."),
        t("14:30", "Roppongi or Azabudai Hills", "azabudai", "Modern complex wander.", "17:30"),
        t("18:30", "Tokyo Tower night photos", "tokyo-tower"),
        t("20:00", "Kabukicho arcade & bars", "kabukicho"),
      ]),
  day("d25", "2026-09-20", "Sunday", "Tokyo", "JP", None,
      "Soft Tokyo day",
      "Calm morning in Shinjuku Gyoen, then Shimokitazawa or Nakano Broadway, and a specialty wagyu dinner.",
      "Wagyu BBQ dinner.",
      ["shinjuku-gyoen", "shimokitazawa", "nakano-broadway"],
      ["Gyoen near Shinjuku.", "Choose Shimokita OR Nakano Broadway."],
      ["Gyoen has an entry fee — worth it for calm."],
      [
        t("09:30", "Shinjuku Gyoen National Garden", "shinjuku-gyoen", "Relaxing green morning.", "12:00"),
        t("13:30", "Shimokitazawa OR Nakano Broadway", "shimokitazawa", "Vintage thrift vs otaku maze.", "17:30"),
        t("19:00", "Specialty wagyu BBQ dinner", None),
      ]),
  day("d26", "2026-09-21", "Monday", "Tokyo", "JP", None,
      "Easy Tokyo day",
      "Free day in Tokyo: late wake-up, coffee in Shimokitazawa or Harajuku, or light shopping.",
      "Café hopping; dinner near the hotel.",
      ["shimokitazawa", "takeshita", "ginza"],
      ["Ginza / Harajuku / Shimokitazawa."],
      ["Pick one neighborhood."],
      [
        t("10:30", "Late start — café of choice", None),
        t("13:00", "Shimokitazawa / Harajuku / Ginza", "shimokitazawa", "One neighborhood focus.", "17:30"),
        t("19:30", "Dinner near hotel", "ginza"),
      ]),
  day("d27", "2026-09-22", "Tuesday", "Tokyo", "JP", None,
      "Last-minute shopping & fine dining",
      "Ginza shopping (or Akihabara / Shibuya), then a farewell dinner.",
      "Farewell fine dining in Tokyo.",
      ["ginza", "akihabara", "shibuya-crossing"],
      ["One shopping focus."],
      ["Pack non-essentials tonight."],
      [
        t("10:00", "Shopping — Ginza focus (or Akihabara / Shibuya)", "ginza", "Choose your lane.", "17:00"),
        t("19:30", "Farewell celebratory dinner", None, "Toast the trip."),
      ]),
  day("d28", "2026-09-23", "Wednesday", "Tokyo", "JP", None,
      "Pack & departure",
      "Pack, travel to Narita or Haneda, and fly home.",
      "Airport meal.",
      ["narita"],
      ["Allow 2.5–3h door-to-gate.", "N'EX to NRT or Monorail/train to HND."],
      ["Confirm actual flight date (Sep 23 or 24).", "Keep passports & Visit Japan Web QR handy."],
      [
        t("09:00", "Final pack & checkout", None),
        t("12:00", "Depart for airport", "narita", "Match NRT vs HND to your ticket."),
        t("15:00", "Airport", "narita", "Security, food, duty-free."),
        t("18:00", "Departure", "narita", "Confirm actual flight time."),
      ]),
]

TRIP = {
    "title": "Korea + Japan 2026",
    "subtitle": "Idan & Shahar itinerary (dad's Excel was inspiration only)",
    "dates": "August 27 – September 23/24, 2026",
    "route": ["Seoul", "Tokyo", "Hakone", "Kawaguchiko", "Kyoto", "Osaka", "Tokyo"],
    "notes": [
        "Route: Seoul → Tokyo → Hakone → Kawaguchiko → Kyoto → Osaka → Tokyo.",
        "Sep 5: Ghibli Museum + Inokashira + Shimokitazawa.",
        "Sep 21: easy Tokyo day — late start, cafés, light shopping.",
        "Departure Sep 23/24 — confirm flight.",
        "Tap places for Google / Kakao / Naver / Yahoo! / Apple Maps.",
    ],
}

for d in DAYS:
    if d["id"] in TRANSFERS:
        d["transfer"] = TRANSFERS[d["id"]]
    for item in d.get("timeline") or []:
        if not item.get("category"):
            item["category"] = infer_category(item.get("title", ""), item.get("placeId"), item.get("note", ""))

def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

js = f"""/* Auto-generated trip data — Seoul + Japan detailed timelines */
window.TRIP = {dumps(TRIP)};
window.PLACES = {dumps(PLACES)};
window.DAYS = {dumps(DAYS)};
"""
OUT.write_text(js, encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
print(f"Days: {len(DAYS)}, Places: {len(PLACES)}")
print("Transfers:", sum(1 for d in DAYS if d.get("transfer")))
